// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: kiseki/v1/advisory.proto

// Workflow Advisory & Client Telemetry service.
// Spec: ADR-020 (analyst), ADR-021 (architect), specs/features/workflow-advisory.feature,
// specs/invariants.md I-WA1..I-WA18.
//
// Isolation: this service is served on its own gRPC listener and processed
// on a tokio runtime separate from the data path (I-WA2).
// All operations are re-authorized per message via mTLS identity (I-WA3).
// Telemetry and rejection responses are size-padded and latency-bucketed
// (ADR-021 §8) to prevent covert channels (I-WA15).

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowAdvisoryService_DeclareWorkflow_FullMethodName    = "/kiseki.v1.WorkflowAdvisoryService/DeclareWorkflow"
	WorkflowAdvisoryService_EndWorkflow_FullMethodName        = "/kiseki.v1.WorkflowAdvisoryService/EndWorkflow"
	WorkflowAdvisoryService_PhaseAdvance_FullMethodName       = "/kiseki.v1.WorkflowAdvisoryService/PhaseAdvance"
	WorkflowAdvisoryService_GetWorkflowStatus_FullMethodName  = "/kiseki.v1.WorkflowAdvisoryService/GetWorkflowStatus"
	WorkflowAdvisoryService_AdvisoryStream_FullMethodName     = "/kiseki.v1.WorkflowAdvisoryService/AdvisoryStream"
	WorkflowAdvisoryService_SubscribeTelemetry_FullMethodName = "/kiseki.v1.WorkflowAdvisoryService/SubscribeTelemetry"
)

// WorkflowAdvisoryServiceClient is the client API for WorkflowAdvisoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowAdvisoryServiceClient interface {
	// Lifecycle (unary, per-operation mTLS authorized — I-WA3).
	DeclareWorkflow(ctx context.Context, in *DeclareWorkflowRequest, opts ...grpc.CallOption) (*DeclareWorkflowResponse, error)
	EndWorkflow(ctx context.Context, in *EndWorkflowRequest, opts ...grpc.CallOption) (*EndWorkflowResponse, error)
	PhaseAdvance(ctx context.Context, in *PhaseAdvanceRequest, opts ...grpc.CallOption) (*PhaseAdvanceResponse, error)
	GetWorkflowStatus(ctx context.Context, in *GetWorkflowStatusRequest, opts ...grpc.CallOption) (*GetWorkflowStatusResponse, error)
	// Main channel: hints in, telemetry out, multiplexed (I-WA5..I-WA8).
	// One bidi stream per active workflow.
	AdvisoryStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AdvisoryClientMessage, AdvisoryServerMessage], error)
	// Telemetry-only (server-streaming) variant for callers who do not submit hints.
	SubscribeTelemetry(ctx context.Context, in *SubscribeTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryEvent], error)
}

type workflowAdvisoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowAdvisoryServiceClient(cc grpc.ClientConnInterface) WorkflowAdvisoryServiceClient {
	return &workflowAdvisoryServiceClient{cc}
}

func (c *workflowAdvisoryServiceClient) DeclareWorkflow(ctx context.Context, in *DeclareWorkflowRequest, opts ...grpc.CallOption) (*DeclareWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeclareWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowAdvisoryService_DeclareWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdvisoryServiceClient) EndWorkflow(ctx context.Context, in *EndWorkflowRequest, opts ...grpc.CallOption) (*EndWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowAdvisoryService_EndWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdvisoryServiceClient) PhaseAdvance(ctx context.Context, in *PhaseAdvanceRequest, opts ...grpc.CallOption) (*PhaseAdvanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhaseAdvanceResponse)
	err := c.cc.Invoke(ctx, WorkflowAdvisoryService_PhaseAdvance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdvisoryServiceClient) GetWorkflowStatus(ctx context.Context, in *GetWorkflowStatusRequest, opts ...grpc.CallOption) (*GetWorkflowStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowStatusResponse)
	err := c.cc.Invoke(ctx, WorkflowAdvisoryService_GetWorkflowStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdvisoryServiceClient) AdvisoryStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AdvisoryClientMessage, AdvisoryServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkflowAdvisoryService_ServiceDesc.Streams[0], WorkflowAdvisoryService_AdvisoryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AdvisoryClientMessage, AdvisoryServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowAdvisoryService_AdvisoryStreamClient = grpc.BidiStreamingClient[AdvisoryClientMessage, AdvisoryServerMessage]

func (c *workflowAdvisoryServiceClient) SubscribeTelemetry(ctx context.Context, in *SubscribeTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkflowAdvisoryService_ServiceDesc.Streams[1], WorkflowAdvisoryService_SubscribeTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTelemetryRequest, TelemetryEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowAdvisoryService_SubscribeTelemetryClient = grpc.ServerStreamingClient[TelemetryEvent]

// WorkflowAdvisoryServiceServer is the server API for WorkflowAdvisoryService service.
// All implementations must embed UnimplementedWorkflowAdvisoryServiceServer
// for forward compatibility.
type WorkflowAdvisoryServiceServer interface {
	// Lifecycle (unary, per-operation mTLS authorized — I-WA3).
	DeclareWorkflow(context.Context, *DeclareWorkflowRequest) (*DeclareWorkflowResponse, error)
	EndWorkflow(context.Context, *EndWorkflowRequest) (*EndWorkflowResponse, error)
	PhaseAdvance(context.Context, *PhaseAdvanceRequest) (*PhaseAdvanceResponse, error)
	GetWorkflowStatus(context.Context, *GetWorkflowStatusRequest) (*GetWorkflowStatusResponse, error)
	// Main channel: hints in, telemetry out, multiplexed (I-WA5..I-WA8).
	// One bidi stream per active workflow.
	AdvisoryStream(grpc.BidiStreamingServer[AdvisoryClientMessage, AdvisoryServerMessage]) error
	// Telemetry-only (server-streaming) variant for callers who do not submit hints.
	SubscribeTelemetry(*SubscribeTelemetryRequest, grpc.ServerStreamingServer[TelemetryEvent]) error
	mustEmbedUnimplementedWorkflowAdvisoryServiceServer()
}

// UnimplementedWorkflowAdvisoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowAdvisoryServiceServer struct{}

func (UnimplementedWorkflowAdvisoryServiceServer) DeclareWorkflow(context.Context, *DeclareWorkflowRequest) (*DeclareWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeclareWorkflow not implemented")
}
func (UnimplementedWorkflowAdvisoryServiceServer) EndWorkflow(context.Context, *EndWorkflowRequest) (*EndWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndWorkflow not implemented")
}
func (UnimplementedWorkflowAdvisoryServiceServer) PhaseAdvance(context.Context, *PhaseAdvanceRequest) (*PhaseAdvanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PhaseAdvance not implemented")
}
func (UnimplementedWorkflowAdvisoryServiceServer) GetWorkflowStatus(context.Context, *GetWorkflowStatusRequest) (*GetWorkflowStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowStatus not implemented")
}
func (UnimplementedWorkflowAdvisoryServiceServer) AdvisoryStream(grpc.BidiStreamingServer[AdvisoryClientMessage, AdvisoryServerMessage]) error {
	return status.Error(codes.Unimplemented, "method AdvisoryStream not implemented")
}
func (UnimplementedWorkflowAdvisoryServiceServer) SubscribeTelemetry(*SubscribeTelemetryRequest, grpc.ServerStreamingServer[TelemetryEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTelemetry not implemented")
}
func (UnimplementedWorkflowAdvisoryServiceServer) mustEmbedUnimplementedWorkflowAdvisoryServiceServer() {
}
func (UnimplementedWorkflowAdvisoryServiceServer) testEmbeddedByValue() {}

// UnsafeWorkflowAdvisoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowAdvisoryServiceServer will
// result in compilation errors.
type UnsafeWorkflowAdvisoryServiceServer interface {
	mustEmbedUnimplementedWorkflowAdvisoryServiceServer()
}

func RegisterWorkflowAdvisoryServiceServer(s grpc.ServiceRegistrar, srv WorkflowAdvisoryServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowAdvisoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowAdvisoryService_ServiceDesc, srv)
}

func _WorkflowAdvisoryService_DeclareWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclareWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdvisoryServiceServer).DeclareWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdvisoryService_DeclareWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdvisoryServiceServer).DeclareWorkflow(ctx, req.(*DeclareWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdvisoryService_EndWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdvisoryServiceServer).EndWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdvisoryService_EndWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdvisoryServiceServer).EndWorkflow(ctx, req.(*EndWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdvisoryService_PhaseAdvance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhaseAdvanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdvisoryServiceServer).PhaseAdvance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdvisoryService_PhaseAdvance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdvisoryServiceServer).PhaseAdvance(ctx, req.(*PhaseAdvanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdvisoryService_GetWorkflowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdvisoryServiceServer).GetWorkflowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdvisoryService_GetWorkflowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdvisoryServiceServer).GetWorkflowStatus(ctx, req.(*GetWorkflowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdvisoryService_AdvisoryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkflowAdvisoryServiceServer).AdvisoryStream(&grpc.GenericServerStream[AdvisoryClientMessage, AdvisoryServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowAdvisoryService_AdvisoryStreamServer = grpc.BidiStreamingServer[AdvisoryClientMessage, AdvisoryServerMessage]

func _WorkflowAdvisoryService_SubscribeTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowAdvisoryServiceServer).SubscribeTelemetry(m, &grpc.GenericServerStream[SubscribeTelemetryRequest, TelemetryEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowAdvisoryService_SubscribeTelemetryServer = grpc.ServerStreamingServer[TelemetryEvent]

// WorkflowAdvisoryService_ServiceDesc is the grpc.ServiceDesc for WorkflowAdvisoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowAdvisoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiseki.v1.WorkflowAdvisoryService",
	HandlerType: (*WorkflowAdvisoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeclareWorkflow",
			Handler:    _WorkflowAdvisoryService_DeclareWorkflow_Handler,
		},
		{
			MethodName: "EndWorkflow",
			Handler:    _WorkflowAdvisoryService_EndWorkflow_Handler,
		},
		{
			MethodName: "PhaseAdvance",
			Handler:    _WorkflowAdvisoryService_PhaseAdvance_Handler,
		},
		{
			MethodName: "GetWorkflowStatus",
			Handler:    _WorkflowAdvisoryService_GetWorkflowStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AdvisoryStream",
			Handler:       _WorkflowAdvisoryService_AdvisoryStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeTelemetry",
			Handler:       _WorkflowAdvisoryService_SubscribeTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kiseki/v1/advisory.proto",
}
