// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kiseki/v1/chunk.proto

// Chunk Storage context — encrypted chunks, placement, EC, GC, retention.
// Spec: specs/architecture/data-models/chunk.rs,
//       specs/architecture/api-contracts.md#Chunk-Storage-context,
//       specs/features/chunk-storage.feature,
//       invariants.md I-C1..I-C4, I-K1, I-K7, I-K10.
//
// Intra-process in Rust. This proto defines the on-disk envelope metadata
// and the internal request/response shapes used by `ChunkOps` callers.

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptionAlgorithm int32

const (
	EncryptionAlgorithm_ENCRYPTION_ALGORITHM_UNSPECIFIED EncryptionAlgorithm = 0
	EncryptionAlgorithm_ENCRYPTION_ALGORITHM_AES_256_GCM EncryptionAlgorithm = 1 // Post-quantum candidates reserved for future phases.
)

// Enum value maps for EncryptionAlgorithm.
var (
	EncryptionAlgorithm_name = map[int32]string{
		0: "ENCRYPTION_ALGORITHM_UNSPECIFIED",
		1: "ENCRYPTION_ALGORITHM_AES_256_GCM",
	}
	EncryptionAlgorithm_value = map[string]int32{
		"ENCRYPTION_ALGORITHM_UNSPECIFIED": 0,
		"ENCRYPTION_ALGORITHM_AES_256_GCM": 1,
	}
)

func (x EncryptionAlgorithm) Enum() *EncryptionAlgorithm {
	p := new(EncryptionAlgorithm)
	*p = x
	return p
}

func (x EncryptionAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_chunk_proto_enumTypes[0].Descriptor()
}

func (EncryptionAlgorithm) Type() protoreflect.EnumType {
	return &file_kiseki_v1_chunk_proto_enumTypes[0]
}

func (x EncryptionAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionAlgorithm.Descriptor instead.
func (EncryptionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{0}
}

type ChunkIdAlgorithm int32

const (
	ChunkIdAlgorithm_CHUNK_ID_ALGORITHM_UNSPECIFIED ChunkIdAlgorithm = 0
	ChunkIdAlgorithm_CHUNK_ID_ALGORITHM_SHA256      ChunkIdAlgorithm = 1 // cross-tenant dedup default
	ChunkIdAlgorithm_CHUNK_ID_ALGORITHM_HMAC_SHA256 ChunkIdAlgorithm = 2 // tenant-isolated (I-K10, I-X2)
)

// Enum value maps for ChunkIdAlgorithm.
var (
	ChunkIdAlgorithm_name = map[int32]string{
		0: "CHUNK_ID_ALGORITHM_UNSPECIFIED",
		1: "CHUNK_ID_ALGORITHM_SHA256",
		2: "CHUNK_ID_ALGORITHM_HMAC_SHA256",
	}
	ChunkIdAlgorithm_value = map[string]int32{
		"CHUNK_ID_ALGORITHM_UNSPECIFIED": 0,
		"CHUNK_ID_ALGORITHM_SHA256":      1,
		"CHUNK_ID_ALGORITHM_HMAC_SHA256": 2,
	}
)

func (x ChunkIdAlgorithm) Enum() *ChunkIdAlgorithm {
	p := new(ChunkIdAlgorithm)
	*p = x
	return p
}

func (x ChunkIdAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkIdAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_chunk_proto_enumTypes[1].Descriptor()
}

func (ChunkIdAlgorithm) Type() protoreflect.EnumType {
	return &file_kiseki_v1_chunk_proto_enumTypes[1]
}

func (x ChunkIdAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkIdAlgorithm.Descriptor instead.
func (ChunkIdAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{1}
}

type DeviceClass int32

const (
	DeviceClass_DEVICE_CLASS_UNSPECIFIED            DeviceClass = 0
	DeviceClass_DEVICE_CLASS_NVME_U2                DeviceClass = 1
	DeviceClass_DEVICE_CLASS_NVME_QLC               DeviceClass = 2
	DeviceClass_DEVICE_CLASS_NVME_PERSISTENT_MEMORY DeviceClass = 3
	// Tenant/admin-provided classes use DEVICE_CLASS_CUSTOM + `custom_label`.
	DeviceClass_DEVICE_CLASS_CUSTOM DeviceClass = 4
)

// Enum value maps for DeviceClass.
var (
	DeviceClass_name = map[int32]string{
		0: "DEVICE_CLASS_UNSPECIFIED",
		1: "DEVICE_CLASS_NVME_U2",
		2: "DEVICE_CLASS_NVME_QLC",
		3: "DEVICE_CLASS_NVME_PERSISTENT_MEMORY",
		4: "DEVICE_CLASS_CUSTOM",
	}
	DeviceClass_value = map[string]int32{
		"DEVICE_CLASS_UNSPECIFIED":            0,
		"DEVICE_CLASS_NVME_U2":                1,
		"DEVICE_CLASS_NVME_QLC":               2,
		"DEVICE_CLASS_NVME_PERSISTENT_MEMORY": 3,
		"DEVICE_CLASS_CUSTOM":                 4,
	}
)

func (x DeviceClass) Enum() *DeviceClass {
	p := new(DeviceClass)
	*p = x
	return p
}

func (x DeviceClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceClass) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_chunk_proto_enumTypes[2].Descriptor()
}

func (DeviceClass) Type() protoreflect.EnumType {
	return &file_kiseki_v1_chunk_proto_enumTypes[2]
}

func (x DeviceClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceClass.Descriptor instead.
func (DeviceClass) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{2}
}

type RepairTrigger int32

const (
	RepairTrigger_REPAIR_TRIGGER_UNSPECIFIED     RepairTrigger = 0
	RepairTrigger_REPAIR_TRIGGER_DEVICE_FAILURE  RepairTrigger = 1
	RepairTrigger_REPAIR_TRIGGER_INTEGRITY_CHECK RepairTrigger = 2
	RepairTrigger_REPAIR_TRIGGER_ADMIN_TRIGGERED RepairTrigger = 3
)

// Enum value maps for RepairTrigger.
var (
	RepairTrigger_name = map[int32]string{
		0: "REPAIR_TRIGGER_UNSPECIFIED",
		1: "REPAIR_TRIGGER_DEVICE_FAILURE",
		2: "REPAIR_TRIGGER_INTEGRITY_CHECK",
		3: "REPAIR_TRIGGER_ADMIN_TRIGGERED",
	}
	RepairTrigger_value = map[string]int32{
		"REPAIR_TRIGGER_UNSPECIFIED":     0,
		"REPAIR_TRIGGER_DEVICE_FAILURE":  1,
		"REPAIR_TRIGGER_INTEGRITY_CHECK": 2,
		"REPAIR_TRIGGER_ADMIN_TRIGGERED": 3,
	}
)

func (x RepairTrigger) Enum() *RepairTrigger {
	p := new(RepairTrigger)
	*p = x
	return p
}

func (x RepairTrigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepairTrigger) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_chunk_proto_enumTypes[3].Descriptor()
}

func (RepairTrigger) Type() protoreflect.EnumType {
	return &file_kiseki_v1_chunk_proto_enumTypes[3]
}

func (x RepairTrigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepairTrigger.Descriptor instead.
func (RepairTrigger) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{3}
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ciphertext bytes. Never decrypted except inside `kiseki-crypto` with
	// valid system and tenant key material.
	Ciphertext []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// AEAD auth tag, 16 bytes.
	AuthTag []byte `protobuf:"bytes,2,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`
	// Nonce / IV, 12 bytes.
	Nonce       []byte              `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Algorithm   EncryptionAlgorithm `protobuf:"varint,4,opt,name=algorithm,proto3,enum=kiseki.v1.EncryptionAlgorithm" json:"algorithm,omitempty"`
	SystemEpoch *KeyEpoch           `protobuf:"bytes,5,opt,name=system_epoch,json=systemEpoch,proto3" json:"system_epoch,omitempty"`
	// Optional for non-tenant-scoped envelopes (should be present for all
	// tenant data).
	TenantEpoch *KeyEpoch `protobuf:"bytes,6,opt,name=tenant_epoch,json=tenantEpoch,proto3" json:"tenant_epoch,omitempty"`
	// Tenant KEK-wrapped system DEK derivation material (ADR-003).
	TenantWrappedMaterial []byte `protobuf:"bytes,7,opt,name=tenant_wrapped_material,json=tenantWrappedMaterial,proto3" json:"tenant_wrapped_material,omitempty"`
	// Plaintext-derived (for default dedup) or tenant-HMAC-derived (for
	// tenant-isolated dedup). Always in clear so the system can address
	// without tenant keys (I-K4).
	ChunkId       *ChunkId `protobuf:"bytes,8,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *Envelope) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

func (x *Envelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Envelope) GetAlgorithm() EncryptionAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return EncryptionAlgorithm_ENCRYPTION_ALGORITHM_UNSPECIFIED
}

func (x *Envelope) GetSystemEpoch() *KeyEpoch {
	if x != nil {
		return x.SystemEpoch
	}
	return nil
}

func (x *Envelope) GetTenantEpoch() *KeyEpoch {
	if x != nil {
		return x.TenantEpoch
	}
	return nil
}

func (x *Envelope) GetTenantWrappedMaterial() []byte {
	if x != nil {
		return x.TenantWrappedMaterial
	}
	return nil
}

func (x *Envelope) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

// Minimal envelope metadata — stored alongside chunk rows in the index.
// The ciphertext itself lives on disk.
type EnvelopeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     EncryptionAlgorithm    `protobuf:"varint,1,opt,name=algorithm,proto3,enum=kiseki.v1.EncryptionAlgorithm" json:"algorithm,omitempty"`
	SystemEpoch   *KeyEpoch              `protobuf:"bytes,2,opt,name=system_epoch,json=systemEpoch,proto3" json:"system_epoch,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AuthTag       []byte                 `protobuf:"bytes,4,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeMeta) Reset() {
	*x = EnvelopeMeta{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeMeta) ProtoMessage() {}

func (x *EnvelopeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeMeta.ProtoReflect.Descriptor instead.
func (*EnvelopeMeta) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *EnvelopeMeta) GetAlgorithm() EncryptionAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return EncryptionAlgorithm_ENCRYPTION_ALGORITHM_UNSPECIFIED
}

func (x *EnvelopeMeta) GetSystemEpoch() *KeyEpoch {
	if x != nil {
		return x.SystemEpoch
	}
	return nil
}

func (x *EnvelopeMeta) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EnvelopeMeta) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

type AffinityPoolId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffinityPoolId) Reset() {
	*x = AffinityPoolId{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffinityPoolId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffinityPoolId) ProtoMessage() {}

func (x *AffinityPoolId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffinityPoolId.ProtoReflect.Descriptor instead.
func (*AffinityPoolId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *AffinityPoolId) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeviceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceId) Reset() {
	*x = DeviceId{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceId) ProtoMessage() {}

func (x *DeviceId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceId.ProtoReflect.Descriptor instead.
func (*DeviceId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceId) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DurabilityStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Strategy:
	//
	//	*DurabilityStrategy_ErasureCoding
	//	*DurabilityStrategy_Replication
	Strategy      isDurabilityStrategy_Strategy `protobuf_oneof:"strategy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurabilityStrategy) Reset() {
	*x = DurabilityStrategy{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurabilityStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurabilityStrategy) ProtoMessage() {}

func (x *DurabilityStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurabilityStrategy.ProtoReflect.Descriptor instead.
func (*DurabilityStrategy) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{4}
}

func (x *DurabilityStrategy) GetStrategy() isDurabilityStrategy_Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *DurabilityStrategy) GetErasureCoding() *ErasureCoding {
	if x != nil {
		if x, ok := x.Strategy.(*DurabilityStrategy_ErasureCoding); ok {
			return x.ErasureCoding
		}
	}
	return nil
}

func (x *DurabilityStrategy) GetReplication() *Replication {
	if x != nil {
		if x, ok := x.Strategy.(*DurabilityStrategy_Replication); ok {
			return x.Replication
		}
	}
	return nil
}

type isDurabilityStrategy_Strategy interface {
	isDurabilityStrategy_Strategy()
}

type DurabilityStrategy_ErasureCoding struct {
	ErasureCoding *ErasureCoding `protobuf:"bytes,1,opt,name=erasure_coding,json=erasureCoding,proto3,oneof"`
}

type DurabilityStrategy_Replication struct {
	Replication *Replication `protobuf:"bytes,2,opt,name=replication,proto3,oneof"`
}

func (*DurabilityStrategy_ErasureCoding) isDurabilityStrategy_Strategy() {}

func (*DurabilityStrategy_Replication) isDurabilityStrategy_Strategy() {}

type ErasureCoding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataChunks    uint32                 `protobuf:"varint,1,opt,name=data_chunks,json=dataChunks,proto3" json:"data_chunks,omitempty"`
	ParityChunks  uint32                 `protobuf:"varint,2,opt,name=parity_chunks,json=parityChunks,proto3" json:"parity_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErasureCoding) Reset() {
	*x = ErasureCoding{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErasureCoding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErasureCoding) ProtoMessage() {}

func (x *ErasureCoding) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErasureCoding.ProtoReflect.Descriptor instead.
func (*ErasureCoding) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{5}
}

func (x *ErasureCoding) GetDataChunks() uint32 {
	if x != nil {
		return x.DataChunks
	}
	return 0
}

func (x *ErasureCoding) GetParityChunks() uint32 {
	if x != nil {
		return x.ParityChunks
	}
	return 0
}

type Replication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Copies        uint32                 `protobuf:"varint,1,opt,name=copies,proto3" json:"copies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replication) Reset() {
	*x = Replication{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replication) ProtoMessage() {}

func (x *Replication) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replication.ProtoReflect.Descriptor instead.
func (*Replication) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{6}
}

func (x *Replication) GetCopies() uint32 {
	if x != nil {
		return x.Copies
	}
	return 0
}

type AffinityPool struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PoolId      *AffinityPoolId        `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	DeviceClass DeviceClass            `protobuf:"varint,2,opt,name=device_class,json=deviceClass,proto3,enum=kiseki.v1.DeviceClass" json:"device_class,omitempty"`
	// Populated only when device_class == DEVICE_CLASS_CUSTOM.
	CustomLabel   string              `protobuf:"bytes,3,opt,name=custom_label,json=customLabel,proto3" json:"custom_label,omitempty"`
	Durability    *DurabilityStrategy `protobuf:"bytes,4,opt,name=durability,proto3" json:"durability,omitempty"`
	Devices       []*DeviceId         `protobuf:"bytes,5,rep,name=devices,proto3" json:"devices,omitempty"`
	CapacityBytes uint64              `protobuf:"varint,6,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	UsedBytes     uint64              `protobuf:"varint,7,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffinityPool) Reset() {
	*x = AffinityPool{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffinityPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffinityPool) ProtoMessage() {}

func (x *AffinityPool) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffinityPool.ProtoReflect.Descriptor instead.
func (*AffinityPool) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{7}
}

func (x *AffinityPool) GetPoolId() *AffinityPoolId {
	if x != nil {
		return x.PoolId
	}
	return nil
}

func (x *AffinityPool) GetDeviceClass() DeviceClass {
	if x != nil {
		return x.DeviceClass
	}
	return DeviceClass_DEVICE_CLASS_UNSPECIFIED
}

func (x *AffinityPool) GetCustomLabel() string {
	if x != nil {
		return x.CustomLabel
	}
	return ""
}

func (x *AffinityPool) GetDurability() *DurabilityStrategy {
	if x != nil {
		return x.Durability
	}
	return nil
}

func (x *AffinityPool) GetDevices() []*DeviceId {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *AffinityPool) GetCapacityBytes() uint64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *AffinityPool) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

type ChunkPlacement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For EC: which devices hold which fragments.
	Fragments []*DeviceFragment `protobuf:"bytes,1,rep,name=fragments,proto3" json:"fragments,omitempty"`
	// For replication: which devices hold copies.
	Replicas      []*DeviceId `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkPlacement) Reset() {
	*x = ChunkPlacement{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkPlacement) ProtoMessage() {}

func (x *ChunkPlacement) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkPlacement.ProtoReflect.Descriptor instead.
func (*ChunkPlacement) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkPlacement) GetFragments() []*DeviceFragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

func (x *ChunkPlacement) GetReplicas() []*DeviceId {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type DeviceFragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceId              `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	FragmentIndex uint32                 `protobuf:"varint,2,opt,name=fragment_index,json=fragmentIndex,proto3" json:"fragment_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceFragment) Reset() {
	*x = DeviceFragment{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceFragment) ProtoMessage() {}

func (x *DeviceFragment) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceFragment.ProtoReflect.Descriptor instead.
func (*DeviceFragment) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceFragment) GetDevice() *DeviceId {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DeviceFragment) GetFragmentIndex() uint32 {
	if x != nil {
		return x.FragmentIndex
	}
	return 0
}

type RetentionHoldId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionHoldId) Reset() {
	*x = RetentionHoldId{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionHoldId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionHoldId) ProtoMessage() {}

func (x *RetentionHoldId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionHoldId.ProtoReflect.Descriptor instead.
func (*RetentionHoldId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{10}
}

func (x *RetentionHoldId) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RetentionScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*RetentionScope_Tenant
	//	*RetentionScope_Namespace
	//	*RetentionScope_Composition
	Scope         isRetentionScope_Scope `protobuf_oneof:"scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionScope) Reset() {
	*x = RetentionScope{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionScope) ProtoMessage() {}

func (x *RetentionScope) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionScope.ProtoReflect.Descriptor instead.
func (*RetentionScope) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{11}
}

func (x *RetentionScope) GetScope() isRetentionScope_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *RetentionScope) GetTenant() *OrgId {
	if x != nil {
		if x, ok := x.Scope.(*RetentionScope_Tenant); ok {
			return x.Tenant
		}
	}
	return nil
}

func (x *RetentionScope) GetNamespace() *NamespaceId {
	if x != nil {
		if x, ok := x.Scope.(*RetentionScope_Namespace); ok {
			return x.Namespace
		}
	}
	return nil
}

func (x *RetentionScope) GetComposition() *CompositionId {
	if x != nil {
		if x, ok := x.Scope.(*RetentionScope_Composition); ok {
			return x.Composition
		}
	}
	return nil
}

type isRetentionScope_Scope interface {
	isRetentionScope_Scope()
}

type RetentionScope_Tenant struct {
	Tenant *OrgId `protobuf:"bytes,1,opt,name=tenant,proto3,oneof"`
}

type RetentionScope_Namespace struct {
	Namespace *NamespaceId `protobuf:"bytes,2,opt,name=namespace,proto3,oneof"`
}

type RetentionScope_Composition struct {
	Composition *CompositionId `protobuf:"bytes,3,opt,name=composition,proto3,oneof"`
}

func (*RetentionScope_Tenant) isRetentionScope_Scope() {}

func (*RetentionScope_Namespace) isRetentionScope_Scope() {}

func (*RetentionScope_Composition) isRetentionScope_Scope() {}

type RetentionHold struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	HoldId    *RetentionHoldId       `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Scope     *RetentionScope        `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	CreatedAt *WallTime              `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unset = explicit release required.
	ExpiresAt     *WallTime `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Reason        string    `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionHold) Reset() {
	*x = RetentionHold{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionHold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionHold) ProtoMessage() {}

func (x *RetentionHold) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionHold.ProtoReflect.Descriptor instead.
func (*RetentionHold) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{12}
}

func (x *RetentionHold) GetHoldId() *RetentionHoldId {
	if x != nil {
		return x.HoldId
	}
	return nil
}

func (x *RetentionHold) GetScope() *RetentionScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *RetentionHold) GetCreatedAt() *WallTime {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RetentionHold) GetExpiresAt() *WallTime {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RetentionHold) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ChunkMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkId        *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	EnvelopeMeta   *EnvelopeMeta          `protobuf:"bytes,2,opt,name=envelope_meta,json=envelopeMeta,proto3" json:"envelope_meta,omitempty"`
	PoolId         *AffinityPoolId        `protobuf:"bytes,3,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Placement      *ChunkPlacement        `protobuf:"bytes,4,opt,name=placement,proto3" json:"placement,omitempty"`
	Refcount       uint64                 `protobuf:"varint,5,opt,name=refcount,proto3" json:"refcount,omitempty"`
	RetentionHolds []*RetentionHoldId     `protobuf:"bytes,6,rep,name=retention_holds,json=retentionHolds,proto3" json:"retention_holds,omitempty"`
	CreatedAt      *DeltaTimestamp        `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CiphertextSize uint64                 `protobuf:"varint,8,opt,name=ciphertext_size,json=ciphertextSize,proto3" json:"ciphertext_size,omitempty"`
	Compressed     bool                   `protobuf:"varint,9,opt,name=compressed,proto3" json:"compressed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChunkMeta) Reset() {
	*x = ChunkMeta{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMeta) ProtoMessage() {}

func (x *ChunkMeta) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMeta.ProtoReflect.Descriptor instead.
func (*ChunkMeta) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{13}
}

func (x *ChunkMeta) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *ChunkMeta) GetEnvelopeMeta() *EnvelopeMeta {
	if x != nil {
		return x.EnvelopeMeta
	}
	return nil
}

func (x *ChunkMeta) GetPoolId() *AffinityPoolId {
	if x != nil {
		return x.PoolId
	}
	return nil
}

func (x *ChunkMeta) GetPlacement() *ChunkPlacement {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *ChunkMeta) GetRefcount() uint64 {
	if x != nil {
		return x.Refcount
	}
	return 0
}

func (x *ChunkMeta) GetRetentionHolds() []*RetentionHoldId {
	if x != nil {
		return x.RetentionHolds
	}
	return nil
}

func (x *ChunkMeta) GetCreatedAt() *DeltaTimestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChunkMeta) GetCiphertextSize() uint64 {
	if x != nil {
		return x.CiphertextSize
	}
	return 0
}

func (x *ChunkMeta) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

type WriteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Envelope      *Envelope              `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	TargetPool    *AffinityPoolId        `protobuf:"bytes,3,opt,name=target_pool,json=targetPool,proto3" json:"target_pool,omitempty"`
	TenantId      *OrgId                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkRequest) Reset() {
	*x = WriteChunkRequest{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkRequest) ProtoMessage() {}

func (x *WriteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkRequest.ProtoReflect.Descriptor instead.
func (*WriteChunkRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{14}
}

func (x *WriteChunkRequest) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *WriteChunkRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *WriteChunkRequest) GetTargetPool() *AffinityPoolId {
	if x != nil {
		return x.TargetPool
	}
	return nil
}

func (x *WriteChunkRequest) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

// Idempotent: if chunk exists, increments refcount (I-C2).
type WriteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	WasDedup      bool                   `protobuf:"varint,2,opt,name=was_dedup,json=wasDedup,proto3" json:"was_dedup,omitempty"`
	NewRefcount   uint64                 `protobuf:"varint,3,opt,name=new_refcount,json=newRefcount,proto3" json:"new_refcount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkResponse) Reset() {
	*x = WriteChunkResponse{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkResponse) ProtoMessage() {}

func (x *WriteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkResponse.ProtoReflect.Descriptor instead.
func (*WriteChunkResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{15}
}

func (x *WriteChunkResponse) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *WriteChunkResponse) GetWasDedup() bool {
	if x != nil {
		return x.WasDedup
	}
	return false
}

func (x *WriteChunkResponse) GetNewRefcount() uint64 {
	if x != nil {
		return x.NewRefcount
	}
	return 0
}

type ReadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkRequest) Reset() {
	*x = ReadChunkRequest{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkRequest) ProtoMessage() {}

func (x *ReadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkRequest.ProtoReflect.Descriptor instead.
func (*ReadChunkRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{16}
}

func (x *ReadChunkRequest) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

type ReadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Meta          *EnvelopeMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunkResponse) Reset() {
	*x = ReadChunkResponse{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunkResponse) ProtoMessage() {}

func (x *ReadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunkResponse.ProtoReflect.Descriptor instead.
func (*ReadChunkResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{17}
}

func (x *ReadChunkResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *ReadChunkResponse) GetMeta() *EnvelopeMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type IncrementRefcountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	TenantId      *OrgId                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementRefcountRequest) Reset() {
	*x = IncrementRefcountRequest{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementRefcountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementRefcountRequest) ProtoMessage() {}

func (x *IncrementRefcountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementRefcountRequest.ProtoReflect.Descriptor instead.
func (*IncrementRefcountRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{18}
}

func (x *IncrementRefcountRequest) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *IncrementRefcountRequest) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

type DecrementRefcountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	TenantId      *OrgId                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementRefcountRequest) Reset() {
	*x = DecrementRefcountRequest{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementRefcountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementRefcountRequest) ProtoMessage() {}

func (x *DecrementRefcountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementRefcountRequest.ProtoReflect.Descriptor instead.
func (*DecrementRefcountRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{19}
}

func (x *DecrementRefcountRequest) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *DecrementRefcountRequest) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

type RepairChunkRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ChunkId *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Trigger RepairTrigger          `protobuf:"varint,2,opt,name=trigger,proto3,enum=kiseki.v1.RepairTrigger" json:"trigger,omitempty"`
	// Set only when trigger == DEVICE_FAILURE.
	FailedDevice  *DeviceId `protobuf:"bytes,3,opt,name=failed_device,json=failedDevice,proto3" json:"failed_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairChunkRequest) Reset() {
	*x = RepairChunkRequest{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairChunkRequest) ProtoMessage() {}

func (x *RepairChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairChunkRequest.ProtoReflect.Descriptor instead.
func (*RepairChunkRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{20}
}

func (x *RepairChunkRequest) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *RepairChunkRequest) GetTrigger() RepairTrigger {
	if x != nil {
		return x.Trigger
	}
	return RepairTrigger_REPAIR_TRIGGER_UNSPECIFIED
}

func (x *RepairChunkRequest) GetFailedDevice() *DeviceId {
	if x != nil {
		return x.FailedDevice
	}
	return nil
}

type ChunkStoredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	WasDedup      bool                   `protobuf:"varint,2,opt,name=was_dedup,json=wasDedup,proto3" json:"was_dedup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkStoredEvent) Reset() {
	*x = ChunkStoredEvent{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkStoredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkStoredEvent) ProtoMessage() {}

func (x *ChunkStoredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkStoredEvent.ProtoReflect.Descriptor instead.
func (*ChunkStoredEvent) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{21}
}

func (x *ChunkStoredEvent) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *ChunkStoredEvent) GetWasDedup() bool {
	if x != nil {
		return x.WasDedup
	}
	return false
}

type ChunkLostEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkId               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkLostEvent) Reset() {
	*x = ChunkLostEvent{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkLostEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkLostEvent) ProtoMessage() {}

func (x *ChunkLostEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkLostEvent.ProtoReflect.Descriptor instead.
func (*ChunkLostEvent) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{22}
}

func (x *ChunkLostEvent) GetChunkId() *ChunkId {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

type DeviceFailureEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      *DeviceId              `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceFailureEvent) Reset() {
	*x = DeviceFailureEvent{}
	mi := &file_kiseki_v1_chunk_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceFailureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceFailureEvent) ProtoMessage() {}

func (x *DeviceFailureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_chunk_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceFailureEvent.ProtoReflect.Descriptor instead.
func (*DeviceFailureEvent) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_chunk_proto_rawDescGZIP(), []int{23}
}

func (x *DeviceFailureEvent) GetDeviceId() *DeviceId {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

var File_kiseki_v1_chunk_proto protoreflect.FileDescriptor

const file_kiseki_v1_chunk_proto_rawDesc = "" +
	"\n" +
	"\x15kiseki/v1/chunk.proto\x12\tkiseki.v1\x1a\x16kiseki/v1/common.proto\"\xf0\x02\n" +
	"\bEnvelope\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x19\n" +
	"\bauth_tag\x18\x02 \x01(\fR\aauthTag\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12<\n" +
	"\talgorithm\x18\x04 \x01(\x0e2\x1e.kiseki.v1.EncryptionAlgorithmR\talgorithm\x126\n" +
	"\fsystem_epoch\x18\x05 \x01(\v2\x13.kiseki.v1.KeyEpochR\vsystemEpoch\x126\n" +
	"\ftenant_epoch\x18\x06 \x01(\v2\x13.kiseki.v1.KeyEpochR\vtenantEpoch\x126\n" +
	"\x17tenant_wrapped_material\x18\a \x01(\fR\x15tenantWrappedMaterial\x12-\n" +
	"\bchunk_id\x18\b \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\"\xb5\x01\n" +
	"\fEnvelopeMeta\x12<\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x1e.kiseki.v1.EncryptionAlgorithmR\talgorithm\x126\n" +
	"\fsystem_epoch\x18\x02 \x01(\v2\x13.kiseki.v1.KeyEpochR\vsystemEpoch\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x19\n" +
	"\bauth_tag\x18\x04 \x01(\fR\aauthTag\"&\n" +
	"\x0eAffinityPoolId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\" \n" +
	"\bDeviceId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\x9f\x01\n" +
	"\x12DurabilityStrategy\x12A\n" +
	"\x0eerasure_coding\x18\x01 \x01(\v2\x18.kiseki.v1.ErasureCodingH\x00R\rerasureCoding\x12:\n" +
	"\vreplication\x18\x02 \x01(\v2\x16.kiseki.v1.ReplicationH\x00R\vreplicationB\n" +
	"\n" +
	"\bstrategy\"U\n" +
	"\rErasureCoding\x12\x1f\n" +
	"\vdata_chunks\x18\x01 \x01(\rR\n" +
	"dataChunks\x12#\n" +
	"\rparity_chunks\x18\x02 \x01(\rR\fparityChunks\"%\n" +
	"\vReplication\x12\x16\n" +
	"\x06copies\x18\x01 \x01(\rR\x06copies\"\xd4\x02\n" +
	"\fAffinityPool\x122\n" +
	"\apool_id\x18\x01 \x01(\v2\x19.kiseki.v1.AffinityPoolIdR\x06poolId\x129\n" +
	"\fdevice_class\x18\x02 \x01(\x0e2\x16.kiseki.v1.DeviceClassR\vdeviceClass\x12!\n" +
	"\fcustom_label\x18\x03 \x01(\tR\vcustomLabel\x12=\n" +
	"\n" +
	"durability\x18\x04 \x01(\v2\x1d.kiseki.v1.DurabilityStrategyR\n" +
	"durability\x12-\n" +
	"\adevices\x18\x05 \x03(\v2\x13.kiseki.v1.DeviceIdR\adevices\x12%\n" +
	"\x0ecapacity_bytes\x18\x06 \x01(\x04R\rcapacityBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\a \x01(\x04R\tusedBytes\"z\n" +
	"\x0eChunkPlacement\x127\n" +
	"\tfragments\x18\x01 \x03(\v2\x19.kiseki.v1.DeviceFragmentR\tfragments\x12/\n" +
	"\breplicas\x18\x02 \x03(\v2\x13.kiseki.v1.DeviceIdR\breplicas\"d\n" +
	"\x0eDeviceFragment\x12+\n" +
	"\x06device\x18\x01 \x01(\v2\x13.kiseki.v1.DeviceIdR\x06device\x12%\n" +
	"\x0efragment_index\x18\x02 \x01(\rR\rfragmentIndex\"'\n" +
	"\x0fRetentionHoldId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\xbb\x01\n" +
	"\x0eRetentionScope\x12*\n" +
	"\x06tenant\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdH\x00R\x06tenant\x126\n" +
	"\tnamespace\x18\x02 \x01(\v2\x16.kiseki.v1.NamespaceIdH\x00R\tnamespace\x12<\n" +
	"\vcomposition\x18\x03 \x01(\v2\x18.kiseki.v1.CompositionIdH\x00R\vcompositionB\a\n" +
	"\x05scope\"\xf5\x01\n" +
	"\rRetentionHold\x123\n" +
	"\ahold_id\x18\x01 \x01(\v2\x1a.kiseki.v1.RetentionHoldIdR\x06holdId\x12/\n" +
	"\x05scope\x18\x02 \x01(\v2\x19.kiseki.v1.RetentionScopeR\x05scope\x122\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x13.kiseki.v1.WallTimeR\tcreatedAt\x122\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x13.kiseki.v1.WallTimeR\texpiresAt\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xc9\x03\n" +
	"\tChunkMeta\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\x12<\n" +
	"\renvelope_meta\x18\x02 \x01(\v2\x17.kiseki.v1.EnvelopeMetaR\fenvelopeMeta\x122\n" +
	"\apool_id\x18\x03 \x01(\v2\x19.kiseki.v1.AffinityPoolIdR\x06poolId\x127\n" +
	"\tplacement\x18\x04 \x01(\v2\x19.kiseki.v1.ChunkPlacementR\tplacement\x12\x1a\n" +
	"\brefcount\x18\x05 \x01(\x04R\brefcount\x12C\n" +
	"\x0fretention_holds\x18\x06 \x03(\v2\x1a.kiseki.v1.RetentionHoldIdR\x0eretentionHolds\x128\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x19.kiseki.v1.DeltaTimestampR\tcreatedAt\x12'\n" +
	"\x0fciphertext_size\x18\b \x01(\x04R\x0eciphertextSize\x12\x1e\n" +
	"\n" +
	"compressed\x18\t \x01(\bR\n" +
	"compressed\"\xde\x01\n" +
	"\x11WriteChunkRequest\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\x12/\n" +
	"\benvelope\x18\x02 \x01(\v2\x13.kiseki.v1.EnvelopeR\benvelope\x12:\n" +
	"\vtarget_pool\x18\x03 \x01(\v2\x19.kiseki.v1.AffinityPoolIdR\n" +
	"targetPool\x12-\n" +
	"\ttenant_id\x18\x04 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\"\x83\x01\n" +
	"\x12WriteChunkResponse\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\x12\x1b\n" +
	"\twas_dedup\x18\x02 \x01(\bR\bwasDedup\x12!\n" +
	"\fnew_refcount\x18\x03 \x01(\x04R\vnewRefcount\"A\n" +
	"\x10ReadChunkRequest\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\"q\n" +
	"\x11ReadChunkResponse\x12/\n" +
	"\benvelope\x18\x01 \x01(\v2\x13.kiseki.v1.EnvelopeR\benvelope\x12+\n" +
	"\x04meta\x18\x02 \x01(\v2\x17.kiseki.v1.EnvelopeMetaR\x04meta\"x\n" +
	"\x18IncrementRefcountRequest\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\x12-\n" +
	"\ttenant_id\x18\x02 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\"x\n" +
	"\x18DecrementRefcountRequest\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\x12-\n" +
	"\ttenant_id\x18\x02 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\"\xb1\x01\n" +
	"\x12RepairChunkRequest\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\x122\n" +
	"\atrigger\x18\x02 \x01(\x0e2\x18.kiseki.v1.RepairTriggerR\atrigger\x128\n" +
	"\rfailed_device\x18\x03 \x01(\v2\x13.kiseki.v1.DeviceIdR\ffailedDevice\"^\n" +
	"\x10ChunkStoredEvent\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\x12\x1b\n" +
	"\twas_dedup\x18\x02 \x01(\bR\bwasDedup\"?\n" +
	"\x0eChunkLostEvent\x12-\n" +
	"\bchunk_id\x18\x01 \x01(\v2\x12.kiseki.v1.ChunkIdR\achunkId\"F\n" +
	"\x12DeviceFailureEvent\x120\n" +
	"\tdevice_id\x18\x01 \x01(\v2\x13.kiseki.v1.DeviceIdR\bdeviceId*a\n" +
	"\x13EncryptionAlgorithm\x12$\n" +
	" ENCRYPTION_ALGORITHM_UNSPECIFIED\x10\x00\x12$\n" +
	" ENCRYPTION_ALGORITHM_AES_256_GCM\x10\x01*y\n" +
	"\x10ChunkIdAlgorithm\x12\"\n" +
	"\x1eCHUNK_ID_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CHUNK_ID_ALGORITHM_SHA256\x10\x01\x12\"\n" +
	"\x1eCHUNK_ID_ALGORITHM_HMAC_SHA256\x10\x02*\xa2\x01\n" +
	"\vDeviceClass\x12\x1c\n" +
	"\x18DEVICE_CLASS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEVICE_CLASS_NVME_U2\x10\x01\x12\x19\n" +
	"\x15DEVICE_CLASS_NVME_QLC\x10\x02\x12'\n" +
	"#DEVICE_CLASS_NVME_PERSISTENT_MEMORY\x10\x03\x12\x17\n" +
	"\x13DEVICE_CLASS_CUSTOM\x10\x04*\x9a\x01\n" +
	"\rRepairTrigger\x12\x1e\n" +
	"\x1aREPAIR_TRIGGER_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dREPAIR_TRIGGER_DEVICE_FAILURE\x10\x01\x12\"\n" +
	"\x1eREPAIR_TRIGGER_INTEGRITY_CHECK\x10\x02\x12\"\n" +
	"\x1eREPAIR_TRIGGER_ADMIN_TRIGGERED\x10\x03B2Z0github.com/witlox/kiseki/control/proto/kiseki/v1b\x06proto3"

var (
	file_kiseki_v1_chunk_proto_rawDescOnce sync.Once
	file_kiseki_v1_chunk_proto_rawDescData []byte
)

func file_kiseki_v1_chunk_proto_rawDescGZIP() []byte {
	file_kiseki_v1_chunk_proto_rawDescOnce.Do(func() {
		file_kiseki_v1_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kiseki_v1_chunk_proto_rawDesc), len(file_kiseki_v1_chunk_proto_rawDesc)))
	})
	return file_kiseki_v1_chunk_proto_rawDescData
}

var file_kiseki_v1_chunk_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_kiseki_v1_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_kiseki_v1_chunk_proto_goTypes = []any{
	(EncryptionAlgorithm)(0),         // 0: kiseki.v1.EncryptionAlgorithm
	(ChunkIdAlgorithm)(0),            // 1: kiseki.v1.ChunkIdAlgorithm
	(DeviceClass)(0),                 // 2: kiseki.v1.DeviceClass
	(RepairTrigger)(0),               // 3: kiseki.v1.RepairTrigger
	(*Envelope)(nil),                 // 4: kiseki.v1.Envelope
	(*EnvelopeMeta)(nil),             // 5: kiseki.v1.EnvelopeMeta
	(*AffinityPoolId)(nil),           // 6: kiseki.v1.AffinityPoolId
	(*DeviceId)(nil),                 // 7: kiseki.v1.DeviceId
	(*DurabilityStrategy)(nil),       // 8: kiseki.v1.DurabilityStrategy
	(*ErasureCoding)(nil),            // 9: kiseki.v1.ErasureCoding
	(*Replication)(nil),              // 10: kiseki.v1.Replication
	(*AffinityPool)(nil),             // 11: kiseki.v1.AffinityPool
	(*ChunkPlacement)(nil),           // 12: kiseki.v1.ChunkPlacement
	(*DeviceFragment)(nil),           // 13: kiseki.v1.DeviceFragment
	(*RetentionHoldId)(nil),          // 14: kiseki.v1.RetentionHoldId
	(*RetentionScope)(nil),           // 15: kiseki.v1.RetentionScope
	(*RetentionHold)(nil),            // 16: kiseki.v1.RetentionHold
	(*ChunkMeta)(nil),                // 17: kiseki.v1.ChunkMeta
	(*WriteChunkRequest)(nil),        // 18: kiseki.v1.WriteChunkRequest
	(*WriteChunkResponse)(nil),       // 19: kiseki.v1.WriteChunkResponse
	(*ReadChunkRequest)(nil),         // 20: kiseki.v1.ReadChunkRequest
	(*ReadChunkResponse)(nil),        // 21: kiseki.v1.ReadChunkResponse
	(*IncrementRefcountRequest)(nil), // 22: kiseki.v1.IncrementRefcountRequest
	(*DecrementRefcountRequest)(nil), // 23: kiseki.v1.DecrementRefcountRequest
	(*RepairChunkRequest)(nil),       // 24: kiseki.v1.RepairChunkRequest
	(*ChunkStoredEvent)(nil),         // 25: kiseki.v1.ChunkStoredEvent
	(*ChunkLostEvent)(nil),           // 26: kiseki.v1.ChunkLostEvent
	(*DeviceFailureEvent)(nil),       // 27: kiseki.v1.DeviceFailureEvent
	(*KeyEpoch)(nil),                 // 28: kiseki.v1.KeyEpoch
	(*ChunkId)(nil),                  // 29: kiseki.v1.ChunkId
	(*OrgId)(nil),                    // 30: kiseki.v1.OrgId
	(*NamespaceId)(nil),              // 31: kiseki.v1.NamespaceId
	(*CompositionId)(nil),            // 32: kiseki.v1.CompositionId
	(*WallTime)(nil),                 // 33: kiseki.v1.WallTime
	(*DeltaTimestamp)(nil),           // 34: kiseki.v1.DeltaTimestamp
}
var file_kiseki_v1_chunk_proto_depIdxs = []int32{
	0,  // 0: kiseki.v1.Envelope.algorithm:type_name -> kiseki.v1.EncryptionAlgorithm
	28, // 1: kiseki.v1.Envelope.system_epoch:type_name -> kiseki.v1.KeyEpoch
	28, // 2: kiseki.v1.Envelope.tenant_epoch:type_name -> kiseki.v1.KeyEpoch
	29, // 3: kiseki.v1.Envelope.chunk_id:type_name -> kiseki.v1.ChunkId
	0,  // 4: kiseki.v1.EnvelopeMeta.algorithm:type_name -> kiseki.v1.EncryptionAlgorithm
	28, // 5: kiseki.v1.EnvelopeMeta.system_epoch:type_name -> kiseki.v1.KeyEpoch
	9,  // 6: kiseki.v1.DurabilityStrategy.erasure_coding:type_name -> kiseki.v1.ErasureCoding
	10, // 7: kiseki.v1.DurabilityStrategy.replication:type_name -> kiseki.v1.Replication
	6,  // 8: kiseki.v1.AffinityPool.pool_id:type_name -> kiseki.v1.AffinityPoolId
	2,  // 9: kiseki.v1.AffinityPool.device_class:type_name -> kiseki.v1.DeviceClass
	8,  // 10: kiseki.v1.AffinityPool.durability:type_name -> kiseki.v1.DurabilityStrategy
	7,  // 11: kiseki.v1.AffinityPool.devices:type_name -> kiseki.v1.DeviceId
	13, // 12: kiseki.v1.ChunkPlacement.fragments:type_name -> kiseki.v1.DeviceFragment
	7,  // 13: kiseki.v1.ChunkPlacement.replicas:type_name -> kiseki.v1.DeviceId
	7,  // 14: kiseki.v1.DeviceFragment.device:type_name -> kiseki.v1.DeviceId
	30, // 15: kiseki.v1.RetentionScope.tenant:type_name -> kiseki.v1.OrgId
	31, // 16: kiseki.v1.RetentionScope.namespace:type_name -> kiseki.v1.NamespaceId
	32, // 17: kiseki.v1.RetentionScope.composition:type_name -> kiseki.v1.CompositionId
	14, // 18: kiseki.v1.RetentionHold.hold_id:type_name -> kiseki.v1.RetentionHoldId
	15, // 19: kiseki.v1.RetentionHold.scope:type_name -> kiseki.v1.RetentionScope
	33, // 20: kiseki.v1.RetentionHold.created_at:type_name -> kiseki.v1.WallTime
	33, // 21: kiseki.v1.RetentionHold.expires_at:type_name -> kiseki.v1.WallTime
	29, // 22: kiseki.v1.ChunkMeta.chunk_id:type_name -> kiseki.v1.ChunkId
	5,  // 23: kiseki.v1.ChunkMeta.envelope_meta:type_name -> kiseki.v1.EnvelopeMeta
	6,  // 24: kiseki.v1.ChunkMeta.pool_id:type_name -> kiseki.v1.AffinityPoolId
	12, // 25: kiseki.v1.ChunkMeta.placement:type_name -> kiseki.v1.ChunkPlacement
	14, // 26: kiseki.v1.ChunkMeta.retention_holds:type_name -> kiseki.v1.RetentionHoldId
	34, // 27: kiseki.v1.ChunkMeta.created_at:type_name -> kiseki.v1.DeltaTimestamp
	29, // 28: kiseki.v1.WriteChunkRequest.chunk_id:type_name -> kiseki.v1.ChunkId
	4,  // 29: kiseki.v1.WriteChunkRequest.envelope:type_name -> kiseki.v1.Envelope
	6,  // 30: kiseki.v1.WriteChunkRequest.target_pool:type_name -> kiseki.v1.AffinityPoolId
	30, // 31: kiseki.v1.WriteChunkRequest.tenant_id:type_name -> kiseki.v1.OrgId
	29, // 32: kiseki.v1.WriteChunkResponse.chunk_id:type_name -> kiseki.v1.ChunkId
	29, // 33: kiseki.v1.ReadChunkRequest.chunk_id:type_name -> kiseki.v1.ChunkId
	4,  // 34: kiseki.v1.ReadChunkResponse.envelope:type_name -> kiseki.v1.Envelope
	5,  // 35: kiseki.v1.ReadChunkResponse.meta:type_name -> kiseki.v1.EnvelopeMeta
	29, // 36: kiseki.v1.IncrementRefcountRequest.chunk_id:type_name -> kiseki.v1.ChunkId
	30, // 37: kiseki.v1.IncrementRefcountRequest.tenant_id:type_name -> kiseki.v1.OrgId
	29, // 38: kiseki.v1.DecrementRefcountRequest.chunk_id:type_name -> kiseki.v1.ChunkId
	30, // 39: kiseki.v1.DecrementRefcountRequest.tenant_id:type_name -> kiseki.v1.OrgId
	29, // 40: kiseki.v1.RepairChunkRequest.chunk_id:type_name -> kiseki.v1.ChunkId
	3,  // 41: kiseki.v1.RepairChunkRequest.trigger:type_name -> kiseki.v1.RepairTrigger
	7,  // 42: kiseki.v1.RepairChunkRequest.failed_device:type_name -> kiseki.v1.DeviceId
	29, // 43: kiseki.v1.ChunkStoredEvent.chunk_id:type_name -> kiseki.v1.ChunkId
	29, // 44: kiseki.v1.ChunkLostEvent.chunk_id:type_name -> kiseki.v1.ChunkId
	7,  // 45: kiseki.v1.DeviceFailureEvent.device_id:type_name -> kiseki.v1.DeviceId
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_kiseki_v1_chunk_proto_init() }
func file_kiseki_v1_chunk_proto_init() {
	if File_kiseki_v1_chunk_proto != nil {
		return
	}
	file_kiseki_v1_common_proto_init()
	file_kiseki_v1_chunk_proto_msgTypes[4].OneofWrappers = []any{
		(*DurabilityStrategy_ErasureCoding)(nil),
		(*DurabilityStrategy_Replication)(nil),
	}
	file_kiseki_v1_chunk_proto_msgTypes[11].OneofWrappers = []any{
		(*RetentionScope_Tenant)(nil),
		(*RetentionScope_Namespace)(nil),
		(*RetentionScope_Composition)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kiseki_v1_chunk_proto_rawDesc), len(file_kiseki_v1_chunk_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kiseki_v1_chunk_proto_goTypes,
		DependencyIndexes: file_kiseki_v1_chunk_proto_depIdxs,
		EnumInfos:         file_kiseki_v1_chunk_proto_enumTypes,
		MessageInfos:      file_kiseki_v1_chunk_proto_msgTypes,
	}.Build()
	File_kiseki_v1_chunk_proto = out.File
	file_kiseki_v1_chunk_proto_goTypes = nil
	file_kiseki_v1_chunk_proto_depIdxs = nil
}
