// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kiseki/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClockQuality int32

const (
	ClockQuality_CLOCK_QUALITY_UNSPECIFIED ClockQuality = 0
	ClockQuality_CLOCK_QUALITY_NTP         ClockQuality = 1
	ClockQuality_CLOCK_QUALITY_PTP         ClockQuality = 2
	ClockQuality_CLOCK_QUALITY_GPS         ClockQuality = 3
	ClockQuality_CLOCK_QUALITY_UNSYNC      ClockQuality = 4
)

// Enum value maps for ClockQuality.
var (
	ClockQuality_name = map[int32]string{
		0: "CLOCK_QUALITY_UNSPECIFIED",
		1: "CLOCK_QUALITY_NTP",
		2: "CLOCK_QUALITY_PTP",
		3: "CLOCK_QUALITY_GPS",
		4: "CLOCK_QUALITY_UNSYNC",
	}
	ClockQuality_value = map[string]int32{
		"CLOCK_QUALITY_UNSPECIFIED": 0,
		"CLOCK_QUALITY_NTP":         1,
		"CLOCK_QUALITY_PTP":         2,
		"CLOCK_QUALITY_GPS":         3,
		"CLOCK_QUALITY_UNSYNC":      4,
	}
)

func (x ClockQuality) Enum() *ClockQuality {
	p := new(ClockQuality)
	*p = x
	return p
}

func (x ClockQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClockQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_common_proto_enumTypes[0].Descriptor()
}

func (ClockQuality) Type() protoreflect.EnumType {
	return &file_kiseki_v1_common_proto_enumTypes[0]
}

func (x ClockQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClockQuality.Descriptor instead.
func (ClockQuality) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{0}
}

type ComplianceTag int32

const (
	ComplianceTag_COMPLIANCE_TAG_UNSPECIFIED     ComplianceTag = 0
	ComplianceTag_COMPLIANCE_TAG_HIPAA           ComplianceTag = 1
	ComplianceTag_COMPLIANCE_TAG_GDPR            ComplianceTag = 2
	ComplianceTag_COMPLIANCE_TAG_REVFADP         ComplianceTag = 3
	ComplianceTag_COMPLIANCE_TAG_SWISS_RESIDENCY ComplianceTag = 4
)

// Enum value maps for ComplianceTag.
var (
	ComplianceTag_name = map[int32]string{
		0: "COMPLIANCE_TAG_UNSPECIFIED",
		1: "COMPLIANCE_TAG_HIPAA",
		2: "COMPLIANCE_TAG_GDPR",
		3: "COMPLIANCE_TAG_REVFADP",
		4: "COMPLIANCE_TAG_SWISS_RESIDENCY",
	}
	ComplianceTag_value = map[string]int32{
		"COMPLIANCE_TAG_UNSPECIFIED":     0,
		"COMPLIANCE_TAG_HIPAA":           1,
		"COMPLIANCE_TAG_GDPR":            2,
		"COMPLIANCE_TAG_REVFADP":         3,
		"COMPLIANCE_TAG_SWISS_RESIDENCY": 4,
	}
)

func (x ComplianceTag) Enum() *ComplianceTag {
	p := new(ComplianceTag)
	*p = x
	return p
}

func (x ComplianceTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComplianceTag) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_common_proto_enumTypes[1].Descriptor()
}

func (ComplianceTag) Type() protoreflect.EnumType {
	return &file_kiseki_v1_common_proto_enumTypes[1]
}

func (x ComplianceTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComplianceTag.Descriptor instead.
func (ComplianceTag) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{1}
}

type DedupPolicy int32

const (
	DedupPolicy_DEDUP_POLICY_UNSPECIFIED     DedupPolicy = 0
	DedupPolicy_DEDUP_POLICY_CROSS_TENANT    DedupPolicy = 1 // sha256, default
	DedupPolicy_DEDUP_POLICY_TENANT_ISOLATED DedupPolicy = 2 // HMAC
)

// Enum value maps for DedupPolicy.
var (
	DedupPolicy_name = map[int32]string{
		0: "DEDUP_POLICY_UNSPECIFIED",
		1: "DEDUP_POLICY_CROSS_TENANT",
		2: "DEDUP_POLICY_TENANT_ISOLATED",
	}
	DedupPolicy_value = map[string]int32{
		"DEDUP_POLICY_UNSPECIFIED":     0,
		"DEDUP_POLICY_CROSS_TENANT":    1,
		"DEDUP_POLICY_TENANT_ISOLATED": 2,
	}
)

func (x DedupPolicy) Enum() *DedupPolicy {
	p := new(DedupPolicy)
	*p = x
	return p
}

func (x DedupPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DedupPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_common_proto_enumTypes[2].Descriptor()
}

func (DedupPolicy) Type() protoreflect.EnumType {
	return &file_kiseki_v1_common_proto_enumTypes[2]
}

func (x DedupPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DedupPolicy.Descriptor instead.
func (DedupPolicy) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{2}
}

type OrgId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgId) Reset() {
	*x = OrgId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgId) ProtoMessage() {}

func (x *OrgId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgId.ProtoReflect.Descriptor instead.
func (*OrgId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *OrgId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProjectId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectId) Reset() {
	*x = ProjectId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectId) ProtoMessage() {}

func (x *ProjectId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectId.ProtoReflect.Descriptor instead.
func (*ProjectId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WorkloadId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadId) Reset() {
	*x = WorkloadId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadId) ProtoMessage() {}

func (x *WorkloadId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadId.ProtoReflect.Descriptor instead.
func (*WorkloadId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *WorkloadId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ShardId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardId) Reset() {
	*x = ShardId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardId) ProtoMessage() {}

func (x *ShardId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardId.ProtoReflect.Descriptor instead.
func (*ShardId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ShardId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ChunkId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkId) Reset() {
	*x = ChunkId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkId) ProtoMessage() {}

func (x *ChunkId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkId.ProtoReflect.Descriptor instead.
func (*ChunkId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkId) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CompositionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositionId) Reset() {
	*x = CompositionId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositionId) ProtoMessage() {}

func (x *CompositionId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositionId.ProtoReflect.Descriptor instead.
func (*CompositionId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *CompositionId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NamespaceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceId) Reset() {
	*x = NamespaceId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceId) ProtoMessage() {}

func (x *NamespaceId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceId.ProtoReflect.Descriptor instead.
func (*NamespaceId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *NamespaceId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ViewId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewId) Reset() {
	*x = ViewId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewId) ProtoMessage() {}

func (x *ViewId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewId.ProtoReflect.Descriptor instead.
func (*ViewId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *ViewId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NodeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeId) Reset() {
	*x = NodeId{}
	mi := &file_kiseki_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeId) ProtoMessage() {}

func (x *NodeId) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeId.ProtoReflect.Descriptor instead.
func (*NodeId) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *NodeId) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type HybridLogicalClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhysicalMs    uint64                 `protobuf:"varint,1,opt,name=physical_ms,json=physicalMs,proto3" json:"physical_ms,omitempty"`
	Logical       uint32                 `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	NodeId        uint64                 `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridLogicalClock) Reset() {
	*x = HybridLogicalClock{}
	mi := &file_kiseki_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridLogicalClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridLogicalClock) ProtoMessage() {}

func (x *HybridLogicalClock) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridLogicalClock.ProtoReflect.Descriptor instead.
func (*HybridLogicalClock) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *HybridLogicalClock) GetPhysicalMs() uint64 {
	if x != nil {
		return x.PhysicalMs
	}
	return 0
}

func (x *HybridLogicalClock) GetLogical() uint32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *HybridLogicalClock) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type WallTime struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MillisSinceEpoch uint64                 `protobuf:"varint,1,opt,name=millis_since_epoch,json=millisSinceEpoch,proto3" json:"millis_since_epoch,omitempty"`
	Timezone         string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WallTime) Reset() {
	*x = WallTime{}
	mi := &file_kiseki_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WallTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WallTime) ProtoMessage() {}

func (x *WallTime) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WallTime.ProtoReflect.Descriptor instead.
func (*WallTime) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *WallTime) GetMillisSinceEpoch() uint64 {
	if x != nil {
		return x.MillisSinceEpoch
	}
	return 0
}

func (x *WallTime) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type DeltaTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hlc           *HybridLogicalClock    `protobuf:"bytes,1,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Wall          *WallTime              `protobuf:"bytes,2,opt,name=wall,proto3" json:"wall,omitempty"`
	Quality       ClockQuality           `protobuf:"varint,3,opt,name=quality,proto3,enum=kiseki.v1.ClockQuality" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaTimestamp) Reset() {
	*x = DeltaTimestamp{}
	mi := &file_kiseki_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaTimestamp) ProtoMessage() {}

func (x *DeltaTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaTimestamp.ProtoReflect.Descriptor instead.
func (*DeltaTimestamp) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *DeltaTimestamp) GetHlc() *HybridLogicalClock {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *DeltaTimestamp) GetWall() *WallTime {
	if x != nil {
		return x.Wall
	}
	return nil
}

func (x *DeltaTimestamp) GetQuality() ClockQuality {
	if x != nil {
		return x.Quality
	}
	return ClockQuality_CLOCK_QUALITY_UNSPECIFIED
}

type Quota struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CapacityBytes     uint64                 `protobuf:"varint,1,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	Iops              uint64                 `protobuf:"varint,2,opt,name=iops,proto3" json:"iops,omitempty"`
	MetadataOpsPerSec uint64                 `protobuf:"varint,3,opt,name=metadata_ops_per_sec,json=metadataOpsPerSec,proto3" json:"metadata_ops_per_sec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Quota) Reset() {
	*x = Quota{}
	mi := &file_kiseki_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *Quota) GetCapacityBytes() uint64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *Quota) GetIops() uint64 {
	if x != nil {
		return x.Iops
	}
	return 0
}

func (x *Quota) GetMetadataOpsPerSec() uint64 {
	if x != nil {
		return x.MetadataOpsPerSec
	}
	return 0
}

type QuotaUsage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CapacityBytes      uint64                 `protobuf:"varint,1,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	IopsCurrent        uint64                 `protobuf:"varint,2,opt,name=iops_current,json=iopsCurrent,proto3" json:"iops_current,omitempty"`
	MetadataOpsCurrent uint64                 `protobuf:"varint,3,opt,name=metadata_ops_current,json=metadataOpsCurrent,proto3" json:"metadata_ops_current,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuotaUsage) Reset() {
	*x = QuotaUsage{}
	mi := &file_kiseki_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaUsage) ProtoMessage() {}

func (x *QuotaUsage) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaUsage.ProtoReflect.Descriptor instead.
func (*QuotaUsage) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{13}
}

func (x *QuotaUsage) GetCapacityBytes() uint64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *QuotaUsage) GetIopsCurrent() uint64 {
	if x != nil {
		return x.IopsCurrent
	}
	return 0
}

func (x *QuotaUsage) GetMetadataOpsCurrent() uint64 {
	if x != nil {
		return x.MetadataOpsCurrent
	}
	return 0
}

type KeyEpoch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEpoch) Reset() {
	*x = KeyEpoch{}
	mi := &file_kiseki_v1_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEpoch) ProtoMessage() {}

func (x *KeyEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEpoch.ProtoReflect.Descriptor instead.
func (*KeyEpoch) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_common_proto_rawDescGZIP(), []int{14}
}

func (x *KeyEpoch) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_kiseki_v1_common_proto protoreflect.FileDescriptor

const file_kiseki_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16kiseki/v1/common.proto\x12\tkiseki.v1\"\x1d\n" +
	"\x05OrgId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\tProjectId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"WorkloadId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1f\n" +
	"\aShardId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1f\n" +
	"\aChunkId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"%\n" +
	"\rCompositionId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"#\n" +
	"\vNamespaceId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1e\n" +
	"\x06ViewId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1e\n" +
	"\x06NodeId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\"h\n" +
	"\x12HybridLogicalClock\x12\x1f\n" +
	"\vphysical_ms\x18\x01 \x01(\x04R\n" +
	"physicalMs\x12\x18\n" +
	"\alogical\x18\x02 \x01(\rR\alogical\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x04R\x06nodeId\"T\n" +
	"\bWallTime\x12,\n" +
	"\x12millis_since_epoch\x18\x01 \x01(\x04R\x10millisSinceEpoch\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\"\x9d\x01\n" +
	"\x0eDeltaTimestamp\x12/\n" +
	"\x03hlc\x18\x01 \x01(\v2\x1d.kiseki.v1.HybridLogicalClockR\x03hlc\x12'\n" +
	"\x04wall\x18\x02 \x01(\v2\x13.kiseki.v1.WallTimeR\x04wall\x121\n" +
	"\aquality\x18\x03 \x01(\x0e2\x17.kiseki.v1.ClockQualityR\aquality\"s\n" +
	"\x05Quota\x12%\n" +
	"\x0ecapacity_bytes\x18\x01 \x01(\x04R\rcapacityBytes\x12\x12\n" +
	"\x04iops\x18\x02 \x01(\x04R\x04iops\x12/\n" +
	"\x14metadata_ops_per_sec\x18\x03 \x01(\x04R\x11metadataOpsPerSec\"\x88\x01\n" +
	"\n" +
	"QuotaUsage\x12%\n" +
	"\x0ecapacity_bytes\x18\x01 \x01(\x04R\rcapacityBytes\x12!\n" +
	"\fiops_current\x18\x02 \x01(\x04R\viopsCurrent\x120\n" +
	"\x14metadata_ops_current\x18\x03 \x01(\x04R\x12metadataOpsCurrent\" \n" +
	"\bKeyEpoch\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value*\x8c\x01\n" +
	"\fClockQuality\x12\x1d\n" +
	"\x19CLOCK_QUALITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CLOCK_QUALITY_NTP\x10\x01\x12\x15\n" +
	"\x11CLOCK_QUALITY_PTP\x10\x02\x12\x15\n" +
	"\x11CLOCK_QUALITY_GPS\x10\x03\x12\x18\n" +
	"\x14CLOCK_QUALITY_UNSYNC\x10\x04*\xa2\x01\n" +
	"\rComplianceTag\x12\x1e\n" +
	"\x1aCOMPLIANCE_TAG_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COMPLIANCE_TAG_HIPAA\x10\x01\x12\x17\n" +
	"\x13COMPLIANCE_TAG_GDPR\x10\x02\x12\x1a\n" +
	"\x16COMPLIANCE_TAG_REVFADP\x10\x03\x12\"\n" +
	"\x1eCOMPLIANCE_TAG_SWISS_RESIDENCY\x10\x04*l\n" +
	"\vDedupPolicy\x12\x1c\n" +
	"\x18DEDUP_POLICY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DEDUP_POLICY_CROSS_TENANT\x10\x01\x12 \n" +
	"\x1cDEDUP_POLICY_TENANT_ISOLATED\x10\x02B2Z0github.com/witlox/kiseki/control/proto/kiseki/v1b\x06proto3"

var (
	file_kiseki_v1_common_proto_rawDescOnce sync.Once
	file_kiseki_v1_common_proto_rawDescData []byte
)

func file_kiseki_v1_common_proto_rawDescGZIP() []byte {
	file_kiseki_v1_common_proto_rawDescOnce.Do(func() {
		file_kiseki_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kiseki_v1_common_proto_rawDesc), len(file_kiseki_v1_common_proto_rawDesc)))
	})
	return file_kiseki_v1_common_proto_rawDescData
}

var file_kiseki_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_kiseki_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_kiseki_v1_common_proto_goTypes = []any{
	(ClockQuality)(0),          // 0: kiseki.v1.ClockQuality
	(ComplianceTag)(0),         // 1: kiseki.v1.ComplianceTag
	(DedupPolicy)(0),           // 2: kiseki.v1.DedupPolicy
	(*OrgId)(nil),              // 3: kiseki.v1.OrgId
	(*ProjectId)(nil),          // 4: kiseki.v1.ProjectId
	(*WorkloadId)(nil),         // 5: kiseki.v1.WorkloadId
	(*ShardId)(nil),            // 6: kiseki.v1.ShardId
	(*ChunkId)(nil),            // 7: kiseki.v1.ChunkId
	(*CompositionId)(nil),      // 8: kiseki.v1.CompositionId
	(*NamespaceId)(nil),        // 9: kiseki.v1.NamespaceId
	(*ViewId)(nil),             // 10: kiseki.v1.ViewId
	(*NodeId)(nil),             // 11: kiseki.v1.NodeId
	(*HybridLogicalClock)(nil), // 12: kiseki.v1.HybridLogicalClock
	(*WallTime)(nil),           // 13: kiseki.v1.WallTime
	(*DeltaTimestamp)(nil),     // 14: kiseki.v1.DeltaTimestamp
	(*Quota)(nil),              // 15: kiseki.v1.Quota
	(*QuotaUsage)(nil),         // 16: kiseki.v1.QuotaUsage
	(*KeyEpoch)(nil),           // 17: kiseki.v1.KeyEpoch
}
var file_kiseki_v1_common_proto_depIdxs = []int32{
	12, // 0: kiseki.v1.DeltaTimestamp.hlc:type_name -> kiseki.v1.HybridLogicalClock
	13, // 1: kiseki.v1.DeltaTimestamp.wall:type_name -> kiseki.v1.WallTime
	0,  // 2: kiseki.v1.DeltaTimestamp.quality:type_name -> kiseki.v1.ClockQuality
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kiseki_v1_common_proto_init() }
func file_kiseki_v1_common_proto_init() {
	if File_kiseki_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kiseki_v1_common_proto_rawDesc), len(file_kiseki_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kiseki_v1_common_proto_goTypes,
		DependencyIndexes: file_kiseki_v1_common_proto_depIdxs,
		EnumInfos:         file_kiseki_v1_common_proto_enumTypes,
		MessageInfos:      file_kiseki_v1_common_proto_msgTypes,
	}.Build()
	File_kiseki_v1_common_proto = out.File
	file_kiseki_v1_common_proto_goTypes = nil
	file_kiseki_v1_common_proto_depIdxs = nil
}
