// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: kiseki/v1/control.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_CreateOrganization_FullMethodName   = "/kiseki.v1.ControlService/CreateOrganization"
	ControlService_CreateProject_FullMethodName        = "/kiseki.v1.ControlService/CreateProject"
	ControlService_CreateWorkload_FullMethodName       = "/kiseki.v1.ControlService/CreateWorkload"
	ControlService_GetOrganization_FullMethodName      = "/kiseki.v1.ControlService/GetOrganization"
	ControlService_ListOrganizations_FullMethodName    = "/kiseki.v1.ControlService/ListOrganizations"
	ControlService_CreateNamespace_FullMethodName      = "/kiseki.v1.ControlService/CreateNamespace"
	ControlService_RequestAccess_FullMethodName        = "/kiseki.v1.ControlService/RequestAccess"
	ControlService_ApproveAccess_FullMethodName        = "/kiseki.v1.ControlService/ApproveAccess"
	ControlService_DenyAccess_FullMethodName           = "/kiseki.v1.ControlService/DenyAccess"
	ControlService_SetQuota_FullMethodName             = "/kiseki.v1.ControlService/SetQuota"
	ControlService_SetComplianceTags_FullMethodName    = "/kiseki.v1.ControlService/SetComplianceTags"
	ControlService_SetRetentionHold_FullMethodName     = "/kiseki.v1.ControlService/SetRetentionHold"
	ControlService_ReleaseRetentionHold_FullMethodName = "/kiseki.v1.ControlService/ReleaseRetentionHold"
	ControlService_ListFlavors_FullMethodName          = "/kiseki.v1.ControlService/ListFlavors"
	ControlService_MatchFlavor_FullMethodName          = "/kiseki.v1.ControlService/MatchFlavor"
	ControlService_RegisterPeer_FullMethodName         = "/kiseki.v1.ControlService/RegisterPeer"
	ControlService_ListPeers_FullMethodName            = "/kiseki.v1.ControlService/ListPeers"
	ControlService_SetMaintenanceMode_FullMethodName   = "/kiseki.v1.ControlService/SetMaintenanceMode"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	// Tenant lifecycle
	CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	CreateWorkload(ctx context.Context, in *CreateWorkloadRequest, opts ...grpc.CallOption) (*CreateWorkloadResponse, error)
	GetOrganization(ctx context.Context, in *GetOrganizationRequest, opts ...grpc.CallOption) (*Organization, error)
	ListOrganizations(ctx context.Context, in *ListOrganizationsRequest, opts ...grpc.CallOption) (*ListOrganizationsResponse, error)
	// Namespace
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	// IAM / zero-trust boundary
	RequestAccess(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessRequestResponse, error)
	ApproveAccess(ctx context.Context, in *ApproveAccessRequest, opts ...grpc.CallOption) (*ApproveAccessResponse, error)
	DenyAccess(ctx context.Context, in *DenyAccessRequest, opts ...grpc.CallOption) (*DenyAccessResponse, error)
	// Policy
	SetQuota(ctx context.Context, in *SetQuotaRequest, opts ...grpc.CallOption) (*SetQuotaResponse, error)
	SetComplianceTags(ctx context.Context, in *SetComplianceTagsRequest, opts ...grpc.CallOption) (*SetComplianceTagsResponse, error)
	SetRetentionHold(ctx context.Context, in *SetRetentionHoldRequest, opts ...grpc.CallOption) (*SetRetentionHoldResponse, error)
	ReleaseRetentionHold(ctx context.Context, in *ReleaseRetentionHoldRequest, opts ...grpc.CallOption) (*ReleaseRetentionHoldResponse, error)
	// Flavor
	ListFlavors(ctx context.Context, in *ListFlavorsRequest, opts ...grpc.CallOption) (*ListFlavorsResponse, error)
	MatchFlavor(ctx context.Context, in *MatchFlavorRequest, opts ...grpc.CallOption) (*MatchFlavorResponse, error)
	// Federation
	RegisterPeer(ctx context.Context, in *RegisterPeerRequest, opts ...grpc.CallOption) (*RegisterPeerResponse, error)
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	// Maintenance
	SetMaintenanceMode(ctx context.Context, in *SetMaintenanceModeRequest, opts ...grpc.CallOption) (*SetMaintenanceModeResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrganizationResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateWorkload(ctx context.Context, in *CreateWorkloadRequest, opts ...grpc.CallOption) (*CreateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkloadResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetOrganization(ctx context.Context, in *GetOrganizationRequest, opts ...grpc.CallOption) (*Organization, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Organization)
	err := c.cc.Invoke(ctx, ControlService_GetOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListOrganizations(ctx context.Context, in *ListOrganizationsRequest, opts ...grpc.CallOption) (*ListOrganizationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrganizationsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListOrganizations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, ControlService_CreateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RequestAccess(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessRequestResponse)
	err := c.cc.Invoke(ctx, ControlService_RequestAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ApproveAccess(ctx context.Context, in *ApproveAccessRequest, opts ...grpc.CallOption) (*ApproveAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveAccessResponse)
	err := c.cc.Invoke(ctx, ControlService_ApproveAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DenyAccess(ctx context.Context, in *DenyAccessRequest, opts ...grpc.CallOption) (*DenyAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenyAccessResponse)
	err := c.cc.Invoke(ctx, ControlService_DenyAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetQuota(ctx context.Context, in *SetQuotaRequest, opts ...grpc.CallOption) (*SetQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetQuotaResponse)
	err := c.cc.Invoke(ctx, ControlService_SetQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetComplianceTags(ctx context.Context, in *SetComplianceTagsRequest, opts ...grpc.CallOption) (*SetComplianceTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetComplianceTagsResponse)
	err := c.cc.Invoke(ctx, ControlService_SetComplianceTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetRetentionHold(ctx context.Context, in *SetRetentionHoldRequest, opts ...grpc.CallOption) (*SetRetentionHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRetentionHoldResponse)
	err := c.cc.Invoke(ctx, ControlService_SetRetentionHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ReleaseRetentionHold(ctx context.Context, in *ReleaseRetentionHoldRequest, opts ...grpc.CallOption) (*ReleaseRetentionHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseRetentionHoldResponse)
	err := c.cc.Invoke(ctx, ControlService_ReleaseRetentionHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListFlavors(ctx context.Context, in *ListFlavorsRequest, opts ...grpc.CallOption) (*ListFlavorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFlavorsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListFlavors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) MatchFlavor(ctx context.Context, in *MatchFlavorRequest, opts ...grpc.CallOption) (*MatchFlavorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchFlavorResponse)
	err := c.cc.Invoke(ctx, ControlService_MatchFlavor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RegisterPeer(ctx context.Context, in *RegisterPeerRequest, opts ...grpc.CallOption) (*RegisterPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPeerResponse)
	err := c.cc.Invoke(ctx, ControlService_RegisterPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeersResponse)
	err := c.cc.Invoke(ctx, ControlService_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetMaintenanceMode(ctx context.Context, in *SetMaintenanceModeRequest, opts ...grpc.CallOption) (*SetMaintenanceModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMaintenanceModeResponse)
	err := c.cc.Invoke(ctx, ControlService_SetMaintenanceMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	// Tenant lifecycle
	CreateOrganization(context.Context, *CreateOrganizationRequest) (*CreateOrganizationResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	CreateWorkload(context.Context, *CreateWorkloadRequest) (*CreateWorkloadResponse, error)
	GetOrganization(context.Context, *GetOrganizationRequest) (*Organization, error)
	ListOrganizations(context.Context, *ListOrganizationsRequest) (*ListOrganizationsResponse, error)
	// Namespace
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	// IAM / zero-trust boundary
	RequestAccess(context.Context, *AccessRequest) (*AccessRequestResponse, error)
	ApproveAccess(context.Context, *ApproveAccessRequest) (*ApproveAccessResponse, error)
	DenyAccess(context.Context, *DenyAccessRequest) (*DenyAccessResponse, error)
	// Policy
	SetQuota(context.Context, *SetQuotaRequest) (*SetQuotaResponse, error)
	SetComplianceTags(context.Context, *SetComplianceTagsRequest) (*SetComplianceTagsResponse, error)
	SetRetentionHold(context.Context, *SetRetentionHoldRequest) (*SetRetentionHoldResponse, error)
	ReleaseRetentionHold(context.Context, *ReleaseRetentionHoldRequest) (*ReleaseRetentionHoldResponse, error)
	// Flavor
	ListFlavors(context.Context, *ListFlavorsRequest) (*ListFlavorsResponse, error)
	MatchFlavor(context.Context, *MatchFlavorRequest) (*MatchFlavorResponse, error)
	// Federation
	RegisterPeer(context.Context, *RegisterPeerRequest) (*RegisterPeerResponse, error)
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	// Maintenance
	SetMaintenanceMode(context.Context, *SetMaintenanceModeRequest) (*SetMaintenanceModeResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) CreateOrganization(context.Context, *CreateOrganizationRequest) (*CreateOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrganization not implemented")
}
func (UnimplementedControlServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedControlServiceServer) CreateWorkload(context.Context, *CreateWorkloadRequest) (*CreateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkload not implemented")
}
func (UnimplementedControlServiceServer) GetOrganization(context.Context, *GetOrganizationRequest) (*Organization, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrganization not implemented")
}
func (UnimplementedControlServiceServer) ListOrganizations(context.Context, *ListOrganizationsRequest) (*ListOrganizationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrganizations not implemented")
}
func (UnimplementedControlServiceServer) CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (UnimplementedControlServiceServer) RequestAccess(context.Context, *AccessRequest) (*AccessRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedControlServiceServer) ApproveAccess(context.Context, *ApproveAccessRequest) (*ApproveAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveAccess not implemented")
}
func (UnimplementedControlServiceServer) DenyAccess(context.Context, *DenyAccessRequest) (*DenyAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DenyAccess not implemented")
}
func (UnimplementedControlServiceServer) SetQuota(context.Context, *SetQuotaRequest) (*SetQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetQuota not implemented")
}
func (UnimplementedControlServiceServer) SetComplianceTags(context.Context, *SetComplianceTagsRequest) (*SetComplianceTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetComplianceTags not implemented")
}
func (UnimplementedControlServiceServer) SetRetentionHold(context.Context, *SetRetentionHoldRequest) (*SetRetentionHoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRetentionHold not implemented")
}
func (UnimplementedControlServiceServer) ReleaseRetentionHold(context.Context, *ReleaseRetentionHoldRequest) (*ReleaseRetentionHoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseRetentionHold not implemented")
}
func (UnimplementedControlServiceServer) ListFlavors(context.Context, *ListFlavorsRequest) (*ListFlavorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFlavors not implemented")
}
func (UnimplementedControlServiceServer) MatchFlavor(context.Context, *MatchFlavorRequest) (*MatchFlavorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchFlavor not implemented")
}
func (UnimplementedControlServiceServer) RegisterPeer(context.Context, *RegisterPeerRequest) (*RegisterPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPeer not implemented")
}
func (UnimplementedControlServiceServer) ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedControlServiceServer) SetMaintenanceMode(context.Context, *SetMaintenanceModeRequest) (*SetMaintenanceModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMaintenanceMode not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_CreateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateOrganization(ctx, req.(*CreateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateWorkload(ctx, req.(*CreateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetOrganization(ctx, req.(*GetOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrganizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListOrganizations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListOrganizations(ctx, req.(*ListOrganizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CreateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RequestAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RequestAccess(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ApproveAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ApproveAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ApproveAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ApproveAccess(ctx, req.(*ApproveAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DenyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DenyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_DenyAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DenyAccess(ctx, req.(*DenyAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetQuota(ctx, req.(*SetQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetComplianceTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetComplianceTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetComplianceTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetComplianceTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetComplianceTags(ctx, req.(*SetComplianceTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetRetentionHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRetentionHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetRetentionHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetRetentionHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetRetentionHold(ctx, req.(*SetRetentionHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ReleaseRetentionHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRetentionHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ReleaseRetentionHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ReleaseRetentionHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ReleaseRetentionHold(ctx, req.(*ReleaseRetentionHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListFlavors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlavorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListFlavors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListFlavors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListFlavors(ctx, req.(*ListFlavorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_MatchFlavor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchFlavorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).MatchFlavor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_MatchFlavor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).MatchFlavor(ctx, req.(*MatchFlavorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RegisterPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RegisterPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RegisterPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RegisterPeer(ctx, req.(*RegisterPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetMaintenanceMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMaintenanceModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetMaintenanceMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetMaintenanceMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetMaintenanceMode(ctx, req.(*SetMaintenanceModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiseki.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrganization",
			Handler:    _ControlService_CreateOrganization_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _ControlService_CreateProject_Handler,
		},
		{
			MethodName: "CreateWorkload",
			Handler:    _ControlService_CreateWorkload_Handler,
		},
		{
			MethodName: "GetOrganization",
			Handler:    _ControlService_GetOrganization_Handler,
		},
		{
			MethodName: "ListOrganizations",
			Handler:    _ControlService_ListOrganizations_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _ControlService_CreateNamespace_Handler,
		},
		{
			MethodName: "RequestAccess",
			Handler:    _ControlService_RequestAccess_Handler,
		},
		{
			MethodName: "ApproveAccess",
			Handler:    _ControlService_ApproveAccess_Handler,
		},
		{
			MethodName: "DenyAccess",
			Handler:    _ControlService_DenyAccess_Handler,
		},
		{
			MethodName: "SetQuota",
			Handler:    _ControlService_SetQuota_Handler,
		},
		{
			MethodName: "SetComplianceTags",
			Handler:    _ControlService_SetComplianceTags_Handler,
		},
		{
			MethodName: "SetRetentionHold",
			Handler:    _ControlService_SetRetentionHold_Handler,
		},
		{
			MethodName: "ReleaseRetentionHold",
			Handler:    _ControlService_ReleaseRetentionHold_Handler,
		},
		{
			MethodName: "ListFlavors",
			Handler:    _ControlService_ListFlavors_Handler,
		},
		{
			MethodName: "MatchFlavor",
			Handler:    _ControlService_MatchFlavor_Handler,
		},
		{
			MethodName: "RegisterPeer",
			Handler:    _ControlService_RegisterPeer_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _ControlService_ListPeers_Handler,
		},
		{
			MethodName: "SetMaintenanceMode",
			Handler:    _ControlService_SetMaintenanceMode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kiseki/v1/control.proto",
}
