// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kiseki/v1/control.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessLevel int32

const (
	AccessLevel_ACCESS_LEVEL_UNSPECIFIED AccessLevel = 0
	AccessLevel_ACCESS_LEVEL_READ_ONLY   AccessLevel = 1
	AccessLevel_ACCESS_LEVEL_READ_WRITE  AccessLevel = 2
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "ACCESS_LEVEL_UNSPECIFIED",
		1: "ACCESS_LEVEL_READ_ONLY",
		2: "ACCESS_LEVEL_READ_WRITE",
	}
	AccessLevel_value = map[string]int32{
		"ACCESS_LEVEL_UNSPECIFIED": 0,
		"ACCESS_LEVEL_READ_ONLY":   1,
		"ACCESS_LEVEL_READ_WRITE":  2,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_control_proto_enumTypes[0].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_kiseki_v1_control_proto_enumTypes[0]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{0}
}

type Organization struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrgId          *OrgId                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ComplianceTags []ComplianceTag        `protobuf:"varint,3,rep,packed,name=compliance_tags,json=complianceTags,proto3,enum=kiseki.v1.ComplianceTag" json:"compliance_tags,omitempty"`
	Quota          *Quota                 `protobuf:"bytes,4,opt,name=quota,proto3" json:"quota,omitempty"`
	Usage          *QuotaUsage            `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	DedupPolicy    DedupPolicy            `protobuf:"varint,6,opt,name=dedup_policy,json=dedupPolicy,proto3,enum=kiseki.v1.DedupPolicy" json:"dedup_policy,omitempty"`
	CreatedAt      *WallTime              `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_kiseki_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetOrgId() *OrgId {
	if x != nil {
		return x.OrgId
	}
	return nil
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetComplianceTags() []ComplianceTag {
	if x != nil {
		return x.ComplianceTags
	}
	return nil
}

func (x *Organization) GetQuota() *Quota {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *Organization) GetUsage() *QuotaUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Organization) GetDedupPolicy() DedupPolicy {
	if x != nil {
		return x.DedupPolicy
	}
	return DedupPolicy_DEDUP_POLICY_UNSPECIFIED
}

func (x *Organization) GetCreatedAt() *WallTime {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ComplianceTags []ComplianceTag        `protobuf:"varint,2,rep,packed,name=compliance_tags,json=complianceTags,proto3,enum=kiseki.v1.ComplianceTag" json:"compliance_tags,omitempty"`
	Quota          *Quota                 `protobuf:"bytes,3,opt,name=quota,proto3" json:"quota,omitempty"`
	DedupPolicy    DedupPolicy            `protobuf:"varint,4,opt,name=dedup_policy,json=dedupPolicy,proto3,enum=kiseki.v1.DedupPolicy" json:"dedup_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetComplianceTags() []ComplianceTag {
	if x != nil {
		return x.ComplianceTags
	}
	return nil
}

func (x *CreateOrganizationRequest) GetQuota() *Quota {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *CreateOrganizationRequest) GetDedupPolicy() DedupPolicy {
	if x != nil {
		return x.DedupPolicy
	}
	return DedupPolicy_DEDUP_POLICY_UNSPECIFIED
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         *OrgId                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrganizationResponse) GetOrgId() *OrgId {
	if x != nil {
		return x.OrgId
	}
	return nil
}

type CreateProjectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrgId          *OrgId                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ComplianceTags []ComplianceTag        `protobuf:"varint,3,rep,packed,name=compliance_tags,json=complianceTags,proto3,enum=kiseki.v1.ComplianceTag" json:"compliance_tags,omitempty"`
	Quota          *Quota                 `protobuf:"bytes,4,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProjectRequest) GetOrgId() *OrgId {
	if x != nil {
		return x.OrgId
	}
	return nil
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetComplianceTags() []ComplianceTag {
	if x != nil {
		return x.ComplianceTags
	}
	return nil
}

func (x *CreateProjectRequest) GetQuota() *Quota {
	if x != nil {
		return x.Quota
	}
	return nil
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     *ProjectId             `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProjectResponse) GetProjectId() *ProjectId {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

type CreateWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         *OrgId                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId     *ProjectId             `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // optional
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quota         *Quota                 `protobuf:"bytes,4,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkloadRequest) Reset() {
	*x = CreateWorkloadRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkloadRequest) ProtoMessage() {}

func (x *CreateWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkloadRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWorkloadRequest) GetOrgId() *OrgId {
	if x != nil {
		return x.OrgId
	}
	return nil
}

func (x *CreateWorkloadRequest) GetProjectId() *ProjectId {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *CreateWorkloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkloadRequest) GetQuota() *Quota {
	if x != nil {
		return x.Quota
	}
	return nil
}

type CreateWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    *WorkloadId            `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkloadResponse) Reset() {
	*x = CreateWorkloadResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkloadResponse) ProtoMessage() {}

func (x *CreateWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkloadResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWorkloadResponse) GetWorkloadId() *WorkloadId {
	if x != nil {
		return x.WorkloadId
	}
	return nil
}

type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         *OrgId                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrganizationRequest) GetOrgId() *OrgId {
	if x != nil {
		return x.OrgId
	}
	return nil
}

type ListOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{8}
}

type ListOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

type CreateNamespaceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrgId             *OrgId                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VersioningEnabled bool                   `protobuf:"varint,3,opt,name=versioning_enabled,json=versioningEnabled,proto3" json:"versioning_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateNamespaceRequest) Reset() {
	*x = CreateNamespaceRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceRequest) ProtoMessage() {}

func (x *CreateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNamespaceRequest) GetOrgId() *OrgId {
	if x != nil {
		return x.OrgId
	}
	return nil
}

func (x *CreateNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNamespaceRequest) GetVersioningEnabled() bool {
	if x != nil {
		return x.VersioningEnabled
	}
	return false
}

type CreateNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   *NamespaceId           `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	ShardId       *ShardId               `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceResponse) Reset() {
	*x = CreateNamespaceResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceResponse) ProtoMessage() {}

func (x *CreateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNamespaceResponse) GetNamespaceId() *NamespaceId {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *CreateNamespaceResponse) GetShardId() *ShardId {
	if x != nil {
		return x.ShardId
	}
	return nil
}

type AccessRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Requester string                 `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	TenantId  *OrgId                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Types that are valid to be assigned to Scope:
	//
	//	*AccessRequest_Namespace
	//	*AccessRequest_Org
	Scope         isAccessRequest_Scope `protobuf_oneof:"scope"`
	DurationHours uint32                `protobuf:"varint,5,opt,name=duration_hours,json=durationHours,proto3" json:"duration_hours,omitempty"`
	AccessLevel   AccessLevel           `protobuf:"varint,6,opt,name=access_level,json=accessLevel,proto3,enum=kiseki.v1.AccessLevel" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *AccessRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *AccessRequest) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *AccessRequest) GetScope() isAccessRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AccessRequest) GetNamespace() *NamespaceId {
	if x != nil {
		if x, ok := x.Scope.(*AccessRequest_Namespace); ok {
			return x.Namespace
		}
	}
	return nil
}

func (x *AccessRequest) GetOrg() *OrgId {
	if x != nil {
		if x, ok := x.Scope.(*AccessRequest_Org); ok {
			return x.Org
		}
	}
	return nil
}

func (x *AccessRequest) GetDurationHours() uint32 {
	if x != nil {
		return x.DurationHours
	}
	return 0
}

func (x *AccessRequest) GetAccessLevel() AccessLevel {
	if x != nil {
		return x.AccessLevel
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

type isAccessRequest_Scope interface {
	isAccessRequest_Scope()
}

type AccessRequest_Namespace struct {
	Namespace *NamespaceId `protobuf:"bytes,3,opt,name=namespace,proto3,oneof"`
}

type AccessRequest_Org struct {
	Org *OrgId `protobuf:"bytes,4,opt,name=org,proto3,oneof"`
}

func (*AccessRequest_Namespace) isAccessRequest_Scope() {}

func (*AccessRequest_Org) isAccessRequest_Scope() {}

type AccessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequestResponse) Reset() {
	*x = AccessRequestResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequestResponse) ProtoMessage() {}

func (x *AccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequestResponse.ProtoReflect.Descriptor instead.
func (*AccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *AccessRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApproveAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAccessRequest) Reset() {
	*x = ApproveAccessRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAccessRequest) ProtoMessage() {}

func (x *ApproveAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAccessRequest.ProtoReflect.Descriptor instead.
func (*ApproveAccessRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *ApproveAccessRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApproveAccessRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type ApproveAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAccessResponse) Reset() {
	*x = ApproveAccessResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAccessResponse) ProtoMessage() {}

func (x *ApproveAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAccessResponse.ProtoReflect.Descriptor instead.
func (*ApproveAccessResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{15}
}

type DenyAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeniedBy      string                 `protobuf:"bytes,2,opt,name=denied_by,json=deniedBy,proto3" json:"denied_by,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyAccessRequest) Reset() {
	*x = DenyAccessRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyAccessRequest) ProtoMessage() {}

func (x *DenyAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyAccessRequest.ProtoReflect.Descriptor instead.
func (*DenyAccessRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *DenyAccessRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DenyAccessRequest) GetDeniedBy() string {
	if x != nil {
		return x.DeniedBy
	}
	return ""
}

func (x *DenyAccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DenyAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyAccessResponse) Reset() {
	*x = DenyAccessResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyAccessResponse) ProtoMessage() {}

func (x *DenyAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyAccessResponse.ProtoReflect.Descriptor instead.
func (*DenyAccessResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{17}
}

type SetQuotaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*SetQuotaRequest_OrgId
	//	*SetQuotaRequest_WorkloadId
	Scope         isSetQuotaRequest_Scope `protobuf_oneof:"scope"`
	Quota         *Quota                  `protobuf:"bytes,3,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQuotaRequest) Reset() {
	*x = SetQuotaRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQuotaRequest) ProtoMessage() {}

func (x *SetQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQuotaRequest.ProtoReflect.Descriptor instead.
func (*SetQuotaRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *SetQuotaRequest) GetScope() isSetQuotaRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SetQuotaRequest) GetOrgId() *OrgId {
	if x != nil {
		if x, ok := x.Scope.(*SetQuotaRequest_OrgId); ok {
			return x.OrgId
		}
	}
	return nil
}

func (x *SetQuotaRequest) GetWorkloadId() *WorkloadId {
	if x != nil {
		if x, ok := x.Scope.(*SetQuotaRequest_WorkloadId); ok {
			return x.WorkloadId
		}
	}
	return nil
}

func (x *SetQuotaRequest) GetQuota() *Quota {
	if x != nil {
		return x.Quota
	}
	return nil
}

type isSetQuotaRequest_Scope interface {
	isSetQuotaRequest_Scope()
}

type SetQuotaRequest_OrgId struct {
	OrgId *OrgId `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3,oneof"`
}

type SetQuotaRequest_WorkloadId struct {
	WorkloadId *WorkloadId `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3,oneof"`
}

func (*SetQuotaRequest_OrgId) isSetQuotaRequest_Scope() {}

func (*SetQuotaRequest_WorkloadId) isSetQuotaRequest_Scope() {}

type SetQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQuotaResponse) Reset() {
	*x = SetQuotaResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQuotaResponse) ProtoMessage() {}

func (x *SetQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQuotaResponse.ProtoReflect.Descriptor instead.
func (*SetQuotaResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{19}
}

type SetComplianceTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*SetComplianceTagsRequest_OrgId
	//	*SetComplianceTagsRequest_NamespaceId
	Scope         isSetComplianceTagsRequest_Scope `protobuf_oneof:"scope"`
	Tags          []ComplianceTag                  `protobuf:"varint,3,rep,packed,name=tags,proto3,enum=kiseki.v1.ComplianceTag" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetComplianceTagsRequest) Reset() {
	*x = SetComplianceTagsRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetComplianceTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetComplianceTagsRequest) ProtoMessage() {}

func (x *SetComplianceTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetComplianceTagsRequest.ProtoReflect.Descriptor instead.
func (*SetComplianceTagsRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *SetComplianceTagsRequest) GetScope() isSetComplianceTagsRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SetComplianceTagsRequest) GetOrgId() *OrgId {
	if x != nil {
		if x, ok := x.Scope.(*SetComplianceTagsRequest_OrgId); ok {
			return x.OrgId
		}
	}
	return nil
}

func (x *SetComplianceTagsRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		if x, ok := x.Scope.(*SetComplianceTagsRequest_NamespaceId); ok {
			return x.NamespaceId
		}
	}
	return nil
}

func (x *SetComplianceTagsRequest) GetTags() []ComplianceTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type isSetComplianceTagsRequest_Scope interface {
	isSetComplianceTagsRequest_Scope()
}

type SetComplianceTagsRequest_OrgId struct {
	OrgId *OrgId `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3,oneof"`
}

type SetComplianceTagsRequest_NamespaceId struct {
	NamespaceId *NamespaceId `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3,oneof"`
}

func (*SetComplianceTagsRequest_OrgId) isSetComplianceTagsRequest_Scope() {}

func (*SetComplianceTagsRequest_NamespaceId) isSetComplianceTagsRequest_Scope() {}

type SetComplianceTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetComplianceTagsResponse) Reset() {
	*x = SetComplianceTagsResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetComplianceTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetComplianceTagsResponse) ProtoMessage() {}

func (x *SetComplianceTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetComplianceTagsResponse.ProtoReflect.Descriptor instead.
func (*SetComplianceTagsResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{21}
}

type SetRetentionHoldRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	HoldId string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	// Types that are valid to be assigned to Scope:
	//
	//	*SetRetentionHoldRequest_OrgId
	//	*SetRetentionHoldRequest_NamespaceId
	Scope         isSetRetentionHoldRequest_Scope `protobuf_oneof:"scope"`
	TtlSeconds    uint64                          `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Reason        string                          `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRetentionHoldRequest) Reset() {
	*x = SetRetentionHoldRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRetentionHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRetentionHoldRequest) ProtoMessage() {}

func (x *SetRetentionHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRetentionHoldRequest.ProtoReflect.Descriptor instead.
func (*SetRetentionHoldRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *SetRetentionHoldRequest) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *SetRetentionHoldRequest) GetScope() isSetRetentionHoldRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SetRetentionHoldRequest) GetOrgId() *OrgId {
	if x != nil {
		if x, ok := x.Scope.(*SetRetentionHoldRequest_OrgId); ok {
			return x.OrgId
		}
	}
	return nil
}

func (x *SetRetentionHoldRequest) GetNamespaceId() *NamespaceId {
	if x != nil {
		if x, ok := x.Scope.(*SetRetentionHoldRequest_NamespaceId); ok {
			return x.NamespaceId
		}
	}
	return nil
}

func (x *SetRetentionHoldRequest) GetTtlSeconds() uint64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *SetRetentionHoldRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type isSetRetentionHoldRequest_Scope interface {
	isSetRetentionHoldRequest_Scope()
}

type SetRetentionHoldRequest_OrgId struct {
	OrgId *OrgId `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3,oneof"`
}

type SetRetentionHoldRequest_NamespaceId struct {
	NamespaceId *NamespaceId `protobuf:"bytes,3,opt,name=namespace_id,json=namespaceId,proto3,oneof"`
}

func (*SetRetentionHoldRequest_OrgId) isSetRetentionHoldRequest_Scope() {}

func (*SetRetentionHoldRequest_NamespaceId) isSetRetentionHoldRequest_Scope() {}

type SetRetentionHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRetentionHoldResponse) Reset() {
	*x = SetRetentionHoldResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRetentionHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRetentionHoldResponse) ProtoMessage() {}

func (x *SetRetentionHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRetentionHoldResponse.ProtoReflect.Descriptor instead.
func (*SetRetentionHoldResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{23}
}

type ReleaseRetentionHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRetentionHoldRequest) Reset() {
	*x = ReleaseRetentionHoldRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRetentionHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRetentionHoldRequest) ProtoMessage() {}

func (x *ReleaseRetentionHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRetentionHoldRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRetentionHoldRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *ReleaseRetentionHoldRequest) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

type ReleaseRetentionHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRetentionHoldResponse) Reset() {
	*x = ReleaseRetentionHoldResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRetentionHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRetentionHoldResponse) ProtoMessage() {}

func (x *ReleaseRetentionHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRetentionHoldResponse.ProtoReflect.Descriptor instead.
func (*ReleaseRetentionHoldResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{25}
}

type ListFlavorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlavorsRequest) Reset() {
	*x = ListFlavorsRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlavorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlavorsRequest) ProtoMessage() {}

func (x *ListFlavorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlavorsRequest.ProtoReflect.Descriptor instead.
func (*ListFlavorsRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{26}
}

type ListFlavorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flavors       []*Flavor              `protobuf:"bytes,1,rep,name=flavors,proto3" json:"flavors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlavorsResponse) Reset() {
	*x = ListFlavorsResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlavorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlavorsResponse) ProtoMessage() {}

func (x *ListFlavorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlavorsResponse.ProtoReflect.Descriptor instead.
func (*ListFlavorsResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{27}
}

func (x *ListFlavorsResponse) GetFlavors() []*Flavor {
	if x != nil {
		return x.Flavors
	}
	return nil
}

type Flavor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlavorId      string                 `protobuf:"bytes,1,opt,name=flavor_id,json=flavorId,proto3" json:"flavor_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocols     []string               `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Transports    []string               `protobuf:"bytes,4,rep,name=transports,proto3" json:"transports,omitempty"`
	Topology      string                 `protobuf:"bytes,5,opt,name=topology,proto3" json:"topology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flavor) Reset() {
	*x = Flavor{}
	mi := &file_kiseki_v1_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flavor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flavor) ProtoMessage() {}

func (x *Flavor) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flavor.ProtoReflect.Descriptor instead.
func (*Flavor) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{28}
}

func (x *Flavor) GetFlavorId() string {
	if x != nil {
		return x.FlavorId
	}
	return ""
}

func (x *Flavor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flavor) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Flavor) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *Flavor) GetTopology() string {
	if x != nil {
		return x.Topology
	}
	return ""
}

type MatchFlavorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requested     *Flavor                `protobuf:"bytes,1,opt,name=requested,proto3" json:"requested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFlavorRequest) Reset() {
	*x = MatchFlavorRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFlavorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFlavorRequest) ProtoMessage() {}

func (x *MatchFlavorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFlavorRequest.ProtoReflect.Descriptor instead.
func (*MatchFlavorRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{29}
}

func (x *MatchFlavorRequest) GetRequested() *Flavor {
	if x != nil {
		return x.Requested
	}
	return nil
}

type MatchFlavorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provided      *Flavor                `protobuf:"bytes,1,opt,name=provided,proto3" json:"provided,omitempty"`
	Mismatches    []string               `protobuf:"bytes,2,rep,name=mismatches,proto3" json:"mismatches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFlavorResponse) Reset() {
	*x = MatchFlavorResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFlavorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFlavorResponse) ProtoMessage() {}

func (x *MatchFlavorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFlavorResponse.ProtoReflect.Descriptor instead.
func (*MatchFlavorResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{30}
}

func (x *MatchFlavorResponse) GetProvided() *Flavor {
	if x != nil {
		return x.Provided
	}
	return nil
}

func (x *MatchFlavorResponse) GetMismatches() []string {
	if x != nil {
		return x.Mismatches
	}
	return nil
}

type RegisterPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerRequest) Reset() {
	*x = RegisterPeerRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerRequest) ProtoMessage() {}

func (x *RegisterPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerRequest.ProtoReflect.Descriptor instead.
func (*RegisterPeerRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{31}
}

func (x *RegisterPeerRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *RegisterPeerRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type RegisterPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerResponse) Reset() {
	*x = RegisterPeerResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerResponse) ProtoMessage() {}

func (x *RegisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerResponse.ProtoReflect.Descriptor instead.
func (*RegisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{32}
}

func (x *RegisterPeerResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{33}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*FederationPeer      `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{34}
}

func (x *ListPeersResponse) GetPeers() []*FederationPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type FederationPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SiteName      string                 `protobuf:"bytes,2,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederationPeer) Reset() {
	*x = FederationPeer{}
	mi := &file_kiseki_v1_control_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationPeer) ProtoMessage() {}

func (x *FederationPeer) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationPeer.ProtoReflect.Descriptor instead.
func (*FederationPeer) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{35}
}

func (x *FederationPeer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *FederationPeer) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *FederationPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *FederationPeer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetMaintenanceModeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scope:
	//
	//	*SetMaintenanceModeRequest_ShardId
	//	*SetMaintenanceModeRequest_ClusterWide
	Scope         isSetMaintenanceModeRequest_Scope `protobuf_oneof:"scope"`
	Enabled       bool                              `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMaintenanceModeRequest) Reset() {
	*x = SetMaintenanceModeRequest{}
	mi := &file_kiseki_v1_control_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMaintenanceModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMaintenanceModeRequest) ProtoMessage() {}

func (x *SetMaintenanceModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMaintenanceModeRequest.ProtoReflect.Descriptor instead.
func (*SetMaintenanceModeRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{36}
}

func (x *SetMaintenanceModeRequest) GetScope() isSetMaintenanceModeRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SetMaintenanceModeRequest) GetShardId() *ShardId {
	if x != nil {
		if x, ok := x.Scope.(*SetMaintenanceModeRequest_ShardId); ok {
			return x.ShardId
		}
	}
	return nil
}

func (x *SetMaintenanceModeRequest) GetClusterWide() bool {
	if x != nil {
		if x, ok := x.Scope.(*SetMaintenanceModeRequest_ClusterWide); ok {
			return x.ClusterWide
		}
	}
	return false
}

func (x *SetMaintenanceModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type isSetMaintenanceModeRequest_Scope interface {
	isSetMaintenanceModeRequest_Scope()
}

type SetMaintenanceModeRequest_ShardId struct {
	ShardId *ShardId `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3,oneof"`
}

type SetMaintenanceModeRequest_ClusterWide struct {
	ClusterWide bool `protobuf:"varint,2,opt,name=cluster_wide,json=clusterWide,proto3,oneof"`
}

func (*SetMaintenanceModeRequest_ShardId) isSetMaintenanceModeRequest_Scope() {}

func (*SetMaintenanceModeRequest_ClusterWide) isSetMaintenanceModeRequest_Scope() {}

type SetMaintenanceModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMaintenanceModeResponse) Reset() {
	*x = SetMaintenanceModeResponse{}
	mi := &file_kiseki_v1_control_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMaintenanceModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMaintenanceModeResponse) ProtoMessage() {}

func (x *SetMaintenanceModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_control_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMaintenanceModeResponse.ProtoReflect.Descriptor instead.
func (*SetMaintenanceModeResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_control_proto_rawDescGZIP(), []int{37}
}

var File_kiseki_v1_control_proto protoreflect.FileDescriptor

const file_kiseki_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17kiseki/v1/control.proto\x12\tkiseki.v1\x1a\x16kiseki/v1/common.proto\"\xd2\x02\n" +
	"\fOrganization\x12'\n" +
	"\x06org_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12A\n" +
	"\x0fcompliance_tags\x18\x03 \x03(\x0e2\x18.kiseki.v1.ComplianceTagR\x0ecomplianceTags\x12&\n" +
	"\x05quota\x18\x04 \x01(\v2\x10.kiseki.v1.QuotaR\x05quota\x12+\n" +
	"\x05usage\x18\x05 \x01(\v2\x15.kiseki.v1.QuotaUsageR\x05usage\x129\n" +
	"\fdedup_policy\x18\x06 \x01(\x0e2\x16.kiseki.v1.DedupPolicyR\vdedupPolicy\x122\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x13.kiseki.v1.WallTimeR\tcreatedAt\"\xd5\x01\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\x0fcompliance_tags\x18\x02 \x03(\x0e2\x18.kiseki.v1.ComplianceTagR\x0ecomplianceTags\x12&\n" +
	"\x05quota\x18\x03 \x01(\v2\x10.kiseki.v1.QuotaR\x05quota\x129\n" +
	"\fdedup_policy\x18\x04 \x01(\x0e2\x16.kiseki.v1.DedupPolicyR\vdedupPolicy\"E\n" +
	"\x1aCreateOrganizationResponse\x12'\n" +
	"\x06org_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\x05orgId\"\xbe\x01\n" +
	"\x14CreateProjectRequest\x12'\n" +
	"\x06org_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12A\n" +
	"\x0fcompliance_tags\x18\x03 \x03(\x0e2\x18.kiseki.v1.ComplianceTagR\x0ecomplianceTags\x12&\n" +
	"\x05quota\x18\x04 \x01(\v2\x10.kiseki.v1.QuotaR\x05quota\"L\n" +
	"\x15CreateProjectResponse\x123\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x14.kiseki.v1.ProjectIdR\tprojectId\"\xb1\x01\n" +
	"\x15CreateWorkloadRequest\x12'\n" +
	"\x06org_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\x05orgId\x123\n" +
	"\n" +
	"project_id\x18\x02 \x01(\v2\x14.kiseki.v1.ProjectIdR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12&\n" +
	"\x05quota\x18\x04 \x01(\v2\x10.kiseki.v1.QuotaR\x05quota\"P\n" +
	"\x16CreateWorkloadResponse\x126\n" +
	"\vworkload_id\x18\x01 \x01(\v2\x15.kiseki.v1.WorkloadIdR\n" +
	"workloadId\"A\n" +
	"\x16GetOrganizationRequest\x12'\n" +
	"\x06org_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\x05orgId\"\x1a\n" +
	"\x18ListOrganizationsRequest\"Z\n" +
	"\x19ListOrganizationsResponse\x12=\n" +
	"\rorganizations\x18\x01 \x03(\v2\x17.kiseki.v1.OrganizationR\rorganizations\"\x84\x01\n" +
	"\x16CreateNamespaceRequest\x12'\n" +
	"\x06org_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12versioning_enabled\x18\x03 \x01(\bR\x11versioningEnabled\"\x83\x01\n" +
	"\x17CreateNamespaceResponse\x129\n" +
	"\fnamespace_id\x18\x01 \x01(\v2\x16.kiseki.v1.NamespaceIdR\vnamespaceId\x12-\n" +
	"\bshard_id\x18\x02 \x01(\v2\x12.kiseki.v1.ShardIdR\ashardId\"\xa5\x02\n" +
	"\rAccessRequest\x12\x1c\n" +
	"\trequester\x18\x01 \x01(\tR\trequester\x12-\n" +
	"\ttenant_id\x18\x02 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\x126\n" +
	"\tnamespace\x18\x03 \x01(\v2\x16.kiseki.v1.NamespaceIdH\x00R\tnamespace\x12$\n" +
	"\x03org\x18\x04 \x01(\v2\x10.kiseki.v1.OrgIdH\x00R\x03org\x12%\n" +
	"\x0eduration_hours\x18\x05 \x01(\rR\rdurationHours\x129\n" +
	"\faccess_level\x18\x06 \x01(\x0e2\x16.kiseki.v1.AccessLevelR\vaccessLevelB\a\n" +
	"\x05scope\"6\n" +
	"\x15AccessRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"V\n" +
	"\x14ApproveAccessRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vapproved_by\x18\x02 \x01(\tR\n" +
	"approvedBy\"\x17\n" +
	"\x15ApproveAccessResponse\"g\n" +
	"\x11DenyAccessRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tdenied_by\x18\x02 \x01(\tR\bdeniedBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x14\n" +
	"\x12DenyAccessResponse\"\xa7\x01\n" +
	"\x0fSetQuotaRequest\x12)\n" +
	"\x06org_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdH\x00R\x05orgId\x128\n" +
	"\vworkload_id\x18\x02 \x01(\v2\x15.kiseki.v1.WorkloadIdH\x00R\n" +
	"workloadId\x12&\n" +
	"\x05quota\x18\x03 \x01(\v2\x10.kiseki.v1.QuotaR\x05quotaB\a\n" +
	"\x05scope\"\x12\n" +
	"\x10SetQuotaResponse\"\xb9\x01\n" +
	"\x18SetComplianceTagsRequest\x12)\n" +
	"\x06org_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdH\x00R\x05orgId\x12;\n" +
	"\fnamespace_id\x18\x02 \x01(\v2\x16.kiseki.v1.NamespaceIdH\x00R\vnamespaceId\x12,\n" +
	"\x04tags\x18\x03 \x03(\x0e2\x18.kiseki.v1.ComplianceTagR\x04tagsB\a\n" +
	"\x05scope\"\x1b\n" +
	"\x19SetComplianceTagsResponse\"\xdc\x01\n" +
	"\x17SetRetentionHoldRequest\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12)\n" +
	"\x06org_id\x18\x02 \x01(\v2\x10.kiseki.v1.OrgIdH\x00R\x05orgId\x12;\n" +
	"\fnamespace_id\x18\x03 \x01(\v2\x16.kiseki.v1.NamespaceIdH\x00R\vnamespaceId\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x04R\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reasonB\a\n" +
	"\x05scope\"\x1a\n" +
	"\x18SetRetentionHoldResponse\"6\n" +
	"\x1bReleaseRetentionHoldRequest\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\"\x1e\n" +
	"\x1cReleaseRetentionHoldResponse\"\x14\n" +
	"\x12ListFlavorsRequest\"B\n" +
	"\x13ListFlavorsResponse\x12+\n" +
	"\aflavors\x18\x01 \x03(\v2\x11.kiseki.v1.FlavorR\aflavors\"\x93\x01\n" +
	"\x06Flavor\x12\x1b\n" +
	"\tflavor_id\x18\x01 \x01(\tR\bflavorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tprotocols\x18\x03 \x03(\tR\tprotocols\x12\x1e\n" +
	"\n" +
	"transports\x18\x04 \x03(\tR\n" +
	"transports\x12\x1a\n" +
	"\btopology\x18\x05 \x01(\tR\btopology\"E\n" +
	"\x12MatchFlavorRequest\x12/\n" +
	"\trequested\x18\x01 \x01(\v2\x11.kiseki.v1.FlavorR\trequested\"d\n" +
	"\x13MatchFlavorResponse\x12-\n" +
	"\bprovided\x18\x01 \x01(\v2\x11.kiseki.v1.FlavorR\bprovided\x12\x1e\n" +
	"\n" +
	"mismatches\x18\x02 \x03(\tR\n" +
	"mismatches\"N\n" +
	"\x13RegisterPeerRequest\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"/\n" +
	"\x14RegisterPeerResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\x12\n" +
	"\x10ListPeersRequest\"D\n" +
	"\x11ListPeersResponse\x12/\n" +
	"\x05peers\x18\x01 \x03(\v2\x19.kiseki.v1.FederationPeerR\x05peers\"z\n" +
	"\x0eFederationPeer\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tsite_name\x18\x02 \x01(\tR\bsiteName\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x94\x01\n" +
	"\x19SetMaintenanceModeRequest\x12/\n" +
	"\bshard_id\x18\x01 \x01(\v2\x12.kiseki.v1.ShardIdH\x00R\ashardId\x12#\n" +
	"\fcluster_wide\x18\x02 \x01(\bH\x00R\vclusterWide\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabledB\a\n" +
	"\x05scope\"\x1c\n" +
	"\x1aSetMaintenanceModeResponse*d\n" +
	"\vAccessLevel\x12\x1c\n" +
	"\x18ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACCESS_LEVEL_READ_ONLY\x10\x01\x12\x1b\n" +
	"\x17ACCESS_LEVEL_READ_WRITE\x10\x022\x96\f\n" +
	"\x0eControlService\x12a\n" +
	"\x12CreateOrganization\x12$.kiseki.v1.CreateOrganizationRequest\x1a%.kiseki.v1.CreateOrganizationResponse\x12R\n" +
	"\rCreateProject\x12\x1f.kiseki.v1.CreateProjectRequest\x1a .kiseki.v1.CreateProjectResponse\x12U\n" +
	"\x0eCreateWorkload\x12 .kiseki.v1.CreateWorkloadRequest\x1a!.kiseki.v1.CreateWorkloadResponse\x12M\n" +
	"\x0fGetOrganization\x12!.kiseki.v1.GetOrganizationRequest\x1a\x17.kiseki.v1.Organization\x12^\n" +
	"\x11ListOrganizations\x12#.kiseki.v1.ListOrganizationsRequest\x1a$.kiseki.v1.ListOrganizationsResponse\x12X\n" +
	"\x0fCreateNamespace\x12!.kiseki.v1.CreateNamespaceRequest\x1a\".kiseki.v1.CreateNamespaceResponse\x12K\n" +
	"\rRequestAccess\x12\x18.kiseki.v1.AccessRequest\x1a .kiseki.v1.AccessRequestResponse\x12R\n" +
	"\rApproveAccess\x12\x1f.kiseki.v1.ApproveAccessRequest\x1a .kiseki.v1.ApproveAccessResponse\x12I\n" +
	"\n" +
	"DenyAccess\x12\x1c.kiseki.v1.DenyAccessRequest\x1a\x1d.kiseki.v1.DenyAccessResponse\x12C\n" +
	"\bSetQuota\x12\x1a.kiseki.v1.SetQuotaRequest\x1a\x1b.kiseki.v1.SetQuotaResponse\x12^\n" +
	"\x11SetComplianceTags\x12#.kiseki.v1.SetComplianceTagsRequest\x1a$.kiseki.v1.SetComplianceTagsResponse\x12[\n" +
	"\x10SetRetentionHold\x12\".kiseki.v1.SetRetentionHoldRequest\x1a#.kiseki.v1.SetRetentionHoldResponse\x12g\n" +
	"\x14ReleaseRetentionHold\x12&.kiseki.v1.ReleaseRetentionHoldRequest\x1a'.kiseki.v1.ReleaseRetentionHoldResponse\x12L\n" +
	"\vListFlavors\x12\x1d.kiseki.v1.ListFlavorsRequest\x1a\x1e.kiseki.v1.ListFlavorsResponse\x12L\n" +
	"\vMatchFlavor\x12\x1d.kiseki.v1.MatchFlavorRequest\x1a\x1e.kiseki.v1.MatchFlavorResponse\x12O\n" +
	"\fRegisterPeer\x12\x1e.kiseki.v1.RegisterPeerRequest\x1a\x1f.kiseki.v1.RegisterPeerResponse\x12F\n" +
	"\tListPeers\x12\x1b.kiseki.v1.ListPeersRequest\x1a\x1c.kiseki.v1.ListPeersResponse\x12a\n" +
	"\x12SetMaintenanceMode\x12$.kiseki.v1.SetMaintenanceModeRequest\x1a%.kiseki.v1.SetMaintenanceModeResponseB2Z0github.com/witlox/kiseki/control/proto/kiseki/v1b\x06proto3"

var (
	file_kiseki_v1_control_proto_rawDescOnce sync.Once
	file_kiseki_v1_control_proto_rawDescData []byte
)

func file_kiseki_v1_control_proto_rawDescGZIP() []byte {
	file_kiseki_v1_control_proto_rawDescOnce.Do(func() {
		file_kiseki_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kiseki_v1_control_proto_rawDesc), len(file_kiseki_v1_control_proto_rawDesc)))
	})
	return file_kiseki_v1_control_proto_rawDescData
}

var file_kiseki_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kiseki_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_kiseki_v1_control_proto_goTypes = []any{
	(AccessLevel)(0),                     // 0: kiseki.v1.AccessLevel
	(*Organization)(nil),                 // 1: kiseki.v1.Organization
	(*CreateOrganizationRequest)(nil),    // 2: kiseki.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil),   // 3: kiseki.v1.CreateOrganizationResponse
	(*CreateProjectRequest)(nil),         // 4: kiseki.v1.CreateProjectRequest
	(*CreateProjectResponse)(nil),        // 5: kiseki.v1.CreateProjectResponse
	(*CreateWorkloadRequest)(nil),        // 6: kiseki.v1.CreateWorkloadRequest
	(*CreateWorkloadResponse)(nil),       // 7: kiseki.v1.CreateWorkloadResponse
	(*GetOrganizationRequest)(nil),       // 8: kiseki.v1.GetOrganizationRequest
	(*ListOrganizationsRequest)(nil),     // 9: kiseki.v1.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil),    // 10: kiseki.v1.ListOrganizationsResponse
	(*CreateNamespaceRequest)(nil),       // 11: kiseki.v1.CreateNamespaceRequest
	(*CreateNamespaceResponse)(nil),      // 12: kiseki.v1.CreateNamespaceResponse
	(*AccessRequest)(nil),                // 13: kiseki.v1.AccessRequest
	(*AccessRequestResponse)(nil),        // 14: kiseki.v1.AccessRequestResponse
	(*ApproveAccessRequest)(nil),         // 15: kiseki.v1.ApproveAccessRequest
	(*ApproveAccessResponse)(nil),        // 16: kiseki.v1.ApproveAccessResponse
	(*DenyAccessRequest)(nil),            // 17: kiseki.v1.DenyAccessRequest
	(*DenyAccessResponse)(nil),           // 18: kiseki.v1.DenyAccessResponse
	(*SetQuotaRequest)(nil),              // 19: kiseki.v1.SetQuotaRequest
	(*SetQuotaResponse)(nil),             // 20: kiseki.v1.SetQuotaResponse
	(*SetComplianceTagsRequest)(nil),     // 21: kiseki.v1.SetComplianceTagsRequest
	(*SetComplianceTagsResponse)(nil),    // 22: kiseki.v1.SetComplianceTagsResponse
	(*SetRetentionHoldRequest)(nil),      // 23: kiseki.v1.SetRetentionHoldRequest
	(*SetRetentionHoldResponse)(nil),     // 24: kiseki.v1.SetRetentionHoldResponse
	(*ReleaseRetentionHoldRequest)(nil),  // 25: kiseki.v1.ReleaseRetentionHoldRequest
	(*ReleaseRetentionHoldResponse)(nil), // 26: kiseki.v1.ReleaseRetentionHoldResponse
	(*ListFlavorsRequest)(nil),           // 27: kiseki.v1.ListFlavorsRequest
	(*ListFlavorsResponse)(nil),          // 28: kiseki.v1.ListFlavorsResponse
	(*Flavor)(nil),                       // 29: kiseki.v1.Flavor
	(*MatchFlavorRequest)(nil),           // 30: kiseki.v1.MatchFlavorRequest
	(*MatchFlavorResponse)(nil),          // 31: kiseki.v1.MatchFlavorResponse
	(*RegisterPeerRequest)(nil),          // 32: kiseki.v1.RegisterPeerRequest
	(*RegisterPeerResponse)(nil),         // 33: kiseki.v1.RegisterPeerResponse
	(*ListPeersRequest)(nil),             // 34: kiseki.v1.ListPeersRequest
	(*ListPeersResponse)(nil),            // 35: kiseki.v1.ListPeersResponse
	(*FederationPeer)(nil),               // 36: kiseki.v1.FederationPeer
	(*SetMaintenanceModeRequest)(nil),    // 37: kiseki.v1.SetMaintenanceModeRequest
	(*SetMaintenanceModeResponse)(nil),   // 38: kiseki.v1.SetMaintenanceModeResponse
	(*OrgId)(nil),                        // 39: kiseki.v1.OrgId
	(ComplianceTag)(0),                   // 40: kiseki.v1.ComplianceTag
	(*Quota)(nil),                        // 41: kiseki.v1.Quota
	(*QuotaUsage)(nil),                   // 42: kiseki.v1.QuotaUsage
	(DedupPolicy)(0),                     // 43: kiseki.v1.DedupPolicy
	(*WallTime)(nil),                     // 44: kiseki.v1.WallTime
	(*ProjectId)(nil),                    // 45: kiseki.v1.ProjectId
	(*WorkloadId)(nil),                   // 46: kiseki.v1.WorkloadId
	(*NamespaceId)(nil),                  // 47: kiseki.v1.NamespaceId
	(*ShardId)(nil),                      // 48: kiseki.v1.ShardId
}
var file_kiseki_v1_control_proto_depIdxs = []int32{
	39, // 0: kiseki.v1.Organization.org_id:type_name -> kiseki.v1.OrgId
	40, // 1: kiseki.v1.Organization.compliance_tags:type_name -> kiseki.v1.ComplianceTag
	41, // 2: kiseki.v1.Organization.quota:type_name -> kiseki.v1.Quota
	42, // 3: kiseki.v1.Organization.usage:type_name -> kiseki.v1.QuotaUsage
	43, // 4: kiseki.v1.Organization.dedup_policy:type_name -> kiseki.v1.DedupPolicy
	44, // 5: kiseki.v1.Organization.created_at:type_name -> kiseki.v1.WallTime
	40, // 6: kiseki.v1.CreateOrganizationRequest.compliance_tags:type_name -> kiseki.v1.ComplianceTag
	41, // 7: kiseki.v1.CreateOrganizationRequest.quota:type_name -> kiseki.v1.Quota
	43, // 8: kiseki.v1.CreateOrganizationRequest.dedup_policy:type_name -> kiseki.v1.DedupPolicy
	39, // 9: kiseki.v1.CreateOrganizationResponse.org_id:type_name -> kiseki.v1.OrgId
	39, // 10: kiseki.v1.CreateProjectRequest.org_id:type_name -> kiseki.v1.OrgId
	40, // 11: kiseki.v1.CreateProjectRequest.compliance_tags:type_name -> kiseki.v1.ComplianceTag
	41, // 12: kiseki.v1.CreateProjectRequest.quota:type_name -> kiseki.v1.Quota
	45, // 13: kiseki.v1.CreateProjectResponse.project_id:type_name -> kiseki.v1.ProjectId
	39, // 14: kiseki.v1.CreateWorkloadRequest.org_id:type_name -> kiseki.v1.OrgId
	45, // 15: kiseki.v1.CreateWorkloadRequest.project_id:type_name -> kiseki.v1.ProjectId
	41, // 16: kiseki.v1.CreateWorkloadRequest.quota:type_name -> kiseki.v1.Quota
	46, // 17: kiseki.v1.CreateWorkloadResponse.workload_id:type_name -> kiseki.v1.WorkloadId
	39, // 18: kiseki.v1.GetOrganizationRequest.org_id:type_name -> kiseki.v1.OrgId
	1,  // 19: kiseki.v1.ListOrganizationsResponse.organizations:type_name -> kiseki.v1.Organization
	39, // 20: kiseki.v1.CreateNamespaceRequest.org_id:type_name -> kiseki.v1.OrgId
	47, // 21: kiseki.v1.CreateNamespaceResponse.namespace_id:type_name -> kiseki.v1.NamespaceId
	48, // 22: kiseki.v1.CreateNamespaceResponse.shard_id:type_name -> kiseki.v1.ShardId
	39, // 23: kiseki.v1.AccessRequest.tenant_id:type_name -> kiseki.v1.OrgId
	47, // 24: kiseki.v1.AccessRequest.namespace:type_name -> kiseki.v1.NamespaceId
	39, // 25: kiseki.v1.AccessRequest.org:type_name -> kiseki.v1.OrgId
	0,  // 26: kiseki.v1.AccessRequest.access_level:type_name -> kiseki.v1.AccessLevel
	39, // 27: kiseki.v1.SetQuotaRequest.org_id:type_name -> kiseki.v1.OrgId
	46, // 28: kiseki.v1.SetQuotaRequest.workload_id:type_name -> kiseki.v1.WorkloadId
	41, // 29: kiseki.v1.SetQuotaRequest.quota:type_name -> kiseki.v1.Quota
	39, // 30: kiseki.v1.SetComplianceTagsRequest.org_id:type_name -> kiseki.v1.OrgId
	47, // 31: kiseki.v1.SetComplianceTagsRequest.namespace_id:type_name -> kiseki.v1.NamespaceId
	40, // 32: kiseki.v1.SetComplianceTagsRequest.tags:type_name -> kiseki.v1.ComplianceTag
	39, // 33: kiseki.v1.SetRetentionHoldRequest.org_id:type_name -> kiseki.v1.OrgId
	47, // 34: kiseki.v1.SetRetentionHoldRequest.namespace_id:type_name -> kiseki.v1.NamespaceId
	29, // 35: kiseki.v1.ListFlavorsResponse.flavors:type_name -> kiseki.v1.Flavor
	29, // 36: kiseki.v1.MatchFlavorRequest.requested:type_name -> kiseki.v1.Flavor
	29, // 37: kiseki.v1.MatchFlavorResponse.provided:type_name -> kiseki.v1.Flavor
	36, // 38: kiseki.v1.ListPeersResponse.peers:type_name -> kiseki.v1.FederationPeer
	48, // 39: kiseki.v1.SetMaintenanceModeRequest.shard_id:type_name -> kiseki.v1.ShardId
	2,  // 40: kiseki.v1.ControlService.CreateOrganization:input_type -> kiseki.v1.CreateOrganizationRequest
	4,  // 41: kiseki.v1.ControlService.CreateProject:input_type -> kiseki.v1.CreateProjectRequest
	6,  // 42: kiseki.v1.ControlService.CreateWorkload:input_type -> kiseki.v1.CreateWorkloadRequest
	8,  // 43: kiseki.v1.ControlService.GetOrganization:input_type -> kiseki.v1.GetOrganizationRequest
	9,  // 44: kiseki.v1.ControlService.ListOrganizations:input_type -> kiseki.v1.ListOrganizationsRequest
	11, // 45: kiseki.v1.ControlService.CreateNamespace:input_type -> kiseki.v1.CreateNamespaceRequest
	13, // 46: kiseki.v1.ControlService.RequestAccess:input_type -> kiseki.v1.AccessRequest
	15, // 47: kiseki.v1.ControlService.ApproveAccess:input_type -> kiseki.v1.ApproveAccessRequest
	17, // 48: kiseki.v1.ControlService.DenyAccess:input_type -> kiseki.v1.DenyAccessRequest
	19, // 49: kiseki.v1.ControlService.SetQuota:input_type -> kiseki.v1.SetQuotaRequest
	21, // 50: kiseki.v1.ControlService.SetComplianceTags:input_type -> kiseki.v1.SetComplianceTagsRequest
	23, // 51: kiseki.v1.ControlService.SetRetentionHold:input_type -> kiseki.v1.SetRetentionHoldRequest
	25, // 52: kiseki.v1.ControlService.ReleaseRetentionHold:input_type -> kiseki.v1.ReleaseRetentionHoldRequest
	27, // 53: kiseki.v1.ControlService.ListFlavors:input_type -> kiseki.v1.ListFlavorsRequest
	30, // 54: kiseki.v1.ControlService.MatchFlavor:input_type -> kiseki.v1.MatchFlavorRequest
	32, // 55: kiseki.v1.ControlService.RegisterPeer:input_type -> kiseki.v1.RegisterPeerRequest
	34, // 56: kiseki.v1.ControlService.ListPeers:input_type -> kiseki.v1.ListPeersRequest
	37, // 57: kiseki.v1.ControlService.SetMaintenanceMode:input_type -> kiseki.v1.SetMaintenanceModeRequest
	3,  // 58: kiseki.v1.ControlService.CreateOrganization:output_type -> kiseki.v1.CreateOrganizationResponse
	5,  // 59: kiseki.v1.ControlService.CreateProject:output_type -> kiseki.v1.CreateProjectResponse
	7,  // 60: kiseki.v1.ControlService.CreateWorkload:output_type -> kiseki.v1.CreateWorkloadResponse
	1,  // 61: kiseki.v1.ControlService.GetOrganization:output_type -> kiseki.v1.Organization
	10, // 62: kiseki.v1.ControlService.ListOrganizations:output_type -> kiseki.v1.ListOrganizationsResponse
	12, // 63: kiseki.v1.ControlService.CreateNamespace:output_type -> kiseki.v1.CreateNamespaceResponse
	14, // 64: kiseki.v1.ControlService.RequestAccess:output_type -> kiseki.v1.AccessRequestResponse
	16, // 65: kiseki.v1.ControlService.ApproveAccess:output_type -> kiseki.v1.ApproveAccessResponse
	18, // 66: kiseki.v1.ControlService.DenyAccess:output_type -> kiseki.v1.DenyAccessResponse
	20, // 67: kiseki.v1.ControlService.SetQuota:output_type -> kiseki.v1.SetQuotaResponse
	22, // 68: kiseki.v1.ControlService.SetComplianceTags:output_type -> kiseki.v1.SetComplianceTagsResponse
	24, // 69: kiseki.v1.ControlService.SetRetentionHold:output_type -> kiseki.v1.SetRetentionHoldResponse
	26, // 70: kiseki.v1.ControlService.ReleaseRetentionHold:output_type -> kiseki.v1.ReleaseRetentionHoldResponse
	28, // 71: kiseki.v1.ControlService.ListFlavors:output_type -> kiseki.v1.ListFlavorsResponse
	31, // 72: kiseki.v1.ControlService.MatchFlavor:output_type -> kiseki.v1.MatchFlavorResponse
	33, // 73: kiseki.v1.ControlService.RegisterPeer:output_type -> kiseki.v1.RegisterPeerResponse
	35, // 74: kiseki.v1.ControlService.ListPeers:output_type -> kiseki.v1.ListPeersResponse
	38, // 75: kiseki.v1.ControlService.SetMaintenanceMode:output_type -> kiseki.v1.SetMaintenanceModeResponse
	58, // [58:76] is the sub-list for method output_type
	40, // [40:58] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_kiseki_v1_control_proto_init() }
func file_kiseki_v1_control_proto_init() {
	if File_kiseki_v1_control_proto != nil {
		return
	}
	file_kiseki_v1_common_proto_init()
	file_kiseki_v1_control_proto_msgTypes[12].OneofWrappers = []any{
		(*AccessRequest_Namespace)(nil),
		(*AccessRequest_Org)(nil),
	}
	file_kiseki_v1_control_proto_msgTypes[18].OneofWrappers = []any{
		(*SetQuotaRequest_OrgId)(nil),
		(*SetQuotaRequest_WorkloadId)(nil),
	}
	file_kiseki_v1_control_proto_msgTypes[20].OneofWrappers = []any{
		(*SetComplianceTagsRequest_OrgId)(nil),
		(*SetComplianceTagsRequest_NamespaceId)(nil),
	}
	file_kiseki_v1_control_proto_msgTypes[22].OneofWrappers = []any{
		(*SetRetentionHoldRequest_OrgId)(nil),
		(*SetRetentionHoldRequest_NamespaceId)(nil),
	}
	file_kiseki_v1_control_proto_msgTypes[36].OneofWrappers = []any{
		(*SetMaintenanceModeRequest_ShardId)(nil),
		(*SetMaintenanceModeRequest_ClusterWide)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kiseki_v1_control_proto_rawDesc), len(file_kiseki_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kiseki_v1_control_proto_goTypes,
		DependencyIndexes: file_kiseki_v1_control_proto_depIdxs,
		EnumInfos:         file_kiseki_v1_control_proto_enumTypes,
		MessageInfos:      file_kiseki_v1_control_proto_msgTypes,
	}.Build()
	File_kiseki_v1_control_proto = out.File
	file_kiseki_v1_control_proto_goTypes = nil
	file_kiseki_v1_control_proto_depIdxs = nil
}
