// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kiseki/v1/key.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchMasterKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         *KeyEpoch              `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"` // Server authenticates via mTLS; key manager verifies it's a legitimate server.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMasterKeyRequest) Reset() {
	*x = FetchMasterKeyRequest{}
	mi := &file_kiseki_v1_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMasterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMasterKeyRequest) ProtoMessage() {}

func (x *FetchMasterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMasterKeyRequest.ProtoReflect.Descriptor instead.
func (*FetchMasterKeyRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{0}
}

func (x *FetchMasterKeyRequest) GetEpoch() *KeyEpoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

type FetchMasterKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyMaterial   []byte                 `protobuf:"bytes,1,opt,name=key_material,json=keyMaterial,proto3" json:"key_material,omitempty"` // 32 bytes, encrypted in transit (TLS)
	Epoch         *KeyEpoch              `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	CreatedAt     *DeltaTimestamp        `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMasterKeyResponse) Reset() {
	*x = FetchMasterKeyResponse{}
	mi := &file_kiseki_v1_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMasterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMasterKeyResponse) ProtoMessage() {}

func (x *FetchMasterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMasterKeyResponse.ProtoReflect.Descriptor instead.
func (*FetchMasterKeyResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{1}
}

func (x *FetchMasterKeyResponse) GetKeyMaterial() []byte {
	if x != nil {
		return x.KeyMaterial
	}
	return nil
}

func (x *FetchMasterKeyResponse) GetEpoch() *KeyEpoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *FetchMasterKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *FetchMasterKeyResponse) GetCreatedAt() *DeltaTimestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CurrentEpochRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentEpochRequest) Reset() {
	*x = CurrentEpochRequest{}
	mi := &file_kiseki_v1_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentEpochRequest) ProtoMessage() {}

func (x *CurrentEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentEpochRequest.ProtoReflect.Descriptor instead.
func (*CurrentEpochRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{2}
}

type CurrentEpochResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       *KeyEpoch              `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Retained      []*KeyEpoch            `protobuf:"bytes,2,rep,name=retained,proto3" json:"retained,omitempty"` // old epochs still valid during rotation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentEpochResponse) Reset() {
	*x = CurrentEpochResponse{}
	mi := &file_kiseki_v1_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentEpochResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentEpochResponse) ProtoMessage() {}

func (x *CurrentEpochResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentEpochResponse.ProtoReflect.Descriptor instead.
func (*CurrentEpochResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentEpochResponse) GetCurrent() *KeyEpoch {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *CurrentEpochResponse) GetRetained() []*KeyEpoch {
	if x != nil {
		return x.Retained
	}
	return nil
}

type RotateSystemKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggeredBy   string                 `protobuf:"bytes,1,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSystemKeyRequest) Reset() {
	*x = RotateSystemKeyRequest{}
	mi := &file_kiseki_v1_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSystemKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSystemKeyRequest) ProtoMessage() {}

func (x *RotateSystemKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSystemKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateSystemKeyRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{4}
}

func (x *RotateSystemKeyRequest) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

type RotateSystemKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewEpoch      *KeyEpoch              `protobuf:"bytes,1,opt,name=new_epoch,json=newEpoch,proto3" json:"new_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSystemKeyResponse) Reset() {
	*x = RotateSystemKeyResponse{}
	mi := &file_kiseki_v1_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSystemKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSystemKeyResponse) ProtoMessage() {}

func (x *RotateSystemKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSystemKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateSystemKeyResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{5}
}

func (x *RotateSystemKeyResponse) GetNewEpoch() *KeyEpoch {
	if x != nil {
		return x.NewEpoch
	}
	return nil
}

type KeyManagerHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyManagerHealthRequest) Reset() {
	*x = KeyManagerHealthRequest{}
	mi := &file_kiseki_v1_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyManagerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyManagerHealthRequest) ProtoMessage() {}

func (x *KeyManagerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyManagerHealthRequest.ProtoReflect.Descriptor instead.
func (*KeyManagerHealthRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{6}
}

type KeyManagerHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentEpoch  *KeyEpoch              `protobuf:"bytes,1,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	RaftMembers   []uint64               `protobuf:"varint,2,rep,packed,name=raft_members,json=raftMembers,proto3" json:"raft_members,omitempty"`
	Leader        uint64                 `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyManagerHealthResponse) Reset() {
	*x = KeyManagerHealthResponse{}
	mi := &file_kiseki_v1_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyManagerHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyManagerHealthResponse) ProtoMessage() {}

func (x *KeyManagerHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyManagerHealthResponse.ProtoReflect.Descriptor instead.
func (*KeyManagerHealthResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{7}
}

func (x *KeyManagerHealthResponse) GetCurrentEpoch() *KeyEpoch {
	if x != nil {
		return x.CurrentEpoch
	}
	return nil
}

func (x *KeyManagerHealthResponse) GetRaftMembers() []uint64 {
	if x != nil {
		return x.RaftMembers
	}
	return nil
}

func (x *KeyManagerHealthResponse) GetLeader() uint64 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *KeyManagerHealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type RotateTenantKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *OrgId                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TriggeredBy   string                 `protobuf:"bytes,2,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateTenantKeyRequest) Reset() {
	*x = RotateTenantKeyRequest{}
	mi := &file_kiseki_v1_key_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateTenantKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateTenantKeyRequest) ProtoMessage() {}

func (x *RotateTenantKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateTenantKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateTenantKeyRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{8}
}

func (x *RotateTenantKeyRequest) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *RotateTenantKeyRequest) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

type RotateTenantKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewEpoch      *KeyEpoch              `protobuf:"bytes,1,opt,name=new_epoch,json=newEpoch,proto3" json:"new_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateTenantKeyResponse) Reset() {
	*x = RotateTenantKeyResponse{}
	mi := &file_kiseki_v1_key_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateTenantKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateTenantKeyResponse) ProtoMessage() {}

func (x *RotateTenantKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateTenantKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateTenantKeyResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{9}
}

func (x *RotateTenantKeyResponse) GetNewEpoch() *KeyEpoch {
	if x != nil {
		return x.NewEpoch
	}
	return nil
}

type CryptoShredRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TenantId              *OrgId                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ForceWithoutHoldCheck bool                   `protobuf:"varint,2,opt,name=force_without_hold_check,json=forceWithoutHoldCheck,proto3" json:"force_without_hold_check,omitempty"` // ADR-010
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CryptoShredRequest) Reset() {
	*x = CryptoShredRequest{}
	mi := &file_kiseki_v1_key_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoShredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoShredRequest) ProtoMessage() {}

func (x *CryptoShredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoShredRequest.ProtoReflect.Descriptor instead.
func (*CryptoShredRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{10}
}

func (x *CryptoShredRequest) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *CryptoShredRequest) GetForceWithoutHoldCheck() bool {
	if x != nil {
		return x.ForceWithoutHoldCheck
	}
	return false
}

type CryptoShredResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	KekDestroyed              bool                   `protobuf:"varint,1,opt,name=kek_destroyed,json=kekDestroyed,proto3" json:"kek_destroyed,omitempty"`
	CompositionsAffected      uint64                 `protobuf:"varint,2,opt,name=compositions_affected,json=compositionsAffected,proto3" json:"compositions_affected,omitempty"`
	ChunksRefcountDecremented uint64                 `protobuf:"varint,3,opt,name=chunks_refcount_decremented,json=chunksRefcountDecremented,proto3" json:"chunks_refcount_decremented,omitempty"`
	ChunksGcEligible          uint64                 `protobuf:"varint,4,opt,name=chunks_gc_eligible,json=chunksGcEligible,proto3" json:"chunks_gc_eligible,omitempty"`
	ChunksHeldByRetention     uint64                 `protobuf:"varint,5,opt,name=chunks_held_by_retention,json=chunksHeldByRetention,proto3" json:"chunks_held_by_retention,omitempty"`
	Timestamp                 *DeltaTimestamp        `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CryptoShredResponse) Reset() {
	*x = CryptoShredResponse{}
	mi := &file_kiseki_v1_key_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoShredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoShredResponse) ProtoMessage() {}

func (x *CryptoShredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoShredResponse.ProtoReflect.Descriptor instead.
func (*CryptoShredResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{11}
}

func (x *CryptoShredResponse) GetKekDestroyed() bool {
	if x != nil {
		return x.KekDestroyed
	}
	return false
}

func (x *CryptoShredResponse) GetCompositionsAffected() uint64 {
	if x != nil {
		return x.CompositionsAffected
	}
	return 0
}

func (x *CryptoShredResponse) GetChunksRefcountDecremented() uint64 {
	if x != nil {
		return x.ChunksRefcountDecremented
	}
	return 0
}

func (x *CryptoShredResponse) GetChunksGcEligible() uint64 {
	if x != nil {
		return x.ChunksGcEligible
	}
	return 0
}

func (x *CryptoShredResponse) GetChunksHeldByRetention() uint64 {
	if x != nil {
		return x.ChunksHeldByRetention
	}
	return 0
}

func (x *CryptoShredResponse) GetTimestamp() *DeltaTimestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type FullReEncryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *OrgId                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullReEncryptRequest) Reset() {
	*x = FullReEncryptRequest{}
	mi := &file_kiseki_v1_key_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullReEncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullReEncryptRequest) ProtoMessage() {}

func (x *FullReEncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullReEncryptRequest.ProtoReflect.Descriptor instead.
func (*FullReEncryptRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{12}
}

func (x *FullReEncryptRequest) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *FullReEncryptRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type FullReEncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // background job tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullReEncryptResponse) Reset() {
	*x = FullReEncryptResponse{}
	mi := &file_kiseki_v1_key_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullReEncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullReEncryptResponse) ProtoMessage() {}

func (x *FullReEncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullReEncryptResponse.ProtoReflect.Descriptor instead.
func (*FullReEncryptResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{13}
}

func (x *FullReEncryptResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CheckKmsHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *OrgId                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckKmsHealthRequest) Reset() {
	*x = CheckKmsHealthRequest{}
	mi := &file_kiseki_v1_key_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckKmsHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckKmsHealthRequest) ProtoMessage() {}

func (x *CheckKmsHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckKmsHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckKmsHealthRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{14}
}

func (x *CheckKmsHealthRequest) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

type CheckKmsHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reachable     bool                   `protobuf:"varint,1,opt,name=reachable,proto3" json:"reachable,omitempty"`
	LatencyMs     uint64                 `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckKmsHealthResponse) Reset() {
	*x = CheckKmsHealthResponse{}
	mi := &file_kiseki_v1_key_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckKmsHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckKmsHealthResponse) ProtoMessage() {}

func (x *CheckKmsHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_key_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckKmsHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckKmsHealthResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_key_proto_rawDescGZIP(), []int{15}
}

func (x *CheckKmsHealthResponse) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *CheckKmsHealthResponse) GetLatencyMs() uint64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_kiseki_v1_key_proto protoreflect.FileDescriptor

const file_kiseki_v1_key_proto_rawDesc = "" +
	"\n" +
	"\x13kiseki/v1/key.proto\x12\tkiseki.v1\x1a\x16kiseki/v1/common.proto\"B\n" +
	"\x15FetchMasterKeyRequest\x12)\n" +
	"\x05epoch\x18\x01 \x01(\v2\x13.kiseki.v1.KeyEpochR\x05epoch\"\xbe\x01\n" +
	"\x16FetchMasterKeyResponse\x12!\n" +
	"\fkey_material\x18\x01 \x01(\fR\vkeyMaterial\x12)\n" +
	"\x05epoch\x18\x02 \x01(\v2\x13.kiseki.v1.KeyEpochR\x05epoch\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x128\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x19.kiseki.v1.DeltaTimestampR\tcreatedAt\"\x15\n" +
	"\x13CurrentEpochRequest\"v\n" +
	"\x14CurrentEpochResponse\x12-\n" +
	"\acurrent\x18\x01 \x01(\v2\x13.kiseki.v1.KeyEpochR\acurrent\x12/\n" +
	"\bretained\x18\x02 \x03(\v2\x13.kiseki.v1.KeyEpochR\bretained\";\n" +
	"\x16RotateSystemKeyRequest\x12!\n" +
	"\ftriggered_by\x18\x01 \x01(\tR\vtriggeredBy\"K\n" +
	"\x17RotateSystemKeyResponse\x120\n" +
	"\tnew_epoch\x18\x01 \x01(\v2\x13.kiseki.v1.KeyEpochR\bnewEpoch\"\x19\n" +
	"\x17KeyManagerHealthRequest\"\xa9\x01\n" +
	"\x18KeyManagerHealthResponse\x128\n" +
	"\rcurrent_epoch\x18\x01 \x01(\v2\x13.kiseki.v1.KeyEpochR\fcurrentEpoch\x12!\n" +
	"\fraft_members\x18\x02 \x03(\x04R\vraftMembers\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\x04R\x06leader\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\"j\n" +
	"\x16RotateTenantKeyRequest\x12-\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\x12!\n" +
	"\ftriggered_by\x18\x02 \x01(\tR\vtriggeredBy\"K\n" +
	"\x17RotateTenantKeyResponse\x120\n" +
	"\tnew_epoch\x18\x01 \x01(\v2\x13.kiseki.v1.KeyEpochR\bnewEpoch\"|\n" +
	"\x12CryptoShredRequest\x12-\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\x127\n" +
	"\x18force_without_hold_check\x18\x02 \x01(\bR\x15forceWithoutHoldCheck\"\xcf\x02\n" +
	"\x13CryptoShredResponse\x12#\n" +
	"\rkek_destroyed\x18\x01 \x01(\bR\fkekDestroyed\x123\n" +
	"\x15compositions_affected\x18\x02 \x01(\x04R\x14compositionsAffected\x12>\n" +
	"\x1bchunks_refcount_decremented\x18\x03 \x01(\x04R\x19chunksRefcountDecremented\x12,\n" +
	"\x12chunks_gc_eligible\x18\x04 \x01(\x04R\x10chunksGcEligible\x127\n" +
	"\x18chunks_held_by_retention\x18\x05 \x01(\x04R\x15chunksHeldByRetention\x127\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x19.kiseki.v1.DeltaTimestampR\ttimestamp\"]\n" +
	"\x14FullReEncryptRequest\x12-\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\".\n" +
	"\x15FullReEncryptResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"F\n" +
	"\x15CheckKmsHealthRequest\x12-\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\"U\n" +
	"\x16CheckKmsHealthResponse\x12\x1c\n" +
	"\treachable\x18\x01 \x01(\bR\treachable\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x04R\tlatencyMs2\xe8\x02\n" +
	"\x11KeyManagerService\x12U\n" +
	"\x0eFetchMasterKey\x12 .kiseki.v1.FetchMasterKeyRequest\x1a!.kiseki.v1.FetchMasterKeyResponse\x12O\n" +
	"\fCurrentEpoch\x12\x1e.kiseki.v1.CurrentEpochRequest\x1a\x1f.kiseki.v1.CurrentEpochResponse\x12X\n" +
	"\x0fRotateSystemKey\x12!.kiseki.v1.RotateSystemKeyRequest\x1a\".kiseki.v1.RotateSystemKeyResponse\x12Q\n" +
	"\x06Health\x12\".kiseki.v1.KeyManagerHealthRequest\x1a#.kiseki.v1.KeyManagerHealthResponse2\xe5\x02\n" +
	"\x10TenantKeyService\x12X\n" +
	"\x0fRotateTenantKey\x12!.kiseki.v1.RotateTenantKeyRequest\x1a\".kiseki.v1.RotateTenantKeyResponse\x12L\n" +
	"\vCryptoShred\x12\x1d.kiseki.v1.CryptoShredRequest\x1a\x1e.kiseki.v1.CryptoShredResponse\x12R\n" +
	"\rFullReEncrypt\x12\x1f.kiseki.v1.FullReEncryptRequest\x1a .kiseki.v1.FullReEncryptResponse\x12U\n" +
	"\x0eCheckKmsHealth\x12 .kiseki.v1.CheckKmsHealthRequest\x1a!.kiseki.v1.CheckKmsHealthResponseB2Z0github.com/witlox/kiseki/control/proto/kiseki/v1b\x06proto3"

var (
	file_kiseki_v1_key_proto_rawDescOnce sync.Once
	file_kiseki_v1_key_proto_rawDescData []byte
)

func file_kiseki_v1_key_proto_rawDescGZIP() []byte {
	file_kiseki_v1_key_proto_rawDescOnce.Do(func() {
		file_kiseki_v1_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kiseki_v1_key_proto_rawDesc), len(file_kiseki_v1_key_proto_rawDesc)))
	})
	return file_kiseki_v1_key_proto_rawDescData
}

var file_kiseki_v1_key_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_kiseki_v1_key_proto_goTypes = []any{
	(*FetchMasterKeyRequest)(nil),    // 0: kiseki.v1.FetchMasterKeyRequest
	(*FetchMasterKeyResponse)(nil),   // 1: kiseki.v1.FetchMasterKeyResponse
	(*CurrentEpochRequest)(nil),      // 2: kiseki.v1.CurrentEpochRequest
	(*CurrentEpochResponse)(nil),     // 3: kiseki.v1.CurrentEpochResponse
	(*RotateSystemKeyRequest)(nil),   // 4: kiseki.v1.RotateSystemKeyRequest
	(*RotateSystemKeyResponse)(nil),  // 5: kiseki.v1.RotateSystemKeyResponse
	(*KeyManagerHealthRequest)(nil),  // 6: kiseki.v1.KeyManagerHealthRequest
	(*KeyManagerHealthResponse)(nil), // 7: kiseki.v1.KeyManagerHealthResponse
	(*RotateTenantKeyRequest)(nil),   // 8: kiseki.v1.RotateTenantKeyRequest
	(*RotateTenantKeyResponse)(nil),  // 9: kiseki.v1.RotateTenantKeyResponse
	(*CryptoShredRequest)(nil),       // 10: kiseki.v1.CryptoShredRequest
	(*CryptoShredResponse)(nil),      // 11: kiseki.v1.CryptoShredResponse
	(*FullReEncryptRequest)(nil),     // 12: kiseki.v1.FullReEncryptRequest
	(*FullReEncryptResponse)(nil),    // 13: kiseki.v1.FullReEncryptResponse
	(*CheckKmsHealthRequest)(nil),    // 14: kiseki.v1.CheckKmsHealthRequest
	(*CheckKmsHealthResponse)(nil),   // 15: kiseki.v1.CheckKmsHealthResponse
	(*KeyEpoch)(nil),                 // 16: kiseki.v1.KeyEpoch
	(*DeltaTimestamp)(nil),           // 17: kiseki.v1.DeltaTimestamp
	(*OrgId)(nil),                    // 18: kiseki.v1.OrgId
}
var file_kiseki_v1_key_proto_depIdxs = []int32{
	16, // 0: kiseki.v1.FetchMasterKeyRequest.epoch:type_name -> kiseki.v1.KeyEpoch
	16, // 1: kiseki.v1.FetchMasterKeyResponse.epoch:type_name -> kiseki.v1.KeyEpoch
	17, // 2: kiseki.v1.FetchMasterKeyResponse.created_at:type_name -> kiseki.v1.DeltaTimestamp
	16, // 3: kiseki.v1.CurrentEpochResponse.current:type_name -> kiseki.v1.KeyEpoch
	16, // 4: kiseki.v1.CurrentEpochResponse.retained:type_name -> kiseki.v1.KeyEpoch
	16, // 5: kiseki.v1.RotateSystemKeyResponse.new_epoch:type_name -> kiseki.v1.KeyEpoch
	16, // 6: kiseki.v1.KeyManagerHealthResponse.current_epoch:type_name -> kiseki.v1.KeyEpoch
	18, // 7: kiseki.v1.RotateTenantKeyRequest.tenant_id:type_name -> kiseki.v1.OrgId
	16, // 8: kiseki.v1.RotateTenantKeyResponse.new_epoch:type_name -> kiseki.v1.KeyEpoch
	18, // 9: kiseki.v1.CryptoShredRequest.tenant_id:type_name -> kiseki.v1.OrgId
	17, // 10: kiseki.v1.CryptoShredResponse.timestamp:type_name -> kiseki.v1.DeltaTimestamp
	18, // 11: kiseki.v1.FullReEncryptRequest.tenant_id:type_name -> kiseki.v1.OrgId
	18, // 12: kiseki.v1.CheckKmsHealthRequest.tenant_id:type_name -> kiseki.v1.OrgId
	0,  // 13: kiseki.v1.KeyManagerService.FetchMasterKey:input_type -> kiseki.v1.FetchMasterKeyRequest
	2,  // 14: kiseki.v1.KeyManagerService.CurrentEpoch:input_type -> kiseki.v1.CurrentEpochRequest
	4,  // 15: kiseki.v1.KeyManagerService.RotateSystemKey:input_type -> kiseki.v1.RotateSystemKeyRequest
	6,  // 16: kiseki.v1.KeyManagerService.Health:input_type -> kiseki.v1.KeyManagerHealthRequest
	8,  // 17: kiseki.v1.TenantKeyService.RotateTenantKey:input_type -> kiseki.v1.RotateTenantKeyRequest
	10, // 18: kiseki.v1.TenantKeyService.CryptoShred:input_type -> kiseki.v1.CryptoShredRequest
	12, // 19: kiseki.v1.TenantKeyService.FullReEncrypt:input_type -> kiseki.v1.FullReEncryptRequest
	14, // 20: kiseki.v1.TenantKeyService.CheckKmsHealth:input_type -> kiseki.v1.CheckKmsHealthRequest
	1,  // 21: kiseki.v1.KeyManagerService.FetchMasterKey:output_type -> kiseki.v1.FetchMasterKeyResponse
	3,  // 22: kiseki.v1.KeyManagerService.CurrentEpoch:output_type -> kiseki.v1.CurrentEpochResponse
	5,  // 23: kiseki.v1.KeyManagerService.RotateSystemKey:output_type -> kiseki.v1.RotateSystemKeyResponse
	7,  // 24: kiseki.v1.KeyManagerService.Health:output_type -> kiseki.v1.KeyManagerHealthResponse
	9,  // 25: kiseki.v1.TenantKeyService.RotateTenantKey:output_type -> kiseki.v1.RotateTenantKeyResponse
	11, // 26: kiseki.v1.TenantKeyService.CryptoShred:output_type -> kiseki.v1.CryptoShredResponse
	13, // 27: kiseki.v1.TenantKeyService.FullReEncrypt:output_type -> kiseki.v1.FullReEncryptResponse
	15, // 28: kiseki.v1.TenantKeyService.CheckKmsHealth:output_type -> kiseki.v1.CheckKmsHealthResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_kiseki_v1_key_proto_init() }
func file_kiseki_v1_key_proto_init() {
	if File_kiseki_v1_key_proto != nil {
		return
	}
	file_kiseki_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kiseki_v1_key_proto_rawDesc), len(file_kiseki_v1_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kiseki_v1_key_proto_goTypes,
		DependencyIndexes: file_kiseki_v1_key_proto_depIdxs,
		MessageInfos:      file_kiseki_v1_key_proto_msgTypes,
	}.Build()
	File_kiseki_v1_key_proto = out.File
	file_kiseki_v1_key_proto_goTypes = nil
	file_kiseki_v1_key_proto_depIdxs = nil
}
