// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: kiseki/v1/key.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyManagerService_FetchMasterKey_FullMethodName  = "/kiseki.v1.KeyManagerService/FetchMasterKey"
	KeyManagerService_CurrentEpoch_FullMethodName    = "/kiseki.v1.KeyManagerService/CurrentEpoch"
	KeyManagerService_RotateSystemKey_FullMethodName = "/kiseki.v1.KeyManagerService/RotateSystemKey"
	KeyManagerService_Health_FullMethodName          = "/kiseki.v1.KeyManagerService/Health"
)

// KeyManagerServiceClient is the client API for KeyManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyManagerServiceClient interface {
	// Fetch master key for an epoch. Called at server startup and on rotation.
	FetchMasterKey(ctx context.Context, in *FetchMasterKeyRequest, opts ...grpc.CallOption) (*FetchMasterKeyResponse, error)
	// Get current epoch.
	CurrentEpoch(ctx context.Context, in *CurrentEpochRequest, opts ...grpc.CallOption) (*CurrentEpochResponse, error)
	// Rotate system key — creates new epoch.
	RotateSystemKey(ctx context.Context, in *RotateSystemKeyRequest, opts ...grpc.CallOption) (*RotateSystemKeyResponse, error)
	// Health check.
	Health(ctx context.Context, in *KeyManagerHealthRequest, opts ...grpc.CallOption) (*KeyManagerHealthResponse, error)
}

type keyManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyManagerServiceClient(cc grpc.ClientConnInterface) KeyManagerServiceClient {
	return &keyManagerServiceClient{cc}
}

func (c *keyManagerServiceClient) FetchMasterKey(ctx context.Context, in *FetchMasterKeyRequest, opts ...grpc.CallOption) (*FetchMasterKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchMasterKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagerService_FetchMasterKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagerServiceClient) CurrentEpoch(ctx context.Context, in *CurrentEpochRequest, opts ...grpc.CallOption) (*CurrentEpochResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrentEpochResponse)
	err := c.cc.Invoke(ctx, KeyManagerService_CurrentEpoch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagerServiceClient) RotateSystemKey(ctx context.Context, in *RotateSystemKeyRequest, opts ...grpc.CallOption) (*RotateSystemKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSystemKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagerService_RotateSystemKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagerServiceClient) Health(ctx context.Context, in *KeyManagerHealthRequest, opts ...grpc.CallOption) (*KeyManagerHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyManagerHealthResponse)
	err := c.cc.Invoke(ctx, KeyManagerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyManagerServiceServer is the server API for KeyManagerService service.
// All implementations must embed UnimplementedKeyManagerServiceServer
// for forward compatibility.
type KeyManagerServiceServer interface {
	// Fetch master key for an epoch. Called at server startup and on rotation.
	FetchMasterKey(context.Context, *FetchMasterKeyRequest) (*FetchMasterKeyResponse, error)
	// Get current epoch.
	CurrentEpoch(context.Context, *CurrentEpochRequest) (*CurrentEpochResponse, error)
	// Rotate system key — creates new epoch.
	RotateSystemKey(context.Context, *RotateSystemKeyRequest) (*RotateSystemKeyResponse, error)
	// Health check.
	Health(context.Context, *KeyManagerHealthRequest) (*KeyManagerHealthResponse, error)
	mustEmbedUnimplementedKeyManagerServiceServer()
}

// UnimplementedKeyManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyManagerServiceServer struct{}

func (UnimplementedKeyManagerServiceServer) FetchMasterKey(context.Context, *FetchMasterKeyRequest) (*FetchMasterKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchMasterKey not implemented")
}
func (UnimplementedKeyManagerServiceServer) CurrentEpoch(context.Context, *CurrentEpochRequest) (*CurrentEpochResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CurrentEpoch not implemented")
}
func (UnimplementedKeyManagerServiceServer) RotateSystemKey(context.Context, *RotateSystemKeyRequest) (*RotateSystemKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSystemKey not implemented")
}
func (UnimplementedKeyManagerServiceServer) Health(context.Context, *KeyManagerHealthRequest) (*KeyManagerHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedKeyManagerServiceServer) mustEmbedUnimplementedKeyManagerServiceServer() {}
func (UnimplementedKeyManagerServiceServer) testEmbeddedByValue()                           {}

// UnsafeKeyManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyManagerServiceServer will
// result in compilation errors.
type UnsafeKeyManagerServiceServer interface {
	mustEmbedUnimplementedKeyManagerServiceServer()
}

func RegisterKeyManagerServiceServer(s grpc.ServiceRegistrar, srv KeyManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyManagerService_ServiceDesc, srv)
}

func _KeyManagerService_FetchMasterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMasterKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServiceServer).FetchMasterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagerService_FetchMasterKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServiceServer).FetchMasterKey(ctx, req.(*FetchMasterKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagerService_CurrentEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServiceServer).CurrentEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagerService_CurrentEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServiceServer).CurrentEpoch(ctx, req.(*CurrentEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagerService_RotateSystemKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSystemKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServiceServer).RotateSystemKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagerService_RotateSystemKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServiceServer).RotateSystemKey(ctx, req.(*RotateSystemKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyManagerHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServiceServer).Health(ctx, req.(*KeyManagerHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyManagerService_ServiceDesc is the grpc.ServiceDesc for KeyManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiseki.v1.KeyManagerService",
	HandlerType: (*KeyManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchMasterKey",
			Handler:    _KeyManagerService_FetchMasterKey_Handler,
		},
		{
			MethodName: "CurrentEpoch",
			Handler:    _KeyManagerService_CurrentEpoch_Handler,
		},
		{
			MethodName: "RotateSystemKey",
			Handler:    _KeyManagerService_RotateSystemKey_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _KeyManagerService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kiseki/v1/key.proto",
}

const (
	TenantKeyService_RotateTenantKey_FullMethodName = "/kiseki.v1.TenantKeyService/RotateTenantKey"
	TenantKeyService_CryptoShred_FullMethodName     = "/kiseki.v1.TenantKeyService/CryptoShred"
	TenantKeyService_FullReEncrypt_FullMethodName   = "/kiseki.v1.TenantKeyService/FullReEncrypt"
	TenantKeyService_CheckKmsHealth_FullMethodName  = "/kiseki.v1.TenantKeyService/CheckKmsHealth"
)

// TenantKeyServiceClient is the client API for TenantKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantKeyServiceClient interface {
	// Rotate tenant key via tenant KMS.
	RotateTenantKey(ctx context.Context, in *RotateTenantKeyRequest, opts ...grpc.CallOption) (*RotateTenantKeyResponse, error)
	// Execute crypto-shred — destroy tenant KEK.
	CryptoShred(ctx context.Context, in *CryptoShredRequest, opts ...grpc.CallOption) (*CryptoShredResponse, error)
	// Trigger full re-encryption (key compromise).
	FullReEncrypt(ctx context.Context, in *FullReEncryptRequest, opts ...grpc.CallOption) (*FullReEncryptResponse, error)
	// Check tenant KMS reachability.
	CheckKmsHealth(ctx context.Context, in *CheckKmsHealthRequest, opts ...grpc.CallOption) (*CheckKmsHealthResponse, error)
}

type tenantKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantKeyServiceClient(cc grpc.ClientConnInterface) TenantKeyServiceClient {
	return &tenantKeyServiceClient{cc}
}

func (c *tenantKeyServiceClient) RotateTenantKey(ctx context.Context, in *RotateTenantKeyRequest, opts ...grpc.CallOption) (*RotateTenantKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateTenantKeyResponse)
	err := c.cc.Invoke(ctx, TenantKeyService_RotateTenantKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantKeyServiceClient) CryptoShred(ctx context.Context, in *CryptoShredRequest, opts ...grpc.CallOption) (*CryptoShredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CryptoShredResponse)
	err := c.cc.Invoke(ctx, TenantKeyService_CryptoShred_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantKeyServiceClient) FullReEncrypt(ctx context.Context, in *FullReEncryptRequest, opts ...grpc.CallOption) (*FullReEncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullReEncryptResponse)
	err := c.cc.Invoke(ctx, TenantKeyService_FullReEncrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantKeyServiceClient) CheckKmsHealth(ctx context.Context, in *CheckKmsHealthRequest, opts ...grpc.CallOption) (*CheckKmsHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckKmsHealthResponse)
	err := c.cc.Invoke(ctx, TenantKeyService_CheckKmsHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantKeyServiceServer is the server API for TenantKeyService service.
// All implementations must embed UnimplementedTenantKeyServiceServer
// for forward compatibility.
type TenantKeyServiceServer interface {
	// Rotate tenant key via tenant KMS.
	RotateTenantKey(context.Context, *RotateTenantKeyRequest) (*RotateTenantKeyResponse, error)
	// Execute crypto-shred — destroy tenant KEK.
	CryptoShred(context.Context, *CryptoShredRequest) (*CryptoShredResponse, error)
	// Trigger full re-encryption (key compromise).
	FullReEncrypt(context.Context, *FullReEncryptRequest) (*FullReEncryptResponse, error)
	// Check tenant KMS reachability.
	CheckKmsHealth(context.Context, *CheckKmsHealthRequest) (*CheckKmsHealthResponse, error)
	mustEmbedUnimplementedTenantKeyServiceServer()
}

// UnimplementedTenantKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantKeyServiceServer struct{}

func (UnimplementedTenantKeyServiceServer) RotateTenantKey(context.Context, *RotateTenantKeyRequest) (*RotateTenantKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateTenantKey not implemented")
}
func (UnimplementedTenantKeyServiceServer) CryptoShred(context.Context, *CryptoShredRequest) (*CryptoShredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CryptoShred not implemented")
}
func (UnimplementedTenantKeyServiceServer) FullReEncrypt(context.Context, *FullReEncryptRequest) (*FullReEncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FullReEncrypt not implemented")
}
func (UnimplementedTenantKeyServiceServer) CheckKmsHealth(context.Context, *CheckKmsHealthRequest) (*CheckKmsHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckKmsHealth not implemented")
}
func (UnimplementedTenantKeyServiceServer) mustEmbedUnimplementedTenantKeyServiceServer() {}
func (UnimplementedTenantKeyServiceServer) testEmbeddedByValue()                          {}

// UnsafeTenantKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantKeyServiceServer will
// result in compilation errors.
type UnsafeTenantKeyServiceServer interface {
	mustEmbedUnimplementedTenantKeyServiceServer()
}

func RegisterTenantKeyServiceServer(s grpc.ServiceRegistrar, srv TenantKeyServiceServer) {
	// If the following call panics, it indicates UnimplementedTenantKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantKeyService_ServiceDesc, srv)
}

func _TenantKeyService_RotateTenantKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateTenantKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantKeyServiceServer).RotateTenantKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantKeyService_RotateTenantKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantKeyServiceServer).RotateTenantKey(ctx, req.(*RotateTenantKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantKeyService_CryptoShred_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CryptoShredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantKeyServiceServer).CryptoShred(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantKeyService_CryptoShred_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantKeyServiceServer).CryptoShred(ctx, req.(*CryptoShredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantKeyService_FullReEncrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullReEncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantKeyServiceServer).FullReEncrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantKeyService_FullReEncrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantKeyServiceServer).FullReEncrypt(ctx, req.(*FullReEncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantKeyService_CheckKmsHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckKmsHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantKeyServiceServer).CheckKmsHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantKeyService_CheckKmsHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantKeyServiceServer).CheckKmsHealth(ctx, req.(*CheckKmsHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantKeyService_ServiceDesc is the grpc.ServiceDesc for TenantKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiseki.v1.TenantKeyService",
	HandlerType: (*TenantKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RotateTenantKey",
			Handler:    _TenantKeyService_RotateTenantKey_Handler,
		},
		{
			MethodName: "CryptoShred",
			Handler:    _TenantKeyService_CryptoShred_Handler,
		},
		{
			MethodName: "FullReEncrypt",
			Handler:    _TenantKeyService_FullReEncrypt_Handler,
		},
		{
			MethodName: "CheckKmsHealth",
			Handler:    _TenantKeyService_CheckKmsHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kiseki/v1/key.proto",
}
