// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: kiseki/v1/log.proto

// Log context — deltas, shards, Raft lifecycle.
// Spec: specs/architecture/data-models/log.rs,
//       specs/architecture/api-contracts.md#Log-context,
//       specs/features/log.feature,
//       invariants.md I-L1..I-L8, I-O1, I-O2, I-O6.
//
// Core Log operations are available via `LogOps` trait (intra-process)
// and via `LogService` gRPC (network data path). The proto also
// defines the on-disk delta envelope, events emitted onto the audit
// shard, and cross-node Raft replication carriers.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogService_AppendDelta_FullMethodName    = "/kiseki.v1.LogService/AppendDelta"
	LogService_ReadDeltas_FullMethodName     = "/kiseki.v1.LogService/ReadDeltas"
	LogService_ShardHealth_FullMethodName    = "/kiseki.v1.LogService/ShardHealth"
	LogService_SetMaintenance_FullMethodName = "/kiseki.v1.LogService/SetMaintenance"
)

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	// Append a delta to a shard. Returns the assigned sequence number.
	AppendDelta(ctx context.Context, in *AppendDeltaRequest, opts ...grpc.CallOption) (*AppendDeltaResponse, error)
	// Read deltas in [from, to] inclusive from a shard.
	ReadDeltas(ctx context.Context, in *ReadDeltasRequest, opts ...grpc.CallOption) (*ReadDeltasResponse, error)
	// Get shard health and metadata.
	ShardHealth(ctx context.Context, in *ShardHealthRequest, opts ...grpc.CallOption) (*ShardHealthResponse, error)
	// Set or clear maintenance mode on a shard (I-O6).
	SetMaintenance(ctx context.Context, in *SetMaintenanceRequest, opts ...grpc.CallOption) (*SetMaintenanceResponse, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) AppendDelta(ctx context.Context, in *AppendDeltaRequest, opts ...grpc.CallOption) (*AppendDeltaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendDeltaResponse)
	err := c.cc.Invoke(ctx, LogService_AppendDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) ReadDeltas(ctx context.Context, in *ReadDeltasRequest, opts ...grpc.CallOption) (*ReadDeltasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadDeltasResponse)
	err := c.cc.Invoke(ctx, LogService_ReadDeltas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) ShardHealth(ctx context.Context, in *ShardHealthRequest, opts ...grpc.CallOption) (*ShardHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardHealthResponse)
	err := c.cc.Invoke(ctx, LogService_ShardHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) SetMaintenance(ctx context.Context, in *SetMaintenanceRequest, opts ...grpc.CallOption) (*SetMaintenanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMaintenanceResponse)
	err := c.cc.Invoke(ctx, LogService_SetMaintenance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility.
type LogServiceServer interface {
	// Append a delta to a shard. Returns the assigned sequence number.
	AppendDelta(context.Context, *AppendDeltaRequest) (*AppendDeltaResponse, error)
	// Read deltas in [from, to] inclusive from a shard.
	ReadDeltas(context.Context, *ReadDeltasRequest) (*ReadDeltasResponse, error)
	// Get shard health and metadata.
	ShardHealth(context.Context, *ShardHealthRequest) (*ShardHealthResponse, error)
	// Set or clear maintenance mode on a shard (I-O6).
	SetMaintenance(context.Context, *SetMaintenanceRequest) (*SetMaintenanceResponse, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServiceServer struct{}

func (UnimplementedLogServiceServer) AppendDelta(context.Context, *AppendDeltaRequest) (*AppendDeltaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendDelta not implemented")
}
func (UnimplementedLogServiceServer) ReadDeltas(context.Context, *ReadDeltasRequest) (*ReadDeltasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadDeltas not implemented")
}
func (UnimplementedLogServiceServer) ShardHealth(context.Context, *ShardHealthRequest) (*ShardHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShardHealth not implemented")
}
func (UnimplementedLogServiceServer) SetMaintenance(context.Context, *SetMaintenanceRequest) (*SetMaintenanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMaintenance not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}
func (UnimplementedLogServiceServer) testEmbeddedByValue()                    {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	// If the following call panics, it indicates UnimplementedLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_AppendDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendDeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).AppendDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_AppendDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).AppendDelta(ctx, req.(*AppendDeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_ReadDeltas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDeltasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).ReadDeltas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_ReadDeltas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).ReadDeltas(ctx, req.(*ReadDeltasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_ShardHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).ShardHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_ShardHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).ShardHealth(ctx, req.(*ShardHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_SetMaintenance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMaintenanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SetMaintenance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_SetMaintenance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SetMaintenance(ctx, req.(*SetMaintenanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiseki.v1.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendDelta",
			Handler:    _LogService_AppendDelta_Handler,
		},
		{
			MethodName: "ReadDeltas",
			Handler:    _LogService_ReadDeltas_Handler,
		},
		{
			MethodName: "ShardHealth",
			Handler:    _LogService_ShardHealth_Handler,
		},
		{
			MethodName: "SetMaintenance",
			Handler:    _LogService_SetMaintenance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kiseki/v1/log.proto",
}
