// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kiseki/v1/view.proto

// View Materialization context — descriptors, stream processor state, MVCC.
// Spec: specs/architecture/data-models/view.rs,
//       specs/architecture/api-contracts.md#View-Materialization-context,
//       specs/features/view-materialization.feature,
//       invariants.md I-V1..I-V4, I-K9, I-O3.

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolSemantics int32

const (
	ProtocolSemantics_PROTOCOL_SEMANTICS_UNSPECIFIED ProtocolSemantics = 0
	ProtocolSemantics_PROTOCOL_SEMANTICS_POSIX       ProtocolSemantics = 1
	ProtocolSemantics_PROTOCOL_SEMANTICS_S3          ProtocolSemantics = 2
)

// Enum value maps for ProtocolSemantics.
var (
	ProtocolSemantics_name = map[int32]string{
		0: "PROTOCOL_SEMANTICS_UNSPECIFIED",
		1: "PROTOCOL_SEMANTICS_POSIX",
		2: "PROTOCOL_SEMANTICS_S3",
	}
	ProtocolSemantics_value = map[string]int32{
		"PROTOCOL_SEMANTICS_UNSPECIFIED": 0,
		"PROTOCOL_SEMANTICS_POSIX":       1,
		"PROTOCOL_SEMANTICS_S3":          2,
	}
)

func (x ProtocolSemantics) Enum() *ProtocolSemantics {
	p := new(ProtocolSemantics)
	*p = x
	return p
}

func (x ProtocolSemantics) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolSemantics) Descriptor() protoreflect.EnumDescriptor {
	return file_kiseki_v1_view_proto_enumTypes[0].Descriptor()
}

func (ProtocolSemantics) Type() protoreflect.EnumType {
	return &file_kiseki_v1_view_proto_enumTypes[0]
}

func (x ProtocolSemantics) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolSemantics.Descriptor instead.
func (ProtocolSemantics) EnumDescriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{0}
}

type ConsistencyModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Model:
	//
	//	*ConsistencyModel_ReadYourWrites
	//	*ConsistencyModel_BoundedStaleness
	//	*ConsistencyModel_Eventual
	Model         isConsistencyModel_Model `protobuf_oneof:"model"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsistencyModel) Reset() {
	*x = ConsistencyModel{}
	mi := &file_kiseki_v1_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsistencyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistencyModel) ProtoMessage() {}

func (x *ConsistencyModel) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistencyModel.ProtoReflect.Descriptor instead.
func (*ConsistencyModel) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{0}
}

func (x *ConsistencyModel) GetModel() isConsistencyModel_Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *ConsistencyModel) GetReadYourWrites() *ReadYourWrites {
	if x != nil {
		if x, ok := x.Model.(*ConsistencyModel_ReadYourWrites); ok {
			return x.ReadYourWrites
		}
	}
	return nil
}

func (x *ConsistencyModel) GetBoundedStaleness() *BoundedStaleness {
	if x != nil {
		if x, ok := x.Model.(*ConsistencyModel_BoundedStaleness); ok {
			return x.BoundedStaleness
		}
	}
	return nil
}

func (x *ConsistencyModel) GetEventual() *Eventual {
	if x != nil {
		if x, ok := x.Model.(*ConsistencyModel_Eventual); ok {
			return x.Eventual
		}
	}
	return nil
}

type isConsistencyModel_Model interface {
	isConsistencyModel_Model()
}

type ConsistencyModel_ReadYourWrites struct {
	// Read-your-writes; stream processor tracks log tip (I-V3).
	ReadYourWrites *ReadYourWrites `protobuf:"bytes,1,opt,name=read_your_writes,json=readYourWrites,proto3,oneof"`
}

type ConsistencyModel_BoundedStaleness struct {
	// Bounded staleness; effective = max(this, compliance floor) (I-K9).
	BoundedStaleness *BoundedStaleness `protobuf:"bytes,2,opt,name=bounded_staleness,json=boundedStaleness,proto3,oneof"`
}

type ConsistencyModel_Eventual struct {
	// No bound; used for analytics views.
	Eventual *Eventual `protobuf:"bytes,3,opt,name=eventual,proto3,oneof"`
}

func (*ConsistencyModel_ReadYourWrites) isConsistencyModel_Model() {}

func (*ConsistencyModel_BoundedStaleness) isConsistencyModel_Model() {}

func (*ConsistencyModel_Eventual) isConsistencyModel_Model() {}

type ReadYourWrites struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadYourWrites) Reset() {
	*x = ReadYourWrites{}
	mi := &file_kiseki_v1_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadYourWrites) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadYourWrites) ProtoMessage() {}

func (x *ReadYourWrites) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadYourWrites.ProtoReflect.Descriptor instead.
func (*ReadYourWrites) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{1}
}

type BoundedStaleness struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxStalenessMs uint64                 `protobuf:"varint,1,opt,name=max_staleness_ms,json=maxStalenessMs,proto3" json:"max_staleness_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BoundedStaleness) Reset() {
	*x = BoundedStaleness{}
	mi := &file_kiseki_v1_view_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundedStaleness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundedStaleness) ProtoMessage() {}

func (x *BoundedStaleness) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundedStaleness.ProtoReflect.Descriptor instead.
func (*BoundedStaleness) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{2}
}

func (x *BoundedStaleness) GetMaxStalenessMs() uint64 {
	if x != nil {
		return x.MaxStalenessMs
	}
	return 0
}

type Eventual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eventual) Reset() {
	*x = Eventual{}
	mi := &file_kiseki_v1_view_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eventual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eventual) ProtoMessage() {}

func (x *Eventual) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eventual.ProtoReflect.Descriptor instead.
func (*Eventual) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{3}
}

type ViewDescriptor struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ViewId       *ViewId                `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	TenantId     *OrgId                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SourceShards []*ShardId             `protobuf:"bytes,3,rep,name=source_shards,json=sourceShards,proto3" json:"source_shards,omitempty"`
	Protocol     ProtocolSemantics      `protobuf:"varint,4,opt,name=protocol,proto3,enum=kiseki.v1.ProtocolSemantics" json:"protocol,omitempty"`
	Consistency  *ConsistencyModel      `protobuf:"bytes,5,opt,name=consistency,proto3" json:"consistency,omitempty"`
	AffinityPool *AffinityPoolId        `protobuf:"bytes,6,opt,name=affinity_pool,json=affinityPool,proto3" json:"affinity_pool,omitempty"`
	// Discardable views can be dropped and rebuilt from log (I-V1).
	Discardable   bool            `protobuf:"varint,7,opt,name=discardable,proto3" json:"discardable,omitempty"`
	Version       uint64          `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"` // incremented on update
	CreatedAt     *DeltaTimestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewDescriptor) Reset() {
	*x = ViewDescriptor{}
	mi := &file_kiseki_v1_view_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewDescriptor) ProtoMessage() {}

func (x *ViewDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewDescriptor.ProtoReflect.Descriptor instead.
func (*ViewDescriptor) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{4}
}

func (x *ViewDescriptor) GetViewId() *ViewId {
	if x != nil {
		return x.ViewId
	}
	return nil
}

func (x *ViewDescriptor) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *ViewDescriptor) GetSourceShards() []*ShardId {
	if x != nil {
		return x.SourceShards
	}
	return nil
}

func (x *ViewDescriptor) GetProtocol() ProtocolSemantics {
	if x != nil {
		return x.Protocol
	}
	return ProtocolSemantics_PROTOCOL_SEMANTICS_UNSPECIFIED
}

func (x *ViewDescriptor) GetConsistency() *ConsistencyModel {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *ViewDescriptor) GetAffinityPool() *AffinityPoolId {
	if x != nil {
		return x.AffinityPool
	}
	return nil
}

func (x *ViewDescriptor) GetDiscardable() bool {
	if x != nil {
		return x.Discardable
	}
	return false
}

func (x *ViewDescriptor) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ViewDescriptor) GetCreatedAt() *DeltaTimestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ShardWatermark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       *ShardId               `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Position      uint64                 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"` // sequence number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardWatermark) Reset() {
	*x = ShardWatermark{}
	mi := &file_kiseki_v1_view_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardWatermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardWatermark) ProtoMessage() {}

func (x *ShardWatermark) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardWatermark.ProtoReflect.Descriptor instead.
func (*ShardWatermark) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{5}
}

func (x *ShardWatermark) GetShardId() *ShardId {
	if x != nil {
		return x.ShardId
	}
	return nil
}

func (x *ShardWatermark) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type StreamProcessorState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ViewId            *ViewId                `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	TenantId          *OrgId                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Watermarks        []*ShardWatermark      `protobuf:"bytes,3,rep,name=watermarks,proto3" json:"watermarks,omitempty"`
	DescriptorVersion uint64                 `protobuf:"varint,4,opt,name=descriptor_version,json=descriptorVersion,proto3" json:"descriptor_version,omitempty"`
	Status            *StreamProcessorStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Whether this processor has the tenant KEK cached (I-O3).
	HasCachedTenantKey bool `protobuf:"varint,6,opt,name=has_cached_tenant_key,json=hasCachedTenantKey,proto3" json:"has_cached_tenant_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamProcessorState) Reset() {
	*x = StreamProcessorState{}
	mi := &file_kiseki_v1_view_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProcessorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProcessorState) ProtoMessage() {}

func (x *StreamProcessorState) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProcessorState.ProtoReflect.Descriptor instead.
func (*StreamProcessorState) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{6}
}

func (x *StreamProcessorState) GetViewId() *ViewId {
	if x != nil {
		return x.ViewId
	}
	return nil
}

func (x *StreamProcessorState) GetTenantId() *OrgId {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *StreamProcessorState) GetWatermarks() []*ShardWatermark {
	if x != nil {
		return x.Watermarks
	}
	return nil
}

func (x *StreamProcessorState) GetDescriptorVersion() uint64 {
	if x != nil {
		return x.DescriptorVersion
	}
	return 0
}

func (x *StreamProcessorState) GetStatus() *StreamProcessorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StreamProcessorState) GetHasCachedTenantKey() bool {
	if x != nil {
		return x.HasCachedTenantKey
	}
	return false
}

type StreamProcessorStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*StreamProcessorStatus_Running
	//	*StreamProcessorStatus_StalenessViolation
	//	*StreamProcessorStatus_KeyUnavailable
	//	*StreamProcessorStatus_SourceUnavailable
	//	*StreamProcessorStatus_Stopped
	//	*StreamProcessorStatus_Rebuilding
	Status        isStreamProcessorStatus_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProcessorStatus) Reset() {
	*x = StreamProcessorStatus{}
	mi := &file_kiseki_v1_view_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProcessorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProcessorStatus) ProtoMessage() {}

func (x *StreamProcessorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProcessorStatus.ProtoReflect.Descriptor instead.
func (*StreamProcessorStatus) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{7}
}

func (x *StreamProcessorStatus) GetStatus() isStreamProcessorStatus_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StreamProcessorStatus) GetRunning() *Running {
	if x != nil {
		if x, ok := x.Status.(*StreamProcessorStatus_Running); ok {
			return x.Running
		}
	}
	return nil
}

func (x *StreamProcessorStatus) GetStalenessViolation() *StalenessViolation {
	if x != nil {
		if x, ok := x.Status.(*StreamProcessorStatus_StalenessViolation); ok {
			return x.StalenessViolation
		}
	}
	return nil
}

func (x *StreamProcessorStatus) GetKeyUnavailable() *KeyUnavailable {
	if x != nil {
		if x, ok := x.Status.(*StreamProcessorStatus_KeyUnavailable); ok {
			return x.KeyUnavailable
		}
	}
	return nil
}

func (x *StreamProcessorStatus) GetSourceUnavailable() *SourceUnavailable {
	if x != nil {
		if x, ok := x.Status.(*StreamProcessorStatus_SourceUnavailable); ok {
			return x.SourceUnavailable
		}
	}
	return nil
}

func (x *StreamProcessorStatus) GetStopped() *Stopped {
	if x != nil {
		if x, ok := x.Status.(*StreamProcessorStatus_Stopped); ok {
			return x.Stopped
		}
	}
	return nil
}

func (x *StreamProcessorStatus) GetRebuilding() *Rebuilding {
	if x != nil {
		if x, ok := x.Status.(*StreamProcessorStatus_Rebuilding); ok {
			return x.Rebuilding
		}
	}
	return nil
}

type isStreamProcessorStatus_Status interface {
	isStreamProcessorStatus_Status()
}

type StreamProcessorStatus_Running struct {
	Running *Running `protobuf:"bytes,1,opt,name=running,proto3,oneof"`
}

type StreamProcessorStatus_StalenessViolation struct {
	StalenessViolation *StalenessViolation `protobuf:"bytes,2,opt,name=staleness_violation,json=stalenessViolation,proto3,oneof"`
}

type StreamProcessorStatus_KeyUnavailable struct {
	KeyUnavailable *KeyUnavailable `protobuf:"bytes,3,opt,name=key_unavailable,json=keyUnavailable,proto3,oneof"`
}

type StreamProcessorStatus_SourceUnavailable struct {
	SourceUnavailable *SourceUnavailable `protobuf:"bytes,4,opt,name=source_unavailable,json=sourceUnavailable,proto3,oneof"`
}

type StreamProcessorStatus_Stopped struct {
	Stopped *Stopped `protobuf:"bytes,5,opt,name=stopped,proto3,oneof"`
}

type StreamProcessorStatus_Rebuilding struct {
	Rebuilding *Rebuilding `protobuf:"bytes,6,opt,name=rebuilding,proto3,oneof"`
}

func (*StreamProcessorStatus_Running) isStreamProcessorStatus_Status() {}

func (*StreamProcessorStatus_StalenessViolation) isStreamProcessorStatus_Status() {}

func (*StreamProcessorStatus_KeyUnavailable) isStreamProcessorStatus_Status() {}

func (*StreamProcessorStatus_SourceUnavailable) isStreamProcessorStatus_Status() {}

func (*StreamProcessorStatus_Stopped) isStreamProcessorStatus_Status() {}

func (*StreamProcessorStatus_Rebuilding) isStreamProcessorStatus_Status() {}

type Running struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Running) Reset() {
	*x = Running{}
	mi := &file_kiseki_v1_view_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Running) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Running) ProtoMessage() {}

func (x *Running) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Running.ProtoReflect.Descriptor instead.
func (*Running) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{8}
}

type StalenessViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BehindMs      uint64                 `protobuf:"varint,1,opt,name=behind_ms,json=behindMs,proto3" json:"behind_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StalenessViolation) Reset() {
	*x = StalenessViolation{}
	mi := &file_kiseki_v1_view_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StalenessViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StalenessViolation) ProtoMessage() {}

func (x *StalenessViolation) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StalenessViolation.ProtoReflect.Descriptor instead.
func (*StalenessViolation) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{9}
}

func (x *StalenessViolation) GetBehindMs() uint64 {
	if x != nil {
		return x.BehindMs
	}
	return 0
}

type KeyUnavailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyUnavailable) Reset() {
	*x = KeyUnavailable{}
	mi := &file_kiseki_v1_view_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyUnavailable) ProtoMessage() {}

func (x *KeyUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyUnavailable.ProtoReflect.Descriptor instead.
func (*KeyUnavailable) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{10}
}

type SourceUnavailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         *ShardId               `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceUnavailable) Reset() {
	*x = SourceUnavailable{}
	mi := &file_kiseki_v1_view_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceUnavailable) ProtoMessage() {}

func (x *SourceUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceUnavailable.ProtoReflect.Descriptor instead.
func (*SourceUnavailable) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{11}
}

func (x *SourceUnavailable) GetShard() *ShardId {
	if x != nil {
		return x.Shard
	}
	return nil
}

type Stopped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stopped) Reset() {
	*x = Stopped{}
	mi := &file_kiseki_v1_view_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stopped) ProtoMessage() {}

func (x *Stopped) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stopped.ProtoReflect.Descriptor instead.
func (*Stopped) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{12}
}

type Rebuilding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgressPct   float32                `protobuf:"fixed32,1,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rebuilding) Reset() {
	*x = Rebuilding{}
	mi := &file_kiseki_v1_view_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rebuilding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rebuilding) ProtoMessage() {}

func (x *Rebuilding) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rebuilding.ProtoReflect.Descriptor instead.
func (*Rebuilding) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{13}
}

func (x *Rebuilding) GetProgressPct() float32 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

type MvccReadPin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinId         []byte                 `protobuf:"bytes,1,opt,name=pin_id,json=pinId,proto3" json:"pin_id,omitempty"` // 16-byte UUID
	ViewId        *ViewId                `protobuf:"bytes,2,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	Position      uint64                 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"` // sequence number
	CreatedAt     *WallTime              `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MvccReadPin) Reset() {
	*x = MvccReadPin{}
	mi := &file_kiseki_v1_view_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MvccReadPin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MvccReadPin) ProtoMessage() {}

func (x *MvccReadPin) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MvccReadPin.ProtoReflect.Descriptor instead.
func (*MvccReadPin) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{14}
}

func (x *MvccReadPin) GetPinId() []byte {
	if x != nil {
		return x.PinId
	}
	return nil
}

func (x *MvccReadPin) GetViewId() *ViewId {
	if x != nil {
		return x.ViewId
	}
	return nil
}

func (x *MvccReadPin) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *MvccReadPin) GetCreatedAt() *WallTime {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MvccReadPin) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *ViewDescriptor        `protobuf:"bytes,1,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateViewRequest) Reset() {
	*x = CreateViewRequest{}
	mi := &file_kiseki_v1_view_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewRequest) ProtoMessage() {}

func (x *CreateViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewRequest.ProtoReflect.Descriptor instead.
func (*CreateViewRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{15}
}

func (x *CreateViewRequest) GetDescriptor_() *ViewDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

type DiscardViewRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ViewId *ViewId                `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	// The org that approved the discard (required if caller is not
	// the tenant admin of the owning org).
	ApprovedBy    *OrgId `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardViewRequest) Reset() {
	*x = DiscardViewRequest{}
	mi := &file_kiseki_v1_view_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardViewRequest) ProtoMessage() {}

func (x *DiscardViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardViewRequest.ProtoReflect.Descriptor instead.
func (*DiscardViewRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{16}
}

func (x *DiscardViewRequest) GetViewId() *ViewId {
	if x != nil {
		return x.ViewId
	}
	return nil
}

func (x *DiscardViewRequest) GetApprovedBy() *OrgId {
	if x != nil {
		return x.ApprovedBy
	}
	return nil
}

type UpdateDescriptorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        *ViewId                `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	NewDescriptor *ViewDescriptor        `protobuf:"bytes,2,opt,name=new_descriptor,json=newDescriptor,proto3" json:"new_descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDescriptorRequest) Reset() {
	*x = UpdateDescriptorRequest{}
	mi := &file_kiseki_v1_view_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDescriptorRequest) ProtoMessage() {}

func (x *UpdateDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDescriptorRequest.ProtoReflect.Descriptor instead.
func (*UpdateDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDescriptorRequest) GetViewId() *ViewId {
	if x != nil {
		return x.ViewId
	}
	return nil
}

func (x *UpdateDescriptorRequest) GetNewDescriptor() *ViewDescriptor {
	if x != nil {
		return x.NewDescriptor
	}
	return nil
}

type AcquirePinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        *ViewId                `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquirePinRequest) Reset() {
	*x = AcquirePinRequest{}
	mi := &file_kiseki_v1_view_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquirePinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquirePinRequest) ProtoMessage() {}

func (x *AcquirePinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquirePinRequest.ProtoReflect.Descriptor instead.
func (*AcquirePinRequest) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{18}
}

func (x *AcquirePinRequest) GetViewId() *ViewId {
	if x != nil {
		return x.ViewId
	}
	return nil
}

func (x *AcquirePinRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type AcquirePinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           *MvccReadPin           `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquirePinResponse) Reset() {
	*x = AcquirePinResponse{}
	mi := &file_kiseki_v1_view_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquirePinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquirePinResponse) ProtoMessage() {}

func (x *AcquirePinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kiseki_v1_view_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquirePinResponse.ProtoReflect.Descriptor instead.
func (*AcquirePinResponse) Descriptor() ([]byte, []int) {
	return file_kiseki_v1_view_proto_rawDescGZIP(), []int{19}
}

func (x *AcquirePinResponse) GetPin() *MvccReadPin {
	if x != nil {
		return x.Pin
	}
	return nil
}

var File_kiseki_v1_view_proto protoreflect.FileDescriptor

const file_kiseki_v1_view_proto_rawDesc = "" +
	"\n" +
	"\x14kiseki/v1/view.proto\x12\tkiseki.v1\x1a\x16kiseki/v1/common.proto\x1a\x15kiseki/v1/chunk.proto\"\xe1\x01\n" +
	"\x10ConsistencyModel\x12E\n" +
	"\x10read_your_writes\x18\x01 \x01(\v2\x19.kiseki.v1.ReadYourWritesH\x00R\x0ereadYourWrites\x12J\n" +
	"\x11bounded_staleness\x18\x02 \x01(\v2\x1b.kiseki.v1.BoundedStalenessH\x00R\x10boundedStaleness\x121\n" +
	"\beventual\x18\x03 \x01(\v2\x13.kiseki.v1.EventualH\x00R\beventualB\a\n" +
	"\x05model\"\x10\n" +
	"\x0eReadYourWrites\"<\n" +
	"\x10BoundedStaleness\x12(\n" +
	"\x10max_staleness_ms\x18\x01 \x01(\x04R\x0emaxStalenessMs\"\n" +
	"\n" +
	"\bEventual\"\xd3\x03\n" +
	"\x0eViewDescriptor\x12*\n" +
	"\aview_id\x18\x01 \x01(\v2\x11.kiseki.v1.ViewIdR\x06viewId\x12-\n" +
	"\ttenant_id\x18\x02 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\x127\n" +
	"\rsource_shards\x18\x03 \x03(\v2\x12.kiseki.v1.ShardIdR\fsourceShards\x128\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x1c.kiseki.v1.ProtocolSemanticsR\bprotocol\x12=\n" +
	"\vconsistency\x18\x05 \x01(\v2\x1b.kiseki.v1.ConsistencyModelR\vconsistency\x12>\n" +
	"\raffinity_pool\x18\x06 \x01(\v2\x19.kiseki.v1.AffinityPoolIdR\faffinityPool\x12 \n" +
	"\vdiscardable\x18\a \x01(\bR\vdiscardable\x12\x18\n" +
	"\aversion\x18\b \x01(\x04R\aversion\x128\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x19.kiseki.v1.DeltaTimestampR\tcreatedAt\"[\n" +
	"\x0eShardWatermark\x12-\n" +
	"\bshard_id\x18\x01 \x01(\v2\x12.kiseki.v1.ShardIdR\ashardId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x04R\bposition\"\xc8\x02\n" +
	"\x14StreamProcessorState\x12*\n" +
	"\aview_id\x18\x01 \x01(\v2\x11.kiseki.v1.ViewIdR\x06viewId\x12-\n" +
	"\ttenant_id\x18\x02 \x01(\v2\x10.kiseki.v1.OrgIdR\btenantId\x129\n" +
	"\n" +
	"watermarks\x18\x03 \x03(\v2\x19.kiseki.v1.ShardWatermarkR\n" +
	"watermarks\x12-\n" +
	"\x12descriptor_version\x18\x04 \x01(\x04R\x11descriptorVersion\x128\n" +
	"\x06status\x18\x05 \x01(\v2 .kiseki.v1.StreamProcessorStatusR\x06status\x121\n" +
	"\x15has_cached_tenant_key\x18\x06 \x01(\bR\x12hasCachedTenantKey\"\xa1\x03\n" +
	"\x15StreamProcessorStatus\x12.\n" +
	"\arunning\x18\x01 \x01(\v2\x12.kiseki.v1.RunningH\x00R\arunning\x12P\n" +
	"\x13staleness_violation\x18\x02 \x01(\v2\x1d.kiseki.v1.StalenessViolationH\x00R\x12stalenessViolation\x12D\n" +
	"\x0fkey_unavailable\x18\x03 \x01(\v2\x19.kiseki.v1.KeyUnavailableH\x00R\x0ekeyUnavailable\x12M\n" +
	"\x12source_unavailable\x18\x04 \x01(\v2\x1c.kiseki.v1.SourceUnavailableH\x00R\x11sourceUnavailable\x12.\n" +
	"\astopped\x18\x05 \x01(\v2\x12.kiseki.v1.StoppedH\x00R\astopped\x127\n" +
	"\n" +
	"rebuilding\x18\x06 \x01(\v2\x15.kiseki.v1.RebuildingH\x00R\n" +
	"rebuildingB\b\n" +
	"\x06status\"\t\n" +
	"\aRunning\"1\n" +
	"\x12StalenessViolation\x12\x1b\n" +
	"\tbehind_ms\x18\x01 \x01(\x04R\bbehindMs\"\x10\n" +
	"\x0eKeyUnavailable\"=\n" +
	"\x11SourceUnavailable\x12(\n" +
	"\x05shard\x18\x01 \x01(\v2\x12.kiseki.v1.ShardIdR\x05shard\"\t\n" +
	"\aStopped\"/\n" +
	"\n" +
	"Rebuilding\x12!\n" +
	"\fprogress_pct\x18\x01 \x01(\x02R\vprogressPct\"\xc1\x01\n" +
	"\vMvccReadPin\x12\x15\n" +
	"\x06pin_id\x18\x01 \x01(\fR\x05pinId\x12*\n" +
	"\aview_id\x18\x02 \x01(\v2\x11.kiseki.v1.ViewIdR\x06viewId\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x04R\bposition\x122\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x13.kiseki.v1.WallTimeR\tcreatedAt\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\"N\n" +
	"\x11CreateViewRequest\x129\n" +
	"\n" +
	"descriptor\x18\x01 \x01(\v2\x19.kiseki.v1.ViewDescriptorR\n" +
	"descriptor\"s\n" +
	"\x12DiscardViewRequest\x12*\n" +
	"\aview_id\x18\x01 \x01(\v2\x11.kiseki.v1.ViewIdR\x06viewId\x121\n" +
	"\vapproved_by\x18\x02 \x01(\v2\x10.kiseki.v1.OrgIdR\n" +
	"approvedBy\"\x87\x01\n" +
	"\x17UpdateDescriptorRequest\x12*\n" +
	"\aview_id\x18\x01 \x01(\v2\x11.kiseki.v1.ViewIdR\x06viewId\x12@\n" +
	"\x0enew_descriptor\x18\x02 \x01(\v2\x19.kiseki.v1.ViewDescriptorR\rnewDescriptor\"`\n" +
	"\x11AcquirePinRequest\x12*\n" +
	"\aview_id\x18\x01 \x01(\v2\x11.kiseki.v1.ViewIdR\x06viewId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\rR\n" +
	"ttlSeconds\">\n" +
	"\x12AcquirePinResponse\x12(\n" +
	"\x03pin\x18\x01 \x01(\v2\x16.kiseki.v1.MvccReadPinR\x03pin*p\n" +
	"\x11ProtocolSemantics\x12\"\n" +
	"\x1ePROTOCOL_SEMANTICS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PROTOCOL_SEMANTICS_POSIX\x10\x01\x12\x19\n" +
	"\x15PROTOCOL_SEMANTICS_S3\x10\x02B2Z0github.com/witlox/kiseki/control/proto/kiseki/v1b\x06proto3"

var (
	file_kiseki_v1_view_proto_rawDescOnce sync.Once
	file_kiseki_v1_view_proto_rawDescData []byte
)

func file_kiseki_v1_view_proto_rawDescGZIP() []byte {
	file_kiseki_v1_view_proto_rawDescOnce.Do(func() {
		file_kiseki_v1_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kiseki_v1_view_proto_rawDesc), len(file_kiseki_v1_view_proto_rawDesc)))
	})
	return file_kiseki_v1_view_proto_rawDescData
}

var file_kiseki_v1_view_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kiseki_v1_view_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_kiseki_v1_view_proto_goTypes = []any{
	(ProtocolSemantics)(0),          // 0: kiseki.v1.ProtocolSemantics
	(*ConsistencyModel)(nil),        // 1: kiseki.v1.ConsistencyModel
	(*ReadYourWrites)(nil),          // 2: kiseki.v1.ReadYourWrites
	(*BoundedStaleness)(nil),        // 3: kiseki.v1.BoundedStaleness
	(*Eventual)(nil),                // 4: kiseki.v1.Eventual
	(*ViewDescriptor)(nil),          // 5: kiseki.v1.ViewDescriptor
	(*ShardWatermark)(nil),          // 6: kiseki.v1.ShardWatermark
	(*StreamProcessorState)(nil),    // 7: kiseki.v1.StreamProcessorState
	(*StreamProcessorStatus)(nil),   // 8: kiseki.v1.StreamProcessorStatus
	(*Running)(nil),                 // 9: kiseki.v1.Running
	(*StalenessViolation)(nil),      // 10: kiseki.v1.StalenessViolation
	(*KeyUnavailable)(nil),          // 11: kiseki.v1.KeyUnavailable
	(*SourceUnavailable)(nil),       // 12: kiseki.v1.SourceUnavailable
	(*Stopped)(nil),                 // 13: kiseki.v1.Stopped
	(*Rebuilding)(nil),              // 14: kiseki.v1.Rebuilding
	(*MvccReadPin)(nil),             // 15: kiseki.v1.MvccReadPin
	(*CreateViewRequest)(nil),       // 16: kiseki.v1.CreateViewRequest
	(*DiscardViewRequest)(nil),      // 17: kiseki.v1.DiscardViewRequest
	(*UpdateDescriptorRequest)(nil), // 18: kiseki.v1.UpdateDescriptorRequest
	(*AcquirePinRequest)(nil),       // 19: kiseki.v1.AcquirePinRequest
	(*AcquirePinResponse)(nil),      // 20: kiseki.v1.AcquirePinResponse
	(*ViewId)(nil),                  // 21: kiseki.v1.ViewId
	(*OrgId)(nil),                   // 22: kiseki.v1.OrgId
	(*ShardId)(nil),                 // 23: kiseki.v1.ShardId
	(*AffinityPoolId)(nil),          // 24: kiseki.v1.AffinityPoolId
	(*DeltaTimestamp)(nil),          // 25: kiseki.v1.DeltaTimestamp
	(*WallTime)(nil),                // 26: kiseki.v1.WallTime
}
var file_kiseki_v1_view_proto_depIdxs = []int32{
	2,  // 0: kiseki.v1.ConsistencyModel.read_your_writes:type_name -> kiseki.v1.ReadYourWrites
	3,  // 1: kiseki.v1.ConsistencyModel.bounded_staleness:type_name -> kiseki.v1.BoundedStaleness
	4,  // 2: kiseki.v1.ConsistencyModel.eventual:type_name -> kiseki.v1.Eventual
	21, // 3: kiseki.v1.ViewDescriptor.view_id:type_name -> kiseki.v1.ViewId
	22, // 4: kiseki.v1.ViewDescriptor.tenant_id:type_name -> kiseki.v1.OrgId
	23, // 5: kiseki.v1.ViewDescriptor.source_shards:type_name -> kiseki.v1.ShardId
	0,  // 6: kiseki.v1.ViewDescriptor.protocol:type_name -> kiseki.v1.ProtocolSemantics
	1,  // 7: kiseki.v1.ViewDescriptor.consistency:type_name -> kiseki.v1.ConsistencyModel
	24, // 8: kiseki.v1.ViewDescriptor.affinity_pool:type_name -> kiseki.v1.AffinityPoolId
	25, // 9: kiseki.v1.ViewDescriptor.created_at:type_name -> kiseki.v1.DeltaTimestamp
	23, // 10: kiseki.v1.ShardWatermark.shard_id:type_name -> kiseki.v1.ShardId
	21, // 11: kiseki.v1.StreamProcessorState.view_id:type_name -> kiseki.v1.ViewId
	22, // 12: kiseki.v1.StreamProcessorState.tenant_id:type_name -> kiseki.v1.OrgId
	6,  // 13: kiseki.v1.StreamProcessorState.watermarks:type_name -> kiseki.v1.ShardWatermark
	8,  // 14: kiseki.v1.StreamProcessorState.status:type_name -> kiseki.v1.StreamProcessorStatus
	9,  // 15: kiseki.v1.StreamProcessorStatus.running:type_name -> kiseki.v1.Running
	10, // 16: kiseki.v1.StreamProcessorStatus.staleness_violation:type_name -> kiseki.v1.StalenessViolation
	11, // 17: kiseki.v1.StreamProcessorStatus.key_unavailable:type_name -> kiseki.v1.KeyUnavailable
	12, // 18: kiseki.v1.StreamProcessorStatus.source_unavailable:type_name -> kiseki.v1.SourceUnavailable
	13, // 19: kiseki.v1.StreamProcessorStatus.stopped:type_name -> kiseki.v1.Stopped
	14, // 20: kiseki.v1.StreamProcessorStatus.rebuilding:type_name -> kiseki.v1.Rebuilding
	23, // 21: kiseki.v1.SourceUnavailable.shard:type_name -> kiseki.v1.ShardId
	21, // 22: kiseki.v1.MvccReadPin.view_id:type_name -> kiseki.v1.ViewId
	26, // 23: kiseki.v1.MvccReadPin.created_at:type_name -> kiseki.v1.WallTime
	5,  // 24: kiseki.v1.CreateViewRequest.descriptor:type_name -> kiseki.v1.ViewDescriptor
	21, // 25: kiseki.v1.DiscardViewRequest.view_id:type_name -> kiseki.v1.ViewId
	22, // 26: kiseki.v1.DiscardViewRequest.approved_by:type_name -> kiseki.v1.OrgId
	21, // 27: kiseki.v1.UpdateDescriptorRequest.view_id:type_name -> kiseki.v1.ViewId
	5,  // 28: kiseki.v1.UpdateDescriptorRequest.new_descriptor:type_name -> kiseki.v1.ViewDescriptor
	21, // 29: kiseki.v1.AcquirePinRequest.view_id:type_name -> kiseki.v1.ViewId
	15, // 30: kiseki.v1.AcquirePinResponse.pin:type_name -> kiseki.v1.MvccReadPin
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_kiseki_v1_view_proto_init() }
func file_kiseki_v1_view_proto_init() {
	if File_kiseki_v1_view_proto != nil {
		return
	}
	file_kiseki_v1_common_proto_init()
	file_kiseki_v1_chunk_proto_init()
	file_kiseki_v1_view_proto_msgTypes[0].OneofWrappers = []any{
		(*ConsistencyModel_ReadYourWrites)(nil),
		(*ConsistencyModel_BoundedStaleness)(nil),
		(*ConsistencyModel_Eventual)(nil),
	}
	file_kiseki_v1_view_proto_msgTypes[7].OneofWrappers = []any{
		(*StreamProcessorStatus_Running)(nil),
		(*StreamProcessorStatus_StalenessViolation)(nil),
		(*StreamProcessorStatus_KeyUnavailable)(nil),
		(*StreamProcessorStatus_SourceUnavailable)(nil),
		(*StreamProcessorStatus_Stopped)(nil),
		(*StreamProcessorStatus_Rebuilding)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kiseki_v1_view_proto_rawDesc), len(file_kiseki_v1_view_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kiseki_v1_view_proto_goTypes,
		DependencyIndexes: file_kiseki_v1_view_proto_depIdxs,
		EnumInfos:         file_kiseki_v1_view_proto_enumTypes,
		MessageInfos:      file_kiseki_v1_view_proto_msgTypes,
	}.Build()
	File_kiseki_v1_view_proto = out.File
	file_kiseki_v1_view_proto_goTypes = nil
	file_kiseki_v1_view_proto_depIdxs = nil
}
