# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kiseki.v1 import control_pb2 as kiseki_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kiseki/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """--- Control Plane Service (Go, management network) ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrganization = channel.unary_unary(
                '/kiseki.v1.ControlService/CreateOrganization',
                request_serializer=kiseki_dot_v1_dot_control__pb2.CreateOrganizationRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.CreateOrganizationResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/kiseki.v1.ControlService/CreateProject',
                request_serializer=kiseki_dot_v1_dot_control__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.CreateWorkload = channel.unary_unary(
                '/kiseki.v1.ControlService/CreateWorkload',
                request_serializer=kiseki_dot_v1_dot_control__pb2.CreateWorkloadRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.CreateWorkloadResponse.FromString,
                _registered_method=True)
        self.GetOrganization = channel.unary_unary(
                '/kiseki.v1.ControlService/GetOrganization',
                request_serializer=kiseki_dot_v1_dot_control__pb2.GetOrganizationRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.Organization.FromString,
                _registered_method=True)
        self.ListOrganizations = channel.unary_unary(
                '/kiseki.v1.ControlService/ListOrganizations',
                request_serializer=kiseki_dot_v1_dot_control__pb2.ListOrganizationsRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.ListOrganizationsResponse.FromString,
                _registered_method=True)
        self.CreateNamespace = channel.unary_unary(
                '/kiseki.v1.ControlService/CreateNamespace',
                request_serializer=kiseki_dot_v1_dot_control__pb2.CreateNamespaceRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.CreateNamespaceResponse.FromString,
                _registered_method=True)
        self.RequestAccess = channel.unary_unary(
                '/kiseki.v1.ControlService/RequestAccess',
                request_serializer=kiseki_dot_v1_dot_control__pb2.AccessRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.AccessRequestResponse.FromString,
                _registered_method=True)
        self.ApproveAccess = channel.unary_unary(
                '/kiseki.v1.ControlService/ApproveAccess',
                request_serializer=kiseki_dot_v1_dot_control__pb2.ApproveAccessRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.ApproveAccessResponse.FromString,
                _registered_method=True)
        self.DenyAccess = channel.unary_unary(
                '/kiseki.v1.ControlService/DenyAccess',
                request_serializer=kiseki_dot_v1_dot_control__pb2.DenyAccessRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.DenyAccessResponse.FromString,
                _registered_method=True)
        self.SetQuota = channel.unary_unary(
                '/kiseki.v1.ControlService/SetQuota',
                request_serializer=kiseki_dot_v1_dot_control__pb2.SetQuotaRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.SetQuotaResponse.FromString,
                _registered_method=True)
        self.SetComplianceTags = channel.unary_unary(
                '/kiseki.v1.ControlService/SetComplianceTags',
                request_serializer=kiseki_dot_v1_dot_control__pb2.SetComplianceTagsRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.SetComplianceTagsResponse.FromString,
                _registered_method=True)
        self.SetRetentionHold = channel.unary_unary(
                '/kiseki.v1.ControlService/SetRetentionHold',
                request_serializer=kiseki_dot_v1_dot_control__pb2.SetRetentionHoldRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.SetRetentionHoldResponse.FromString,
                _registered_method=True)
        self.ReleaseRetentionHold = channel.unary_unary(
                '/kiseki.v1.ControlService/ReleaseRetentionHold',
                request_serializer=kiseki_dot_v1_dot_control__pb2.ReleaseRetentionHoldRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.ReleaseRetentionHoldResponse.FromString,
                _registered_method=True)
        self.ListFlavors = channel.unary_unary(
                '/kiseki.v1.ControlService/ListFlavors',
                request_serializer=kiseki_dot_v1_dot_control__pb2.ListFlavorsRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.ListFlavorsResponse.FromString,
                _registered_method=True)
        self.MatchFlavor = channel.unary_unary(
                '/kiseki.v1.ControlService/MatchFlavor',
                request_serializer=kiseki_dot_v1_dot_control__pb2.MatchFlavorRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.MatchFlavorResponse.FromString,
                _registered_method=True)
        self.RegisterPeer = channel.unary_unary(
                '/kiseki.v1.ControlService/RegisterPeer',
                request_serializer=kiseki_dot_v1_dot_control__pb2.RegisterPeerRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.RegisterPeerResponse.FromString,
                _registered_method=True)
        self.ListPeers = channel.unary_unary(
                '/kiseki.v1.ControlService/ListPeers',
                request_serializer=kiseki_dot_v1_dot_control__pb2.ListPeersRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.ListPeersResponse.FromString,
                _registered_method=True)
        self.SetMaintenanceMode = channel.unary_unary(
                '/kiseki.v1.ControlService/SetMaintenanceMode',
                request_serializer=kiseki_dot_v1_dot_control__pb2.SetMaintenanceModeRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_control__pb2.SetMaintenanceModeResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """--- Control Plane Service (Go, management network) ---

    """

    def CreateOrganization(self, request, context):
        """Tenant lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWorkload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrganizations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNamespace(self, request, context):
        """Namespace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAccess(self, request, context):
        """IAM / zero-trust boundary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DenyAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetQuota(self, request, context):
        """Policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetComplianceTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRetentionHold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseRetentionHold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFlavors(self, request, context):
        """Flavor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchFlavor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPeer(self, request, context):
        """Federation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaintenanceMode(self, request, context):
        """Maintenance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganization,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.CreateOrganizationRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.CreateOrganizationResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.CreateProjectRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.CreateProjectResponse.SerializeToString,
            ),
            'CreateWorkload': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkload,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.CreateWorkloadRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.CreateWorkloadResponse.SerializeToString,
            ),
            'GetOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganization,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.GetOrganizationRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.Organization.SerializeToString,
            ),
            'ListOrganizations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.ListOrganizationsRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.ListOrganizationsResponse.SerializeToString,
            ),
            'CreateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNamespace,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.CreateNamespaceRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.CreateNamespaceResponse.SerializeToString,
            ),
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.AccessRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.AccessRequestResponse.SerializeToString,
            ),
            'ApproveAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAccess,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.ApproveAccessRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.ApproveAccessResponse.SerializeToString,
            ),
            'DenyAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.DenyAccess,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.DenyAccessRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.DenyAccessResponse.SerializeToString,
            ),
            'SetQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.SetQuota,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.SetQuotaRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.SetQuotaResponse.SerializeToString,
            ),
            'SetComplianceTags': grpc.unary_unary_rpc_method_handler(
                    servicer.SetComplianceTags,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.SetComplianceTagsRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.SetComplianceTagsResponse.SerializeToString,
            ),
            'SetRetentionHold': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRetentionHold,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.SetRetentionHoldRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.SetRetentionHoldResponse.SerializeToString,
            ),
            'ReleaseRetentionHold': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseRetentionHold,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.ReleaseRetentionHoldRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.ReleaseRetentionHoldResponse.SerializeToString,
            ),
            'ListFlavors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFlavors,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.ListFlavorsRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.ListFlavorsResponse.SerializeToString,
            ),
            'MatchFlavor': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchFlavor,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.MatchFlavorRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.MatchFlavorResponse.SerializeToString,
            ),
            'RegisterPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPeer,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.RegisterPeerRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.RegisterPeerResponse.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.ListPeersRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.ListPeersResponse.SerializeToString,
            ),
            'SetMaintenanceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaintenanceMode,
                    request_deserializer=kiseki_dot_v1_dot_control__pb2.SetMaintenanceModeRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_control__pb2.SetMaintenanceModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiseki.v1.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiseki.v1.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """--- Control Plane Service (Go, management network) ---

    """

    @staticmethod
    def CreateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/CreateOrganization',
            kiseki_dot_v1_dot_control__pb2.CreateOrganizationRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.CreateOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/CreateProject',
            kiseki_dot_v1_dot_control__pb2.CreateProjectRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWorkload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/CreateWorkload',
            kiseki_dot_v1_dot_control__pb2.CreateWorkloadRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.CreateWorkloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/GetOrganization',
            kiseki_dot_v1_dot_control__pb2.GetOrganizationRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.Organization.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/ListOrganizations',
            kiseki_dot_v1_dot_control__pb2.ListOrganizationsRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.ListOrganizationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/CreateNamespace',
            kiseki_dot_v1_dot_control__pb2.CreateNamespaceRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.CreateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/RequestAccess',
            kiseki_dot_v1_dot_control__pb2.AccessRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.AccessRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/ApproveAccess',
            kiseki_dot_v1_dot_control__pb2.ApproveAccessRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.ApproveAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DenyAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/DenyAccess',
            kiseki_dot_v1_dot_control__pb2.DenyAccessRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.DenyAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/SetQuota',
            kiseki_dot_v1_dot_control__pb2.SetQuotaRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.SetQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetComplianceTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/SetComplianceTags',
            kiseki_dot_v1_dot_control__pb2.SetComplianceTagsRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.SetComplianceTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRetentionHold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/SetRetentionHold',
            kiseki_dot_v1_dot_control__pb2.SetRetentionHoldRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.SetRetentionHoldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseRetentionHold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/ReleaseRetentionHold',
            kiseki_dot_v1_dot_control__pb2.ReleaseRetentionHoldRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.ReleaseRetentionHoldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFlavors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/ListFlavors',
            kiseki_dot_v1_dot_control__pb2.ListFlavorsRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.ListFlavorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchFlavor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/MatchFlavor',
            kiseki_dot_v1_dot_control__pb2.MatchFlavorRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.MatchFlavorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/RegisterPeer',
            kiseki_dot_v1_dot_control__pb2.RegisterPeerRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.RegisterPeerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/ListPeers',
            kiseki_dot_v1_dot_control__pb2.ListPeersRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.ListPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMaintenanceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.ControlService/SetMaintenanceMode',
            kiseki_dot_v1_dot_control__pb2.SetMaintenanceModeRequest.SerializeToString,
            kiseki_dot_v1_dot_control__pb2.SetMaintenanceModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
