# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kiseki.v1 import log_pb2 as kiseki_dot_v1_dot_log__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kiseki/v1/log_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogServiceStub(object):
    """============================================================================
    LogService — data-path gRPC for delta read/write
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendDelta = channel.unary_unary(
                '/kiseki.v1.LogService/AppendDelta',
                request_serializer=kiseki_dot_v1_dot_log__pb2.AppendDeltaRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_log__pb2.AppendDeltaResponse.FromString,
                _registered_method=True)
        self.ReadDeltas = channel.unary_unary(
                '/kiseki.v1.LogService/ReadDeltas',
                request_serializer=kiseki_dot_v1_dot_log__pb2.ReadDeltasRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_log__pb2.ReadDeltasResponse.FromString,
                _registered_method=True)
        self.ShardHealth = channel.unary_unary(
                '/kiseki.v1.LogService/ShardHealth',
                request_serializer=kiseki_dot_v1_dot_log__pb2.ShardHealthRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_log__pb2.ShardHealthResponse.FromString,
                _registered_method=True)
        self.SetMaintenance = channel.unary_unary(
                '/kiseki.v1.LogService/SetMaintenance',
                request_serializer=kiseki_dot_v1_dot_log__pb2.SetMaintenanceRequest.SerializeToString,
                response_deserializer=kiseki_dot_v1_dot_log__pb2.SetMaintenanceResponse.FromString,
                _registered_method=True)


class LogServiceServicer(object):
    """============================================================================
    LogService — data-path gRPC for delta read/write
    ============================================================================

    """

    def AppendDelta(self, request, context):
        """Append a delta to a shard. Returns the assigned sequence number.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDeltas(self, request, context):
        """Read deltas in [from, to] inclusive from a shard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShardHealth(self, request, context):
        """Get shard health and metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaintenance(self, request, context):
        """Set or clear maintenance mode on a shard (I-O6).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendDelta,
                    request_deserializer=kiseki_dot_v1_dot_log__pb2.AppendDeltaRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_log__pb2.AppendDeltaResponse.SerializeToString,
            ),
            'ReadDeltas': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDeltas,
                    request_deserializer=kiseki_dot_v1_dot_log__pb2.ReadDeltasRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_log__pb2.ReadDeltasResponse.SerializeToString,
            ),
            'ShardHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ShardHealth,
                    request_deserializer=kiseki_dot_v1_dot_log__pb2.ShardHealthRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_log__pb2.ShardHealthResponse.SerializeToString,
            ),
            'SetMaintenance': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaintenance,
                    request_deserializer=kiseki_dot_v1_dot_log__pb2.SetMaintenanceRequest.FromString,
                    response_serializer=kiseki_dot_v1_dot_log__pb2.SetMaintenanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiseki.v1.LogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kiseki.v1.LogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogService(object):
    """============================================================================
    LogService — data-path gRPC for delta read/write
    ============================================================================

    """

    @staticmethod
    def AppendDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.LogService/AppendDelta',
            kiseki_dot_v1_dot_log__pb2.AppendDeltaRequest.SerializeToString,
            kiseki_dot_v1_dot_log__pb2.AppendDeltaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDeltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.LogService/ReadDeltas',
            kiseki_dot_v1_dot_log__pb2.ReadDeltasRequest.SerializeToString,
            kiseki_dot_v1_dot_log__pb2.ReadDeltasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShardHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.LogService/ShardHealth',
            kiseki_dot_v1_dot_log__pb2.ShardHealthRequest.SerializeToString,
            kiseki_dot_v1_dot_log__pb2.ShardHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMaintenance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kiseki.v1.LogService/SetMaintenance',
            kiseki_dot_v1_dot_log__pb2.SetMaintenanceRequest.SerializeToString,
            kiseki_dot_v1_dot_log__pb2.SetMaintenanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
